### ISSUE TITLE
Add stopwatch

### ISSUE THREAD

**Issue by hitanshu-mehta** [cpeditor/cpeditor#1005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

I usually keep track of the time taken to solve the problem. I think a stopwatch would be a useful feature.

### Describe the feature you'd like

- Add an option in settings to make the stopwatch visible in the right panel.
- If the option is enabled then display the stopwatch in the right panel with the start/stop and reset buttons.

<details>
<summary>It looks something like this.</summary>

![Screenshot_20211104_223101](https://user-images.githubusercontent.com/44025541/140385607-a51543c6-4058-49f1-a461-9c49a9d38082.png)
</details>

### Describe alternatives you've considered

N/A

### Are you willing to contribute to this?

- [X] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

### Anything else?

Discussion: https://github.com/cpeditor/cpeditor/discussions/1004

**Comment by ouuan** [comment]
I suggest these options in the preferences:

1.  Start when the tab is created.
2.  Start when the tab is visited for at least 5 seconds.
3.  Start when switching to this tab and pause when switching to other tabs.
4.  Pause when submit.

However, I personally don't use this feature, so I'm not sure if these are useful.

**Comment by swift-zym** [comment]
Why do we need a builtin stopwatch in cpeditor? When you solving a problem, your focus may not always be on the editor, so cpeditor actually doesn't know anything more than an external stopwatch software.

**Comment by coder3101** [comment]
> Why do we need a builtin stopwatch in cpeditor? When you solving a problem, your focus may not always be on the editor, so cpeditor actually doesn't know anything more than an external stopwatch software.

Just to keep track of how long you took to solve the problem. You could use external stopwatch or rely on system time as well but this just makes it more easier and anything that helps in CP should be in CP Editor.

**Comment by Ravenclaw-OIer** [comment]
Have you implemented this feature yourself or the image is photoshopped?

From LilyWhite with love
________________________________

**Comment by hitanshu-mehta** [comment]
@Ravenclaw-OIer I have implemented it using QElapsedTimer class. You can check out here-> https://github.com/hitanshu-mehta/cpeditor/commit/099e8d69a24ad961d85d21e5b5d9f12be8a37517
