### ISSUE TITLE
(ksyntax-branch) Using Competitve Companion in brower opens a new blank tab

### ISSUE THREAD

**Issue by tusqasi** [cpeditor/cpeditor#1011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using Competitve Companion in brower opens a new blank tab.
Pressing the keybinding to send the test cases to cpeditor, doesn't populate the template only test cases are filled up.

![image](https://user-images.githubusercontent.com/24749908/141610060-01480c16-d4cd-4988-9bf3-13329c0c716f.png)

### Expected Behavior

Template filled in properly.

![image](https://user-images.githubusercontent.com/24749908/141610101-ab2ea9c5-90e6-4955-a185-9db935ed147e.png)

### Steps To Reproduce

1. use ksyntax-branch
2. press keybinding on any problem

### CP Editor Version

6.10

### OS

pop os, linux

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

### Anything else?

Let me know if something is ambiguous, or not clear

**Comment by tusqasi** [comment]
arrow position on the first image is misleading, test cases are fine , the big empty in the editor is the problem

**Comment by ouuan** [comment]
fixed
