### ISSUE TITLE
Shortcuts to select and delete single lines

### ISSUE THREAD

**Issue by Sriram-L** [cpeditor/cpeditor#1025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### Describe the feature you'd like

Need for more shortcuts

So far so good..
In competitive programming, more keyboard shortcuts -> better experience
It would be really nice to have shortcuts to select and delete lines, as sometimes we want to delete an entire line to enter something new..

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
Do you mean <kbd>Ctrl+Shift+K</kbd> or <kbd>Ctrl+Shift+K</kbd> and <kbd>Ctrl+Shift+Enter</kbd>?

**Comment by ouuan** [comment]
We are also planning to add a Vim mode, which has `cc` to do this.
