### ISSUE TITLE
Main window automatically getting closed on font customization in snap edge version

### ISSUE THREAD

**Issue by Sriram-L** [cpeditor/cpeditor#1027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever I try to change the font of any of the text in the editor, the entire application automatically gets closed.

### Expected Behavior

Different font options must appear in a separate window.

### Steps To Reproduce

1. Open cpeditor -> Preferences -> Appearance -> Fonts
2. Click on any of the font options
3. The window closes.

### CP Editor Version

6.10.1 (snap edge release)

### OS

Ubuntu 21.04

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by Sriram-L** [comment]
I would also like to add one more detail...
The application was installed through snap store. When I tried `cpeditor --version` on terminal, it gave me a warning saying 

`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.`

I have a slight feeling this might be an issue closely related to the gnome environment I am using. Not an expert in this field,  just wanted to let the devs know.

**Comment by Sriram-L** [comment]
Update: It seems the same version installed through the  debian package downloaded directly from the source does not cause the same problem. Only the snap version causes this bug.

**Comment by coder3101** [comment]
There is no snap package for beta version. Are you sure? Only stable and edge releases are published.

**Comment by coder3101** [comment]
Please update the title and description as per your finding. We will confirm and track the issue. 

Thanks!

**Comment by Sriram-L** [comment]
My bad, I meant the latest/edge release in snap store.
