### ISSUE TITLE
Undoing a Find & Replace All should be done in a single step

### ISSUE THREAD

**Issue by Sriram-L** [cpeditor/cpeditor#1036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After using the find and replace to replace a particular word, if I wanted to undo, the undoing happens in steps i.e, only one word at a time reverts back.

### Expected Behavior

In VS Code, find and replace all is considered as a single action, and a single undo command reverts all the occurences back to the original word. 

### Steps To Reproduce

1. Type something in a file
2. Use find and replace to replace all occurences of a word
3. Try undoing the operation

### CP Editor Version

6.10.1

### OS

Ubuntu 21.04

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
@all-contributors add @Sriram-L as a contributor for reporting bugs.
