### ISSUE TITLE
Installation warning on windows

### ISSUE THREAD

**Issue by namantam1** [cpeditor/cpeditor#1049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Show warning during installation on windows 11 due to an unknown publisher.

![image](https://user-images.githubusercontent.com/59503233/153278141-85f872a3-3142-41eb-b5b7-dd7f8ce36eb8.png)

### Expected Behavior

It should be installed without any warnings.

### Steps To Reproduce

1. Download the latest release https://github.com/cpeditor/cpeditor/releases/download/6.9.4/cpeditor-6.9.4-windows-x64-setup.exe.
2. Double click on it to install.

### CP Editor Version

6.9.4

### OS

Windows 11

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

### Anything else?

Maybe adding a publisher will remove this warning. I am not sure If I am correct, I am adding this issue as I did not find any issue related to it.

Anyway, I like this editor 😎 a lot.

**Comment by ouuan** [comment]
It's not easy to remove this warning. See https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro

If we don't buy a code signing certificate, we'll need to submit all release assets for malware analysis and then wait for some time. I didn't try it so I don't know how long this would take, but I don't think it's very important.
