### ISSUE TITLE
Code may be Accidentally Lost when Autosave is Turned on

### ISSUE THREAD

**Issue by Acfboy** [cpeditor/cpeditor#1059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When CP editor is reopened after unexpected exit, it will return to the page before the last normal shutdown, and all codes will become the page before the last normal shutdown. If auto save is enabled, the previous code will be saved again, so the code is lost.

### Expected Behavior

Saved files should not be rolled back.

### Steps To Reproduce

I am sorry that I can't create unexpected exit at any time.

### CP Editor Version

6.8.2

### OS

Windows 7

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
@all-contributors add @Acfboy as a contributor for reporting a bug.

**Comment by Acfboy** [comment]
I am sorry about that I didn't read the document carefully, this problem can be solved by "Auto-save the current session periodically".
