### ISSUE TITLE
The "Compile and Run" option takes the compilation time into account

### ISSUE THREAD

**Issue by GoodCoder666** [cpeditor/cpeditor#1069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just write a program that takes a lot of time for compiling, click "Compile and Run", and the judger seems to take the compilation time into account (sometimes only for the first test case). Here is an example below.
<img width="388" alt="image" src="https://user-images.githubusercontent.com/59763425/161029674-ea2965e0-a1ed-4850-a374-609ed043288c.png">
If I set the excution time limit to 1000ms in this case, CP Editor will display TLE and running it again may solve the problem.

### Expected Behavior

Well, in the case above, I'd like to see this:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/59763425/161030539-546ff8f1-8dc2-4606-8c66-e819108fce9d.png">

### Steps To Reproduce

1. write a program that takes a lot of time for compiling
2. click "Compile and Run"

### CP Editor Version

6.9.4

### OS

Windows 11

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
<https://cpeditor.org/docs/faq/#my-code-gets-tle-on-every-first-execution-after-compilation>
