### ISSUE TITLE
We need new interface fonts

### ISSUE THREAD

**Issue by flics0502** [cpeditor/cpeditor#1074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

Well, I just downloaded the cpeditor, it was amzing. A fantastic editor of oi. But the interface font of the cpeditor in windows was **bad**. They looks like "宋体".

### Describe the feature you'd like

I hope that we have some new font to choose, or refresh the interface. I know that this is not a technical issues, but it really affects the work.

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment]
<https://cpeditor.org/docs/preferences/appearance/#custom-application-font>
