### ISSUE TITLE
Support to make the End jump to the first character which is not a space

### ISSUE THREAD

**Issue by zhk1211** [cpeditor/cpeditor#1089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

When I press the End, I need to press right to move to the the first character which is not a space.

### Describe the feature you'd like

Make the End jump to the first character which is not a space.

### Are you willing to contribute to this?

- [X] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment]
Is it <kbd>Home</kbd> instead of <kbd>End</kbd>? There's #774 for it.
