### ISSUE TITLE
wrong shortcut key

### ISSUE THREAD

**Issue by zhk1211** [cpeditor/cpeditor#1092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I set up the shortcut key, but there's something wrong.

![](https://s1.328888.xyz/2022/07/16/NCNHy.png)

but when I press the key

![](https://s1.328888.xyz/2022/07/16/NCuwR.png)

### Expected Behavior

You know it.

### Steps To Reproduce

I don't know.

### CP Editor Version

6.9.4

### OS

Mac

### Are you willing to contribute to this?

- [X] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by swift-zym** [comment]
@zhk1211 It seems that you should also set up a shortcut for "Run Only" since its default shortcut is Command+R.

**Comment by zhk1211** [comment]
@swift-zym so how to deal with it

**Comment by swift-zym** [comment]
> @swift-zym so how to deal with it

Just setup a different shortcut for "Run Only".

**Comment by zhk1211** [comment]
@swift-zym I don't need the shortcut for "Run Only"

**Comment by zhk1211** [comment]
@ouuan

**Comment by ouuan** [comment]
Duplicate of #214
