### ISSUE TITLE
Support only-run mode & only-compile mode in CMD window

### ISSUE THREAD

**Issue by BoringHacker** [cpeditor/cpeditor#1097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [x] I have checked the changelog

### The problem you are facing

When I come to a situation that my code went wrong and I have to debug it out, I would do better using CMD windows. CP editor does not support the only-run mode & only-compile mode in CMD windows, which has frustrated me.

### Describe the feature you'd like

I shall appreciate it if developers could add this small feature to CP editor, the only-run & only-compile mod in CMD windows (just like what Dev-C++ has supported long long ago).

### Describe alternatives you've considered

.

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
What are "CMD windows"? Do you mean detached run which now compiles in every execution?

**Comment by noobyogi0010** [comment]
@BoringHacker 
Do you mean having a cmd to run or compile a specific script using a command prompt?

**Comment by BoringHacker** [comment]
Sorry for confusing statements... but I recently abandoned this editor, so nothing should be discussed any further...
