### ISSUE TITLE
Missing some Chinese fonts

### ISSUE THREAD

**Issue by xgugugu** [cpeditor/cpeditor#1099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

CP Editor can only select a few Chinese fonts, and most of them can't display beautifully (sorry my english is not very good).

### Expected Behavior

Other Chinese fonts such as "Microsoft Yahei" can be selected.

### Steps To Reproduce

Options -> Preferences -> Appearance -> Font -> Open "Select Font" Window -> Set "Writing System" to "Simplified Chinese"

### CP Editor Version

6.9.4

### OS

Windows 10/11

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
You checked the monospace-only checkbox. Many Chinese fonts are not monospaced, so you need to uncheck that checkbox to use them.
