### ISSUE TITLE
Clutter Free Comment

### ISSUE THREAD

**Issue by m3h3d1** [cpeditor/cpeditor#1120]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

Current commenting method seems messy when I comment multiple lines using **ctrl + /**. Different lines follows different indentation to comment. 

![image](https://user-images.githubusercontent.com/39239695/204089793-4503cde0-7fb5-49b9-80ca-f63163c77230.png)

### Describe the feature you'd like

It would be great if all the selected lines followed the same indentation to comment like this one.

![image](https://user-images.githubusercontent.com/39239695/204090002-42f2b20b-27e5-48ef-91d9-1523f61c4757.png)

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by Backl1ght** [comment]
dup with #1033
