### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by D4NZ-jpg** [cpeditor/cpeditor#1130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### Describe the feature you'd like

I would like to help by adding a Spanish translation. I want to start with the application texts, then website and docs. I'm new to qt, so might need a bit of help setting up the .ts file.

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment]
Add `es_MX` in `tools/updateTranslation.sh`/`.bat` and run it to get the `.ts` file. See #1050 for other changes needed.
