### ISSUE TITLE
Test case number

### ISSUE THREAD

**Issue by dipeshyadav331** [cpeditor/cpeditor#1138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

I sumbit a problem on codeforces and it says wrong answer on test 2 and in test 2 it is the 23rd case , so I have to count it 1 ,  2 ,3 4,5... so on than find the 23rd case. after than before sumbitting again , I run and check all cases , so out of 500+ cases in the second test case there are about 30-80 test cases visible , so in the input I have to tell that how many cases are there else run time error is given so again I have to count all the cases and tell in the input how many cases are there in this test case.

### Describe the feature you'd like

if we are shown in the input that which test case  is this just like we are shown in sublime text.

### Describe alternatives you've considered

Sublime text
![Screenshot 2023-01-06 175042](https://user-images.githubusercontent.com/122032063/211011700-d2e2c836-af91-438b-817d-206cfdd86cf8.jpg)
clearly showing their are 88 test cases but not in cp editor , in cp editor I don't know how many cases are there before every test case counting should be written it would help a lot
![Screenshot 2023-01-06 175236](https://user-images.githubusercontent.com/122032063/211011999-c61d6ae9-62c0-40d5-a482-07a857b8cc5e.jpg)

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by swift-zym** [comment]
But most of the time there is more than one line in a single testcase, will it help to just add a line number?

**Comment by dipeshyadav331** [comment]
But in sublime text if a test case consists of multiple lines it is considered a single line 
![Screenshot 2023-01-06 213435](https://user-images.githubusercontent.com/122032063/211050596-d3945400-1251-450b-b8b5-23c65638fb99.jpg)

**Comment by ouuan** [comment]
I suppose you should know the difference between a display line and a text line. If a text line is too long to be displayed on the screen, Sublime wraps it into multiple display lines. But a test case often contains more than a single text line, and it's impossible to know which lines belong to which test case without the knowledge of the problem.

It's possible but non-trivial to display line numbers for the test cases, and I think they are rarely helpful. When you really need the line numbers, you can simply copy the test case to other editors or a new tab of CP Editor.
