### ISSUE TITLE
Variables incorrectly highlighted as functions when initialized via parentheses

### ISSUE THREAD

**Issue by Alex-Github-Programmer** [cpeditor/cpeditor#1139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

initializing variables with a subsequent opening parenthese will make them highlighted like functions, as we can see in the folowing code:

```cpp
struct Point{
	int x,y;
	Point(int x,int y):x(x),y(y){}
};
Point point(1,2);
```

In this case, both of the initialized class members in the member initializer list and the variable `point` are incorrectly highlighted as if they are functions; that is, green in Monokai, for example.

### Expected Behavior

These are definitely not functions, so let's make them displayed the same as other variables.

### Steps To Reproduce

Open a file and paste the example code. See how it is highlighted.

### CP Editor Version

6.10.2

### OS

Windows 7 

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

### Anything else?

I know Windows 7 is out of date, but this might be easily reproduced in other OS's.

Maybe the highlighter considers every identifier succeeded by an opening parenthese as a function, but sometimes it is not.

**Comment by Alex-Github-Programmer** [comment]
Also, I suggest that when a pair of braces is used to declare a struct or a class, a semicolon should be automatically inserted after the closing brace.

**Comment by ouuan** [comment]
There are many types of incorrect highlighting. They are now tracked in #174, so this is a duplicate.
