### ISSUE TITLE
Language server crashed without prompt

### ISSUE THREAD

**Issue by xgugugu** [cpeditor/cpeditor#1140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I open 5 or more c++ source files at the same time, the language server (clanged) will crash without any prompt.

![图片](https://user-images.githubusercontent.com/85472190/212609974-723ecd7e-eb8b-4a79-970b-950e9a993131.png)
4 source files

![图片](https://user-images.githubusercontent.com/85472190/212609773-a3d2d94d-afca-40f3-b84c-559f9d73b46b.png)
5 source files

### Expected Behavior

Language server can run well with more source files. If cannot, there should be a prompt.

### Steps To Reproduce

1. Open 5 or more c++ source files (With language server clangd)
2. Then restart cpedtior
3. Language server will crash without prompt

### CP Editor Version

6.10.2

### OS

Manjaro

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

### Anything else?

This cpeditor package is from [aur](https://aur.archlinux.org/packages/cpeditor)

**Comment by ouuan** [comment]
I can't reproduce this on my Arch Linux. Does the content of the code matter? Can you reproduce it with other codes like a simple hello world or a bare `int main(){error}`? What are your LSP settings?

**Comment by xgugugu** [comment]
I haven't set any LSP settings.

Reproduce this with a bare `int main(){error}`
![图片](https://user-images.githubusercontent.com/85472190/212620143-775232c3-cc6d-4f17-8ba6-f6bf035b57b2.png)
![图片](https://user-images.githubusercontent.com/85472190/212620207-064ee67b-854c-45e9-8388-1683c04cb49f.png)

Several warnings in the log file:
```
[2023-01-16T15:19:46.494][WARN ][   onLSPServerProcessError    ][      LanguageServer.cpp      ](286)::LSP Process errored out <error>: [1], 
[2023-01-16T15:19:46.494][WARN ][  onLSPServerProcessFinished  ][      LanguageServer.cpp      ](318)::LSP Finished with exit code 9<language>: [C++], <status>: [1], 
```
