### ISSUE TITLE
DATE AND TIME

### ISSUE THREAD

**Issue by dipeshyadav331** [cpeditor/cpeditor#1142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have enabled date and time but still It is not coming in comments.
![Screenshot 2023-01-21 165608](https://user-images.githubusercontent.com/122032063/213864962-b7dee83b-569c-48c0-b29b-af5dad2391c0.jpg)
as you can see in the above screenshot no date and time is showing
![Screenshot 2023-01-21 165710](https://user-images.githubusercontent.com/122032063/213864968-7abac1d6-b142-4b3c-8194-d5a5a692edd2.jpg)

### Expected Behavior

Date and time should be visible

### Steps To Reproduce

parse problem

### CP Editor Version

6.10.2

### OS

Windows 11

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

### Anything else?

Thanks

**Comment by ouuan** [comment]
You have set the time format but have not added `${time}` in the comment template. See https://cpeditor.org/docs/preferences/extensions/#head-comments.

But it's indeed misleading as `${time}` is not in the default head comment template.

**Comment by ouuan** [comment]
> But it's indeed misleading as `${time}` is not in the default head comment template.

This dates back to when the head comments were not customizable, and time was not in the hardcoded head comment template. I added the ability to include time in the template but did not change the default template.

**Comment by dipeshyadav331** [comment]
It worked , thanks a lot
