### ISSUE TITLE
unable to run the program

### ISSUE THREAD

**Issue by saurabhkaramankar** [cpeditor/cpeditor#1147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot (419)](https://user-images.githubusercontent.com/70636541/216799820-40e39729-933e-48ec-b05c-9ad3b70dfedb.png)

### Expected Behavior

why failing to start compiler

### Steps To Reproduce

open cp editor
type a program
compile and run
after that getting above error

### CP Editor Version

6.10.2

### OS

Windows 10

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

### Anything else?

no

**Comment by ouuan** [comment]
#1146
