### ISSUE TITLE
Collapse Function

### ISSUE THREAD

**Issue by dipeshyadav331** [cpeditor/cpeditor#1177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

why can't we collapse a function , if there are multiple if else statements , I want to collapse them and reopen them when needed.

### Describe the feature you'd like

Collapse a function , if statement , while loop , for loop

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by coder3101** [comment]
This feature is called `code folding`, this is being implemented as part of #1101
