### ISSUE TITLE
Add more themes

### ISSUE THREAD

**Issue by demss233** [cpeditor/cpeditor#1179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### Describe the feature you'd like

please add new themes

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
New themes are a part of the KSyntaxHighlighter refactor, but this is actually the first issue to explicitly request new themes so it's not a duplicate.

**Comment by coder3101** [comment]
Complete list of new themes as part of #1101 are [here](https://github.com/KDE/syntax-highlighting/tree/master/data/themes)

**Comment by coder3101** [comment]
This issue has been closed because    new themes are available in alpha builds, in subsequent releases it will rollout to beta and finally to stable.

**Comment by demss233** [comment]
can we download alpha builds ?

**Comment by coder3101** [comment]
Follow these steps. https://cpeditor.org/docs/installation/use-artifacts/

You might encounter DLL missing error on windows, you can extract the missing DLL from [this](https://github.com/rogeryoungh/cpeditor/releases/download/7.0.0/cpeditor-7.0.0-windows-x64-portable.zip) and place them where cpeditor.exe is located.
