### ISSUE TITLE
Keybindings

### ISSUE THREAD

**Issue by Xelewet** [cpeditor/cpeditor#1182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

I wasn't able to find Replace mode in Cp editor, I've read documentation and TIPS, and haven't find it.
And also about Ctrl+L would be better than Ctrl+Shift+K

### Describe the feature you'd like

I wasn't able to find Replace mode in Cp editor, I've read documentation and TIPS, and haven't find it.
And also about Ctrl+L would be better than Ctrl+Shift+K

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
Find Replace: the typical <kbd>Ctr+F</kbd>

Customization: #214
