### ISSUE TITLE
CP Editor Sucks on TLE

### ISSUE THREAD

**Issue by dipeshyadav331** [cpeditor/cpeditor#1189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have set the time limit to 2 seconds , but whenever there is an infinite loop in the program , something as java(tm) platform binary 
starts and the system hangs , I have to end task this java(tm) platform binary from task manager , there it consumes upto 2 gb of ram , and If there are 3 different test cases , then 3 processes of java(tm) platform binary starts in task manager. 

This problem also occured in sublime text but there was a fix there to prevent entering task manager/ restart 

### Expected Behavior

If I get a tle , the build should be cancelled there only , but it keeps on running in the background.

### Steps To Reproduce

1. open .java file
2. run an infinite loop in bfs/dfs
3. see the task manager , system would slow down a process name java(tm) platform binary would start and it would consume 2gb ram and it would use 100% cpu.
4. kill the task from task manager or restart 

### CP Editor Version

6.10.3

### OS

Windows 10

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

### Anything else?

Please fix it as soon as possible , it is really frustating

**Comment by dipeshyadav331** [comment]
1. it happens for while(true); also , but it does not consume ram and cpu usage consumption is just slighlty above normal , but when it's a tle with memory allocation , it consumes 2-3 gb of ram and system hangs.
2. I have not tried with c++ / python
3. I was not aware of this Ctrl + k , I did it just now and it actually works , shouldn't the process be killed as soon as we get tle , because after getting tle , then pressing Ctrl + k , takes a delay of 4-5 seconds as the cpu usage touches 100%.
Thanks

**Comment by ouuan** [comment]
The processes are killed by CP Editor on my machine. Please try C++ or Python for further troubleshooting.

**Comment by dipeshyadav331** [comment]
Sorry , python and c++ are not installed on my device , I would use Ctrl+k , from the next time after getting tle.
I love cp editor , it's the best
