### ISSUE TITLE
Fixedsys font size not increasing

### ISSUE THREAD

**Issue by darthplgaueis** [cpeditor/cpeditor#1190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The font size for the font FixedSys is only available in 2 options 9, 12 px. I am unable to set variable size for the font.

### Expected Behavior

I want to be able to change the font size for the font FixedSys.

### Steps To Reproduce

1. Options > Preferences > Appearance > Font > Fixedsys 

### CP Editor Version

6.9.2

### OS

Windows 11

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
That font on your system doesn't have that size. It's not controlled by CP Editor.
