### ISSUE TITLE
Additional Themes

### ISSUE THREAD

**Issue by RazaHussainAziz** [cpeditor/cpeditor#1213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### Describe the feature you'd like

Please add the feature of custom themes or add VScode dark+ theme. I dark mode top menu remains light it is also an issue

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment]
See #1179.
