### ISSUE TITLE
Enhancing IDE Editor: Autocomplete Code and Suggestions Functionality

### ISSUE THREAD

**Issue by HalemoGPA** [cpeditor/cpeditor#1217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

The IDE editor lacks effective autocomplete and suggestions, slowing down coding and increasing the chance of errors.

### Describe the feature you'd like

Implement robust autocomplete code suggestions and context-aware recommendations to enhance coding speed, accuracy, and developer productivity.

### Describe alternatives you've considered

Manual code completion
Basic autocomplete
Third-party plugins
Language Server Protocol (LSP)
User-configurable suggestions

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
duplicate
