### ISSUE TITLE
Take Input from file

### ISSUE THREAD

**Issue by dipeshyadav331** [cpeditor/cpeditor#1231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sometimes like in meta hacker cup , we have to take input from file , in java to take input from the file , we need to write

```
if (System.getProperty("ONLINE_JUDGE") == null) {
                  PrintStream ps = new PrintStream(new File("output.txt"));
                  InputStream is = new FileInputStream("input.txt");
                  System.setIn(is);
                  System.setOut(ps);
}
```

I saved the input.txt and output.txt at the same directory where my file Main.java was stored but still I am getting file not found , How do I take input from the file , copy pasting the input doesn't works as the input files are huge anad upto 70mb.

### Expected Behavior

I want to take input and output from a file.

### Steps To Reproduce

try to take an input from a file

### CP Editor Version

6.10.3

### OS

macOS sonama 14.0

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
You don't need to copy-paste. CP Editor can load test cases from files.

**Comment by ouuan** [comment]
You can load individual input/answer by right-clicking the input/expected text areas, or load pairs of test cases in the "More" menu.

You may need to increase the output length limit in preferences if the answer is 70MB.

**Comment by dipeshyadav331** [comment]
it worked , I was unaware of this.
no editor even comes close to cp editor.
Thanks
