### ISSUE TITLE
Add a default snippet

### ISSUE THREAD

**Issue by straySn1per** [cpeditor/cpeditor#1244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

I open up a new project and neet to pres ctrl t to load my stuff that I add into to me every project.

### Describe the feature you'd like

In the snippets preferences, you should add a check box called "make default source". basicly if you select the checkbox, then the next time you make a new file, it should add in the default source automaticly. 

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
Are you looking for the "template" setting?

**Comment by straySn1per** [comment]
Yep i found it and tested , it doesn't seem to work so yeah

**Comment by straySn1per** [comment]
maybe make it just that you can just input the templet in and the starting curser pos will be the latest pos after apply

**Comment by ouuan** [comment]
I don't get your words. Please describe clearly what you have tried, what you observed, what you expect, and how they differ.
