### ISSUE TITLE
Disable ctrl+roller to change editor font size

### ISSUE THREAD

**Issue by y-kx-b** [cpeditor/cpeditor#1249]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

I used ctrl+Z/X/... shortcut a lot but sometimes too early to roll code before the ctrl key was released. Then I had to wait a few seconds and open settings to change the font size back.

### Describe the feature you'd like

It solves my problem if checkbox of whether enable ctrl+roller to change editor font size(enabled default) can be added, Thx a lot.

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by yashgosa** [comment]
Hey there, @ouuan! I'm eager to lend a hand, but I could use a bit of guidance from the maintainers since my development skills are still a work in progress.  So, if there's any way I can contribute, with a little help, count me in! Thanks! 🌟

**Comment by ouuan** [comment]
@yashgosa First follow https://cpeditor.org/docs/installation/build-from-source/ to build the project locally. You may need to install KSH and ECM via system package manager or build them from the git submodules.

Then you can search for relevant codes. Hint: it should be in files related to the code editor, and may contain strings like "wheel", "font", "size", etc.

**Comment by yashgosa** [comment]
Hey @ouuan I am facing some issues while building cpeditor from source. I am using `zsh`

``` zsh
cpeditor|fakevim-integration ⇒ mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
mkdir: cannot create directory ‘build’: File exists
CMake Error at CMakeLists.txt:22 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
gmake: Makefile: No such file or directory
gmake: *** No rule to make target 'Makefile'.  Stop.

build|fakevim-integration ⇒ uname -a
Linux yash 6.5.0-17-generic #17-Ubuntu SMP PREEMPT_DYNAMIC Thu Jan 11 14:01:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux


build|fakevim-integration ⇒ neofetch
            .-/+oossssoo+/-.               yash@yash 
        `:+ssssssssssssssssss+:`           --------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 23.10 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 82K2 IdeaPad Gaming 3 15ACH6 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 6.5.0-17-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 1 day, 16 hours, 10 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1703 (dpkg), 142 (brew), 15 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.9 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 45.2 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-viridian-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru-viridian [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: kitty 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: AMD Ryzen 5 5600H with Radeon Graphics (12) @ 4.280GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
      -+sssssssssssssssssyyyssss+-         GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q 
        `:+ssssssssssssssssss+:`           Memory: 4030MiB / 13816MiB 
            .-/+oossssoo+/-.
                                                                   
                                                                   

```

**Comment by ouuan** [comment]
There's something wrong with your Qt installation. I don't use Ubuntu, maybe search online and try your best first.

**Comment by ouuan** [comment]
We may still need to add back this feature behind an option. See #1480
