### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lololol00** [cpeditor/cpeditor#1293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

bugging

### Expected Behavior

not bugging

### Steps To Reproduce

<img width="319" alt="Screen Shot 2024-01-11 at 12 22 13" src="https://github.com/cpeditor/cpeditor/assets/157024014/6a258ecf-cd4b-4853-83cb-84833bc14aac">

### CP Editor Version

6.9.2

### OS

masOS

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

### Anything else?

no

**Comment by ouuan** [comment]
I have seen people providing insufficient information, but you are probably the first one who is providing literally no information. The image is indeed a huge surprise when it is loaded on my screen.
