### ISSUE TITLE
CP editor stress testing

### ISSUE THREAD

**Issue by anHiep** [cpeditor/cpeditor#1335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

I want to add stress testing to my CP editor

### Describe the feature you'd like

I fount this: https://github.com/cpeditor/cpeditor/pull/1031
In that video, he shows how to stress test the code. But my newest version doesn't have this. Anyway to add this ??

### Are you willing to contribute to this?

- [X] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment]
It's not available yet. I was not satisfied with that pull request. See my comments there. The functionality implemented there is no more than a simple shell script (you can find many online).
