### ISSUE TITLE
Put tabs in a scroll area

### ISSUE THREAD

**Issue by testitem** [cpeditor/cpeditor#134]
**Describe the bug**
Let's say I parse the whole Atcoder educational DP contest (https://atcoder.jp/contests/dp/tasks), and CPEditor opens all 26 tabs. The result is that problems A, B, Y, Z, or others get pushed off the border of the screen. I know normal contests won't exhibit this behavior, but ACM-like contests and Kotlin Heroes come close when the problem numbers go up to J and K.

**To Reproduce**
1. go to https://atcoder.jp/contests/dp/tasks
2. click green +
3. wait for chaos in cpeditor

**Expected behavior**
For the tabs to either stack on top, into rows, or become thinner and not take up a fixed amount of space.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ouuan** [comment]
Can't you solve problems one by one? Are you solving 26 problems together?

**Comment by ouuan** [comment]
I think there is no good solution for too many tabs. What do you mean by "become thinner", how wide are they on your system? I think they are thin enough.

**Comment by testitem** [comment]
What I mean is this:

<img width="318" alt="image" src="https://user-images.githubusercontent.com/19212916/73517640-fa827d80-4436-11ea-8622-637f2e67cedf.png">

If by "thin" you mean top-bottom, then yes it is thin enough. But the left-right width should be able to dynamically thin.

**Comment by ouuan** [comment]
I believe it's thin enough. A good solution to this is to add a scrollbar for the tabs, but it's not important because CP works on a single file, even though some contests have many problems, you are solving them one by one instead of working on them together.

**Comment by coder3101** [comment]
Tab cannot be made thinner by us, if however in future Qt does makes these adjustments in the framework to have thin-ing of tabs (like chrome), it should come automatically and will not even require any code change from our side. This behavior if comes in some future Qt version, it will be turned on by default.

Closing as this is something Qt does not provide as of now and we do not see any importance of solving 20 problems at once in tabs.

**Comment by ouuan** [comment]
> I believe it's thin enough. A good solution to this is to add a scrollbar for the tabs, but it's not important because CP works on a single file, even though some contests have many problems, you are solving them one by one instead of working on them together.

Have you seen this? We can use QStackedWidget and put the tabs in a scroll area. This is already marked low priority, we can work on this when other problems are solved.

**Comment by coder3101** [comment]
@ouuan I have not seen Scrollbars in Tabs and this idea sounds bad from good UI practices. We should instead wait for Qt itself to provide thinning of tabs.

**Comment by ouuan** [comment]
> @ouuan I have not seen Scrollbars in Tabs and this idea sounds bad from good UI practices. We should instead wait for Qt itself to provide thinning of tabs.

Have you used VS Code?

**Comment by coder3101** [comment]
@ouuan Have you given a contest with 26 problems to solve and solving them all at once. Moreover, it is not the VSCode team who have made the Scroll bar in Tab. It is the electron team (framework). All I am saying is that this issue is something more focussed for framework.

**Comment by coder3101** [comment]
@coder3101 If you still insist on implementing this on your own you can re-open this issue.

**Comment by ouuan** [comment]
OK. I just realized that there's a difficulty: in some styles, the scroll bar is very wide. The scroll bar of the breeze style is good for the tab bar, but others are not.

**Comment by ouuan** [comment]
I just found that even the scroll bar in the breeze style is wide. It only seems narrow, but in fact, it takes a big place.

**Comment by coder3101** [comment]
Scrolling already switches tabs. If you use mouse wheel or touchpad to scroll after you bring mouse pointer to tabs, it cycles throw the tabs. (Tested on Windows)

**Comment by ouuan** [comment]
> Scrolling already switches tabs. If you use mouse wheel or touchpad to scroll after you bring mouse pointer to tabs, it cycles throw the tabs. (Tested on Windows)

Scroll bar is better when you are at the most left tab and you want to see the tabs hidden at right. If there are many tabs, the scroll bar can also be faster than the mouse wheel.

I closed this because I found that it's hard to implement,  I still think scroll bar has some advantages.
