### ISSUE TITLE
Different colors for compilation warnings and errors

### ISSUE THREAD

**Issue by worker2011** [cpeditor/cpeditor#1363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
[
// warning and notes
C:/Users/ThinkPad/AppData/Local/Temp/cpeditor-Ymuolj/sol.cpp:72:36: error: invalid conversion from 'int*' to 'int' [-fpermissive]
   72 |                 int x = lower_bound(b + 1, b + m + 1, a[i]);
      |                         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
      |                                    |
      |                                    int*
C:/Users/ThinkPad/AppData/Local/Temp/cpeditor-Ymuolj/sol.cpp:73:20: error: too few arguments to function 'void upd(int, int)'
   73 |                 upd(x);
      |                 ~~~^~~
C:/Users/ThinkPad/AppData/Local/Temp/cpeditor-Ymuolj/sol.cpp:56:13: note: declared here
   56 | inline void upd(int x, int y) {
      |             ^~~
]
```
That is often when writing cpp code. But when I set the 'warnings' to be yellow, and 'errors' to be red, all of above messages are red, even include the warnings before the errors.

### Expected Behavior

Differ the warnings and make them yellow as I set, and keep the errors red. 

### Steps To Reproduce

Write a cpp code both will occur warnings and errors, then compile it.

### CP Editor Version

7.0.1

### OS

Windows 11

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
This is covered by #714. Closing as duplicate.

A workaround is to [use a language server](https://cpeditor.org/docs/setup/#setup-language-server), so that you get linting messages and won't need compilation messages.
