### ISSUE TITLE
Redo (Cntrl + Y) Feature is not present 

### ISSUE THREAD

**Issue by RomeoIndiaJulietUniform** [cpeditor/cpeditor#1379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

When I try to redo (Cntrl + Y) after I undo (Cntrl + Z)  nothing happens 

OS Version: Linux Ubuntu(22.4 LTS)

Steps to Reproduce: Try Cntrl + Y after you undo few lines of Code via the Cntrl + Z

### Describe the feature you'd like

I would like to getback my already madeup code after I undo(Cntrl + Z) via the (Cntrl + Y) keys

### Are you willing to contribute to this?

- [X] I'm ready to contribute to this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment]
It's <kbd>Ctrl+Shift+Z</kbd> on Linux.

https://doc.qt.io/qt-5/qkeysequence.html#standard-shortcuts

![image](https://github.com/cpeditor/cpeditor/assets/30581822/d4b26785-078a-43cc-8d5d-d1398d70335d)

I just noticed that this is not clear in the QTextEdit documentation, which is linked in the FAQ <https://cpeditor.org/docs/tips/#shortcuts-in-the-code-editor>. Maybe we can improve the documentation.

**Comment by RomeoIndiaJulietUniform** [comment]
Thanks a lot @ouuan for the fast response
