### ISSUE TITLE
Unable to access indivisual elements of a pair !!

### ISSUE THREAD

**Issue by manjit-hub** [cpeditor/cpeditor#1380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

"for(auto [child,edge_weight] : tree[node])" this is part of one of my cpp code. Here tree defines like: 
vector<vector<pair<int , int>>> tree; First element of tree is child, second is edge_weight. 
This code is working on other compilers, but not in CPEDITOR

### Describe the feature you'd like

I think this features belongs to latests GCC compilers. So I want you to update the GCC compiler itself or add this feature to your gcc compiler.

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment]
CP Editor uses the gcc installed on your system. We provide a version with bundled gcc for convenience, but you are not forced to use it, and the version is very recent (gcc 13 and LLVM 17). Please check your gcc installation and compilation flags (e.g. `-std=c++17`) in CP Editor settings.
