### ISSUE TITLE
to expand( > ) or collapse(^ ) a region 

### ISSUE THREAD

**Issue by manjit-hub** [cpeditor/cpeditor#1382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

It's  the feature which help to make the code editor look clean. In VS Code we can collapse and expand any function, so that it does not take entire screen space. This will definitely make CP faster.

### Describe the feature you'd like

add the feature called "[Collapse and expand regions of code]", so that we can minimize every function into one line. Whenever it will be needed to view we can view it by expanding.

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment]
This feature has been added in v7.0
