### ISSUE TITLE
想要一个删除评测点的功能

### ISSUE THREAD

**Issue by WitherStorm-WS** [cpeditor/cpeditor#1384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

我不小心搞了一个新的***评测点***，现在我不想要他啊。可我又没找到***删除评测点***的按钮，我该咋办？

### Describe the feature you'd like

我想要加一个***删除评测点***的功能，这样我（或者其他人😉）就可以删掉一些对我没用（或者不小心加的😅）的评测点了😄😄

### Describe alternatives you've considered

如果现有的UI界面放不下这个按钮，那其实也能理解。

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

### Anything else?

不是我不想做贡献，是我根本不会写啊，我只是个小学生，连OIer都不是啊
球球啦

**Comment by ouuan** [comment]
![image](https://github.com/user-attachments/assets/14ff55c1-e97c-411d-a079-f47565954e11)

**Comment by WitherStorm-WS** [comment]
说错了，是删除评测器

**Comment by WitherStorm-WS** [comment]
说实话，我其实是想再发一个的，我当时说错了，评测器说成评测点了。但我又不好意思再发，唉

**Comment by ouuan** [comment]
比起能够删除评测器，我觉得设计成同时只能有一个自定义评测器，不能添加多个只能替换可能会比较好。但问题应该不大，懒得改了。
