### ISSUE TITLE
想要一个删除评测器的功能

### ISSUE THREAD

**Issue by WitherStorm-WS** [cpeditor/cpeditor#1385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

我不小心搞了一个新的***评测器***，现在我不想要他啊。可我又没找到***删除评测器***的按钮，我该咋办？

### Describe the feature you'd like

我想要加一个***删除评测器***的功能，这样我（或者其他人😉）就可以删掉一些对我没用（或者不小心加的😅）的评测器了😄😄

### Describe alternatives you've considered

如果现有的UI界面放不下这个按钮，那其实也能理解。

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

### Anything else?

额，上次搞错了，不是评测点，是评测器啊。评！测！器！
![评！测！器！](https://github.com/user-attachments/assets/76799ca1-510f-4ec1-bb02-9c2caa84ccbc)
还是一样不是我不想做贡献，是我根本不会写啊，我只是个小学生，连OIer都不是啊

**Comment by ouuan** [comment]
我已经知道是评测器了，不要开新的..

**Comment by ouuan** [comment]
而且这里不要用中文，可以去 https://github.com/cpeditor/cpeditor-cn/discussions

**Comment by WitherStorm-WS** [comment]
知道了
