### ISSUE TITLE
Move from Telegram to Discord

### ISSUE THREAD

**Issue by testitem** [cpeditor/cpeditor#139]
**Is your feature request related to a problem? Please describe.**
I can't access Telegram for some reason. Furthermore, most discussion of issues go there.

**Describe the solution you'd like**
From previous experience Discord is very easy to use, so I think we should move to Discord.

**Describe alternatives you've considered**
~~tell me how to access telegram~~
Keep related discussion on GitHub.

**Additional context**

**Comment by coder3101** [comment]
Telegram Web is also not accessible in India and so the short link to join group does not works. Discord will be a good choice.

**Comment by coder3101** [comment]
Discord is a nice place for bots too. Do you have any idea about some bots that could be useful.

**Comment by ouuan** [comment]
But I can't access Discord without VPN. I suggest using gitter.

**Comment by coder3101** [comment]
> But I can't access Discord without VPN. I suggest using gitter.

I thought both of you were from china. Gitter is more development centrict, common users will mostly avoid creating a new gitter and joining. Also, its application for android and ios is very poor.

**Comment by ouuan** [comment]
@testitem How do you know how many discussions there are on Telegram if you can't access it? In fact, almost all discussions are on Github, especially if there are related issues.

**Comment by ouuan** [comment]
A QQ group may be an alternative solution.

**Comment by coder3101** [comment]
> A QQ group may be an alternative solution.

That isn't very popular outside china. I mean here most people even do not know about it. Seems like there is really few platforms that is available everywhere. I suggest you create and administer the QQ Group and add me too, for the rest of the world, we will have discord and telegram because its join url does not works in India. On our README we will put all 3 and people who find anyone good will join on that platform.

**Comment by ouuan** [comment]
It's bad to have discussions everywhere, let the people who don't have access discuss on Github only is not too bad, since there are only a few discussions in the Telegram group now.

**Comment by coder3101** [comment]
> It's bad to have discussions everywhere. Let the people who don't have access discuss on Github only is not too bad, since there are only a few discussions in the Telegram group now.

Yes and it will become hard to track things too. Fragmentation of users on different platform isn't good idea. The only issue that troubles me now is that telegram group short URL does not work in India and many people who wanted to join could not because connection times out on that URL. Any idea for this?

**Comment by ouuan** [comment]
So only the join URL is blocked in India, but Telegram itself isn't?

**Comment by coder3101** [comment]
> So only the join URL is blocked in India, but Telegram itself isn't?

Yes

**Comment by coder3101** [comment]
To be precise Telegram Web is banned but not Telegram App. Since URL opens Telegram Web and then moves URL to open in App, the join does not work

**Comment by testitem** [comment]
@ouuan I know because you are posting screenshots of it. How are you using Telegram in China though?

I can't use telegram because both web version and app version doesn't work in China.

How about a FreeIRC? That's most definitely not blocked anywhere...

**Comment by testitem** [comment]
Here, use this chat: [link](http://irc.lc/freenode/cp-editor)
Use your normal github username.

**Comment by ouuan** [comment]
> @ouuan I know because you are posting screenshots of it. How are you using Telegram in China though?
> 
> I can't use telegram because both web version and app version doesn't work in China.
> 
> How about a FreeIRC? That's most definitely not blocked anywhere...

That was private messages, and **I have posted it to make it public**.

**Comment by coder3101** [comment]
Gitter is available everywhere but most people don't use it.

**Comment by coder3101** [comment]
Discord seems most permissible to me. IRC does not have images (i think), but then you say discord is not everywhere also.

**Comment by coder3101** [comment]
@ouuan Said

> Maybe Discord is good because I've created a QQ group, and Chinese can ask questions there.

from Telegram Group

**Comment by ouuan** [comment]
The [Discussions](https://github.com/zeit/next.js/discussions) is a good choice, the problem is I don't know when it will be open for all :thinking:

**Comment by ouuan** [comment]
It seems that [Slack](https://slack.com) is good.

- It is accessible for me without VPN (though very slow).
- We can subscribe to GitHub updates, and it seems that it's more powerful than the Telegram bot.
- We can divide the discussions into different channels, like develop, help, announcements and github-notifications.

I've already created a workspace and set up some channels. Click [here](https://join.slack.com/t/cpeditor/shared_invite/zt-dke1v9xd-zr~QeXJhCzbM9FFOjx6sMA) to join.

**Comment by shakeabi** [comment]
What happened to slack channel?

**Comment by ouuan** [comment]
> What happened to slack channel?

It seems that we are used to discussing on Telegram. I think Slack is better, but we need a change.

**Comment by shakeabi** [comment]
We can gradually move the conversations there. Also, the given invite link in the repo doesn't work.

**Comment by ouuan** [comment]
> Also, the given slack invite link in the repo doesn't work.

I copied that link from an email from Slack, and I can go to the workspace via that link :thinking:

So what's displayed after you click that link? Can you visit <https://cpeditor.slack.com>?

**Comment by shakeabi** [comment]
> > Also, the given slack invite link in the repo doesn't work.
> 
> I copied that link from an email from Slack, and I can go to the workspace via that link 
> 
> So what happened after you clicked that link? Can you visit https://cpeditor.slack.com?

Yes, I can visit the workspace from that link. However, the links on the website or in the README.md doesn't work. Try in incognito mode. Also, we can start asking people to slowly move to Slack from telegram.

**Comment by ouuan** [comment]
> Yes, I can visit the workspace from that link. However, the links on the website or in the README.md doesn't work. Try in incognito mode.

Thanks. I've confirmed and it will be fixed in #363.
