### ISSUE TITLE
Submit to CF without cf-tool

### ISSUE THREAD

**Issue by testitem** [cpeditor/cpeditor#142]
**Is your feature request related to a problem? Please describe.**
As cf-tool is a third party program (that **GASP** stores your "encrypted" password ON DISK) it has inherent vulnerabilities.

**Describe the solution you'd like**
Use HTTP POST requests to submit from cp-editor without using cf-tool.

**Describe alternatives you've considered**
Merge the related source code from cf-tool into cp-editor.

**Additional context**
This allows us to incorporate submitting to different OJ's later.

**Comment by coder3101** [comment]
> As cf-tool is a third party program (that **GASP** stores your "encrypted" password ON DISK) it has inherent vulnerabilities.

Well if encrypted passwords is the problem? Even if we use HTTPS POST request the password has to be stored somewhere or cookies. AFAIK CF does not provides O-Auth2 for authentication.

> Merge the related source code from cf-tool into cp-editor

cf-tools is in GO-LANG, This could be more difficult that it may seem to.

>This allows us to incorporate submitting to different OJ's later.

This seems a nice Idea, we could create a new directory in source tree named `api` where user could put PR for new OJ submissions. This however could be a very long term goal. There are certainly more important stuff to complete now.

**Comment by ouuan** [comment]
I think #212 is better :thinking: Why should we do duplicate work as other tools?

**Comment by coder3101** [comment]
@ouuan Yes, moreover this OJ tool can be used as library too.

**Comment by ouuan** [comment]
> moreover this OJ tool can be used as library too.

I think customizing submit commands gives more flexibility and less work for us.

**Comment by coder3101** [comment]
Does OJ tool also require to add template or configure it? I get it customised submit command will be better.

**Comment by ouuan** [comment]
> Does OJ tool also require to add template or configure it?

Why do you ask me?

1. You should ask the documentation of OJ tool.
2. How does it matter? We are not sticking to OJ tool. Users can use any tool, and we can contribute to any tool if we find OJ tool or other tools are not good enough. I think support submitting in CP Editor itself is never the better choice.

So I'll close this in favor of #212.
