### ISSUE TITLE
Add Google Crashpad/Breakpad for reporting runtime errors

### ISSUE THREAD

**Issue by coder3101** [cpeditor/cpeditor#148]
**Is your feature request related to a problem? Please describe.**
When application crashes on any Machine there is no way to for us to know this. There should be a way so that we (developers) and any one else could see the report for crashes. These reports will gather and send only important data that cannot be used back to trace the identity of the user. These reports however should contain hardware information like OS Version and Machine configuration. 

**Describe the solution you'd like**
When application crashes a report will be prepared and the minidump will be sent to us. The user must know that such reporting is being done and user should have a way to opt out of such data collection. The data should not contain any information that could be used to trace the identity. In order to implement this we already have a framework of Google called [Breakpad](https://docs.sentry.io/platforms/native/breakpad/)

**Describe alternatives you've considered**
Event logs will only tell me where things went wrong but not tell us what went wrong. See #146 for more information about Event logger

**Additional context**
N/A

**Comment by testitem** [comment]
This is involuntary intrusion on the users and their privacy as it tracks their hardware information. The users must be prompted before a report is sent. Furthermore, Google-related systems do not work in China.

**Comment by coder3101** [comment]
> This is involuntary intrusion on the users and their privacy as it tracks their hardware information. The users must be prompted before a report is sent. Furthermore, Google-related systems do not work in China.

As already mentioned even event logger cannot provide us runtime errors. (Stack trace) This is a framework that collects the minidump and sends to specific website or endpoint. I will make sure that the site it sends the data (minidump) will be accessible from China as well. 

By hardware information I mean, Memory (RAM) in system, how much free memory when application crashed?, which OS, what OS version, When it occurred, which code was responsible for exception. 

Your will be prompted with a dialog box that application crashed report needs to be sent and what will be sent. If they deny it won't be sent otherwise it will be uploaded to our endpoint. And you can see it publicly. Your identity won't be gathered, Moreover there will always be a way to opt out of it. It will only be enabled by default in beta and optional for stable release.

**Comment by coder3101** [comment]
Also no need to worry. Whatever code for data collection on crash we write will be available in GitHub so you can see what is sent as stacktrace and if you see a privacy concern, it will be removed.

**Comment by testitem** [comment]
Okay. I'm sorry for my abrupt concerns.

**Comment by coder3101** [comment]
> Okay. I'm sorry for my abrupt concerns.

Its okay, big organisation collect data and sell it(maybe). And in this era everyone should be concerned about their online trace and data. We aren't organisation we are a community, collected data will be also publicly seen, and it will not be a concern because there will no no name, email, other identifiers with data. Only a long stacktrace.
