### ISSUE TITLE
Make the header comments opt-in

### ISSUE THREAD

**Issue by testitem** [cpeditor/cpeditor#153]
**Is your feature request related to a problem? Please describe.**
The header comments  (time limits, problem name) don't feel that necessary to me, and I like my code as short as possible.

**Describe the solution you'd like**
title

**Describe alternatives you've considered**
Deleting them myself

**Additional context**
N/A

I can't do this myself since I'm really bad at UI.

**Comment by coder3101** [comment]
You can always remove them. Also, those comments are a way for us to advertise about the EDITOR. Someone if sees a solution of someone who use our editor to submit will get to know about this application. So, what is wrong in that?

**Comment by ouuan** [comment]
close in favor of #203.
