### ISSUE TITLE
New preference window with scrollable tabs on the left

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#166]
**Is your feature request related to a problem? Please describe.**

The current preference window is not able to contain too many options.

**Describe the solution you'd like**

Use a preference window with scrollable tabs on the left. i.e. Make tabs be QPushButtons in a QScrollArea on the left.

And users should be able to search for options.

**Describe alternatives you've considered**

Make the default size of the preference window bigger, so more tabs can be placed in it without the left and right buttons.

**Additional context**

N/A

**Comment by coder3101** [comment]
As of now, I have increased the size of the preference window when it is opened and so it can contain most of the preference tabs directly. As for searching and new preference window UI, It can be under-prioritized now.

**Comment by coder3101** [comment]
637d6b8

**Comment by ouuan** [comment]
I'll write a completely new preference window.

**Comment by ouuan** [comment]
The first-step plan:

![first-step plan](https://user-images.githubusercontent.com/30581822/77845344-c29e7900-71e0-11ea-8062-07d60a00b1c1.png)

The near-future plan:

![near-future plan](https://user-images.githubusercontent.com/30581822/77845345-c500d300-71e0-11ea-99c0-a449c48d88ff.png)

Feel free to share your opinions on these plans.

**Comment by ouuan** [comment]
Other settings pages except for the snippets (which is complicated) and the Limits (which is a new feature) are easy to implement, especially the Actions section (which has only checkboxes). Contributions are welcomed!
