### ISSUE TITLE
Set font for the whole application

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#169]
**Is your feature request related to a problem? Please describe.**

The font of labels is not the system font on Windows.

![image](https://user-images.githubusercontent.com/30581822/85595009-0a675c00-b67b-11ea-9b4c-9e0365948f91.png)

**Describe the solution you'd like**

Able to set the font for the whole application.

**Describe alternatives you've considered**

N/A

**Additional context**

It's the system font on Manjaro KDE, and sans serif on Windows 10, don't know about other OSs.

**Comment by ouuan** [comment]
@coder3101 Why are you adding "stale" manually? It should be added by the stale-bot, and shouldn't be added for issues with a priority.

**Comment by ouuan** [comment]
We can simply use `qApp->setFont` to set the application font, but I met problem when trying to get the font family of the system default font, `QFont::family`, `QFont::key`, `QFont::toString` are all empty for `QFontDatabase::systemFont(QFontDatabase::GeneralFont)`.

**Comment by coder3101** [comment]
Can you share with me apps that allow setting fonts for whole application? This is system specific and should not be app basis in my opinion. 

Doing so only breaks uniformity in Linux, macOS when you set OS wide Fonts from Gnome Tweaks or Settings in Mac!

Customisation is good but too much is bad.

**Comment by ouuan** [comment]
It's OK now. It's not the family name is empty, it's the `if (newFont != font)` never enters.

**Comment by ouuan** [comment]
> Can you share with me apps that allow setting fonts for whole application? This is system specific and should not be app basis in my opinion.
> 
> Doing so only breaks uniformity in Linux, macOS when you set OS wide Fonts from Gnome Tweaks or Settings in Mac!
> 
> Customisation is good but too much is bad.

"**Is your feature request related to a problem? Please describe.**

The font of labels is not the system font on Windows."

**Comment by ouuan** [comment]
We can provide an option to use the system font.

**Comment by ouuan** [comment]
Or we can force the application to use the system font.

**Comment by ouuan** [comment]
Let me test on Windows.

**Comment by coder3101** [comment]
> "**Is your feature request related to a problem? Please describe.**
> 
> The font of labels is not the system font on Windows."

Does this happen with only our application or whole Qt Apps?

**Comment by ouuan** [comment]
I just checked, the default font is `QFontDatabase::systemFont(QFontDatabase::GeneralFont)`, but I haven't seen any application on my windows using that font.

**Comment by coder3101** [comment]
Maybe because of your locale settings in Windows. On my computer CP Editor uses system default font and it is same in all Apps!

**Comment by ouuan** [comment]
Whatever causes this problem, we can fix it by providing two settings:

1. Whether to use a custom font for the whole application.
2. The custom font.

**Comment by coder3101** [comment]
I think it is better to confirm with other Windows 10 users on Group, if default font is different on their PC as well.

It's not a good idea to add new settings if it only happens on your PC!

Or we might find why it happens on your PC;

- Does Chinese Language font of CP Editor also uses different font than windows.

- Do you use Chinese Language for Windows, so Qt can't find a default font for English language?

**Comment by ouuan** [comment]
Both the Chinese font and the English font are wrong. The wrong font is a non-default Chinese font (SimSun). It was originally requested by @Ravenclaw-OIer.

**Comment by ouuan** [comment]
I checked `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes` and none of the fonts there is SimSun.

**Comment by coder3101** [comment]
These resources might help you

- https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-19309

- https://forum.qt.io/topic/86872/where-does-qt-get-the-default-application-font/3

**Comment by coder3101** [comment]
From At docs:
> Changes the default application font to font. If className is passed, the change applies only to classes that inherit className (as reported by QObject::inherits()).

> On application start-up, the default font depends on the window system. It can vary depending on both the window system version and the locale. This function lets you override the default font; but overriding may be a bad idea because, for example, some locales need extra large fonts to support their special characters.

> Warning: Do not use this function in conjunction with Qt Style Sheets. The font of an application can be customized using the "font" style sheet property. To set a bold font for all QPushButtons, set the application styleSheet() as "QPushButton { font: bold }"
