### ISSUE TITLE
Incorrect highlighting

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#174]
**Describe the bug**

1. Highlighting is incorrect when inline/block comments and string literals are mixed together.
2. Raw string literals and string literals with prefixes are not supported.

**To Reproduce**

```cpp
// /*
/*
// */
"//\"" // ""
R"(//"/*")"
R"(//"/*")"
uR"test(//"R"(/*)"*/")test"
u8"test"
L"test"
U"test"
```

**Screenshots**

CP Editor:

![image](https://user-images.githubusercontent.com/30581822/75088734-420aae00-558c-11ea-8be7-8217c220350a.png)

VS Code: (mistake due to string literals with different character kinds cannot be concatenated)

![image](https://user-images.githubusercontent.com/30581822/75089243-d592ad80-5591-11ea-8ed6-96af34ae0df1.png)

**Environment**

 - OS: Manjaro
 - Version: 5.9.8

**Additional context**

We don't need to fix it before 6.0, because CPers seldom write such codes. There are usually not many comments, and string literals are not much more than "Yes"/"No"/"Impossible", etc.

This is a QCodeEditor issue, which is similar to ouuan/QCodeEditor#2, open here for easier bug tracking.

**Comment by ouuan** [comment]
This bug is even more critical on Python.

**Comment by coder3101** [comment]
Was it always like this or some updates made it?

**Comment by ouuan** [comment]
> Was it always like this or some updates made it?

The highlighting is always awful because of QCodeEditor.

**Comment by coder3101** [comment]
> > Was it always like this or some updates made it?
> 
> The highlighting is always awful because of QCodeEditor.

I can think why, usually highlighting is done by Lexer that tokenises and then apply formatting. Does there not exist a Lexer already as Third party dependency?

**Comment by ouuan** [comment]
It can be better than current with simple regex. But of course, simple regex can't be as well as Intellisense.

**Comment by ouuan** [comment]
However, I'll work on the new preferences window in the next days or even weeks.

**Comment by alexei-R** [comment]
hey @ouuan, I have recently started using CP Editor and I find it to be a great and very useful tool.

I observed the following parentheses highlighting inaccuracy (in version 6.1.6):
![grafik](https://user-images.githubusercontent.com/63749693/79383964-5fde0900-7f66-11ea-99d9-e44eaa750de8.png)

The closing parenthesis should be matched with the syntactically opening one, not with the closest one which is a character. It looks like a thing slightly different, but related to the issue in this thread, and too small to create a separate issue. So posting it here.

**Comment by coder3101** [comment]
> This bug is even more critical on Python.

Yup. I have seen that CF comment miserable python highlighter.

```python
'''
Hello Quarantine World!
'''

x = input()  # This line is highlighted green like a comment, while not in DOC comment.
```

Proof:
![Annotation 2020-04-17 154449](https://user-images.githubusercontent.com/22212259/79558862-76997280-80c2-11ea-9749-bd7f489af595.jpg)

**Comment by coder3101** [comment]
Adding to this list `'a'` in `char ch='a'` is also not being highlighted. It should be easy to add a regex to match them and it is critical highlighting issue that needs to be fixed.

**This was reported by someone in Codeforces**

**Comment by testitem** [comment]
bump

**Comment by testitem** [comment]
"because CPers seldom write such codes"

no

here's something i did recently

```
mp[951582721] = R"(*6-bA$5}_2#fQ_$&G%^K*/* Y$@L6;,^rby*BSiR%V~U5(fNyb$P7%($Yir))t|]_,cZR%&X}@& estg,I1mS'&\c),<Am\,p<6s&LLrT!/)aY&osQa (<tf$tYip#[/.t&@I K!u~@t#aQD]+(TB0*;x43(@a4f)=:Tr(^pTy'uJq/*[T~3+!9;D+BIX%!NbqS*EO!S#=3RA!BGs%)a1Ps!~Z>C'Coy2!CqIe!<2fL+1.nY,0w1:$aWMW#+ZK$+TLwP$LdN+#i]\S#iLG+(@](b,7d#2)";
```

for "打表"

**Comment by testitem** [comment]
also actually parse raw string literals

**Comment by coder3101** [comment]
See more incorrect highlighting in #641

**Comment by GoodCoder666** [comment]
Here's the most common incorrect highlight:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/59763425/213687753-e813f3f8-2226-4d23-a449-8aaefa82ac29.png">
This is really annoying as we **nearly always** write such code.
