### ISSUE TITLE
Let users choose where to save test files

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#176]
**Is your feature request related to a problem? Please describe.**

There may be too many files if save test cases is enabled.

**Describe the solution you'd like**

Add an option to hide test case files. (Add a dot at the front on Linux and Mac, [SetFileAttributes](https://stackoverflow.com/questions/33174622/is-it-possible-to-create-a-hidden-txt-file-in-c) on Windows.)

**Describe alternatives you've considered**

Save test cases in a workspace config file.

**Additional context**

N/A

**Comment by coder3101** [comment]
Testing telegram bot

**Comment by coder3101** [comment]
Or how about creating a hidden directory and putting all tests inside it like this :

```
.tests/1/in.txt
.tests/1/out.txt
.tests/1/exp.txt

.tests/2/in.txt
....
```

**Comment by ouuan** [comment]
We can let users set the format, like:

1. `.<filename>-<index>.in`, `.<filename>-<index>.out`, `.<filename>-<index>.ans`
2. `.tests/<filename>/<index>/input.txt`, `.tests/<filename>/<index>/out.txt`, `.tests/<filename>/<index>/expected.txt`.

**Comment by coder3101** [comment]
@ouuan That will be nice too
