### ISSUE TITLE
Invalid payload when parsing sample testcases using Competitive Companion

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#186]
**Describe the bug**

@emli reported that he always receives invalid payload when parsing sample testcases using Competitive Companion.

**To Reproduce**

Not everyone can reproduce it. @emli can reproduce it by parsing sample testcases using Competitive Companion.

**Screenshots**

![image](https://user-images.githubusercontent.com/30581822/75600560-97464280-5aeb-11ea-9949-3b3b5c4c8193.png)

**Environment**

 - OS: Ubuntu 19.10 
 - CP Editor Version: 6.0.2

**Additional context**

The request in the log file provided by @emli:

```
OPTIONS / HTTP/1.1
Host: localhost:10045
Connection: keep-alive
Accept: */*
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Origin: chrome-extension://cjnmckjndlpiamhfimnnjmnckgghkjbl
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```

**Comment by coder3101** [comment]
This has been fixed as per his report on telegram. Closing it now

**Comment by ouuan** [comment]
Since he said it's fixed and there haven't been any replies, we can close this until others report the same issue.
