### ISSUE TITLE
Lines are overlapped in some rare situations

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#187]
**Describe the bug**

In some rare situations, lines are overlapped in the editor, and use arrow keys to go over them make the application crash.

**To Reproduce**

1. Open the file [template.cpp](https://raw.githubusercontent.com/ouuan/CF-template/d853218/template.cpp). (I don't know what makes this code special, but I can always reproduce with it.)
2. There will be several line-overlaps, for example, around line 252.
3. Press <kbd>↓</kbd> on line 252, it will crash.

**Screenshots**

![image](https://user-images.githubusercontent.com/30581822/75643017-8840cb00-5c78-11ea-946c-e15b2f9eee3e.png)

**Environment**

 - OS: Manjaro KDE
 - CP Editor Version: dc49261

**Additional context**

Only open this file can reproduce the bug, the bug doesn't happen when restoring from hot-exit.

**Comment by coder3101** [comment]
Unable to reproduce in either windows or Linux on my machine.
