### ISSUE TITLE
Add warning when switching between snippets

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#189]
**Is your feature request related to a problem? Please describe.**

You won't get any warnings if you close the preference window without saving the settings. What's worse, since the "OK" and "Apply" buttons don't save the snippets, it's very likely that the user forgets to save the snippets and lose them. 

**Describe the solution you'd like**

Add warning when closing the preference window with settings unsaved, and other operations like changing the snippet name/language, which may lose the snippets.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by coder3101** [comment]
The snippet unsaved changes and save should be handled too, re-opened this issue!

**Comment by ouuan** [comment]
Now the only thing left is the warning when switching the snippet language and the snippet name.
