### ISSUE TITLE
Swapping places of "load" and "delete" of testcases

### ISSUE THREAD

**Issue by Ravenclaw-OIer** [cpeditor/cpeditor#190]
**Is your feature request related to a problem? Please describe.**

The load function and the delete function are the inverse of each other, it may be better to put them together in the drop-down menu and put the run button outside.

Target version: v6.1.1
**Describe the solution you'd like**

```
 =======================
|     Run  | | More v  |
                         | Load   |
                         | Delete|
```
**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by coder3101** [comment]
@Ravenclaw-OIer Great idea

**Comment by coder3101** [comment]
I think it will be better to have both the load button at one place. "Input", "Expected" inside "Load" (Change more to load), "Run" and "Delete" should replace the two Load button, since these are more likely to perform operation than others. Overall this should be new UI.

```
=====================|===================|============================|
Input #1 | Run case || Output #1 |  AC  || Expected #1 | Del || More ||
---------------------|-------------------|----------------------------|

```

**Comment by ouuan** [comment]
It sounds more convenient. But there's a small problem: the "Run" action is not for the input only, and the "Del" action is not for expected only, thus makes it a little bit strange.

**Comment by ouuan** [comment]
What about putting them aside instead of above the textedits? I'll have a try.

**Comment by ouuan** [comment]
What about `input load run output AC expected load del`?

**Comment by coder3101** [comment]
One more things that is missing is the ability to expand the view and open in a window. Last time I was solving something and the testcase was big in width and I thought it would have been better if ` Right->click and Expand ` was an option. This should open the content of the box into a window with text input like diff viewer. This should be added to all 3 boxes.

**Comment by ouuan** [comment]
What can you get from reading a big input manually?

**Comment by coder3101** [comment]
> What can you get from reading a big input manually?

It wasn't that big, say it had a string of length 20-30 and then a scrollbar came, it wasn't that big of an issue but if someone loads a testcase from file (possibly big) and then want to see it as well, it would be great to have that option here.

**Comment by ouuan** [comment]
I was exactly asking what you could get from manually reading a big input loading from file.

**Comment by coder3101** [comment]
> I was exactly asking what you could get from manually reading a big input loading from file.

Not exactly only for reading but also changing. Suppose I have a big input whose output I know, I copy paste it into the box and then got answer correct. Then I think of a corner case that I can make by changing a small thing in this big testcase, currently it is very inconvenient to do so on a small input box. I know it isn't that important and maybe you do it some other way, but still giving ability to view in a big window and edit testcase would be good option? Moreover that would be an addition to feature sets.

**Comment by ouuan** [comment]
What about this:

![image](https://user-images.githubusercontent.com/30581822/76180133-0c0a3280-61f8-11ea-87d7-b25db25bc98a.png)

The "Edit in Bigger Window" is actually a `QInputDialog::getMultiLineText`.
