### ISSUE TITLE
Doesn't work with mac os 10.14.5

### ISSUE THREAD

**Issue by GoToCoding** [cpeditor/cpeditor#193]
![image](https://user-images.githubusercontent.com/16542586/76453544-1b4dd380-63e4-11ea-8a25-f2d6729dd63d.png)

using version:  6.0.6

**Comment by ouuan** [comment]
I'll look into this. I've already come up with some solutions, including using Azure Pipelines, cross-compiling, or have volunteers compile on macOS 10.14 manually. I'll work on finding the best solution. It's better of you to keep in touch, I may need your test on your machine when a sample release is available.

**Comment by GoToCoding** [comment]
I've built it from source and looks like it's working fine, but prints this:
```
> ./cpeditor
qt.qpa.fonts: Populating font family aliases took 747 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
```

![image](https://user-images.githubusercontent.com/16542586/76525565-1e48d280-647d-11ea-9010-62ee29f38a83.png)

**Comment by ouuan** [comment]
@GoToCoding This is normal. On Linux you can silence them and run in the background by `nohup cpeditor </dev/null >/dev/null 2>/dev/null &`, I think it should be similar on macOS? Or you can open it by other methods instead of open in the terminal.

**Comment by coder3101** [comment]
Seems like it's only the issue with new version of Xcode that we use to build editor. If we use old Xcode like 10, the compiled bundle will run on Mojave as well even if compiled on Catalina. 

`xcode-select -p <path>`

Can choose between multiple Xcode version. I now only have to see if GitHub Actions Mac image has multiple Xcode version?

**Comment by ouuan** [comment]
When will this be ready? I haven't used macOS before, so it's hard for me to work on this.

**Comment by coder3101** [comment]
I do not have a mac machine with that OS, how about using Azure pipeline?

**Comment by ouuan** [comment]
> I do not have a mac machine with that OS, how about using Azure pipeline?

Didn't you say "it's easy to cross-compile"?

**Comment by ouuan** [comment]
GitHub Actions will be better if cross-compile is easy.

**Comment by coder3101** [comment]
@ouuan Turns out is time taking, it takes time to install Xcode old version. So much more, it took more than 15 min to download that's not acceptable

**Comment by ouuan** [comment]
> @ouuan Turns out is time taking, it takes time to install Xcode old version. So much more, it took more than 15 min to download that's not acceptable

Have you tried that on GitHub Actions? However, 15min is acceptable since we don't release very often.

How big is the download? We can cache it if it's not too big.

**Comment by coder3101** [comment]
There are two solutions;

1. Provide separate macOS build for 10.14 from Azure.

2. Mark the issue as awaited and wait for GitHub action to add 10.14

3. Close and ignore since 10.14 is being used by only 25% of mac users also it doesn't support dark theme.

**Comment by ouuan** [comment]
> 3\. also it doesn't support dark theme.

If I build the package on 10.14 and run it on 10.15, will dark theme work?

**Comment by coder3101** [comment]
@ouuan Not sure since dark theme was added in 10.15, the 10.14 SDK will probably not have it. But I am not sure about it

**Comment by GoToCoding** [comment]
dark theme works find on 10.14.5
![image](https://user-images.githubusercontent.com/16542586/77671697-056e1000-6f99-11ea-902d-8c485b9ec0d2.png)
