### ISSUE TITLE
CF Tool 1.0.0 is not supported

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#194]
**Describe the bug**

You can't submit to CF inside CP Editor with CF Tool 1.0.0.

**To Reproduce**

Try to submit with CF Tool 1.0.0.

**Screenshots**

![image](https://user-images.githubusercontent.com/30581822/76499903-8cd86100-647a-11ea-8163-8eef3bd57b89.png)

**Environment**

 - OS: Manjaro KDE
 - CP Editor Version: 9a424f7fefe413ac23ab8859a360a9b5cc30578b

**Additional context**

Now CF Tool uses `-f` for the file, and supports problem URL, so we don't need to parse the problem URL in CP Editor, and should use `-f` before the file name.

**Comment by coder3101** [comment]
@ouuan Poor backward compatibility. Does old CF tools support -f ? I guess no, 

So we need to check version as well so that those who use old version will have no trouble; but we should warn those to update the CF tool

**Comment by ouuan** [comment]
> Poor backward compatibility. Does old CF tools support -f ? I guess no,

That's why it's 1.0.0 instead of 0.10.0. A new major version doesn't need backward compatibility (though it's good to keep backward compatibility).
