### ISSUE TITLE
If you don't install the clang-format,the code will be cleared when you use the code format.

### ISSUE THREAD

**Issue by WYWFlash** [cpeditor/cpeditor#195]

**Comment by ouuan** [comment]
Please follow the template.

**Comment by ouuan** [comment]
I can't reproduce it on my machine, so your steps to reproduce and your environment are important.

**Comment by ouuan** [comment]
The template:

```Markdown
**Describe the bug**

<!-- A clear and concise description of what the bug is. -->

**To Reproduce**

<!-- Steps to reproduce the behavior. -->

**Screenshots**

<!-- If applicable, add screenshots to help explain your problem. -->

**Environment**

<!-- Your environment is usually important for finding the cause of the bug. -->
<!-- You can get the CP Editor version by clicking `Help`->`Build Info` in the GUI. -->

 - OS: [e.g. Windows 10 / Ubuntu 18.04]
 - CP Editor Version: [e.g. 6.0.2]

**Additional context**

<!-- Add any other context about the problem here. -->

```

**Comment by coder3101** [comment]
@WYWFlash Yes this does happen. On windows, try removing the clang-format from path and you can see that it deletes the code, you can however undo it.

**Comment by ouuan** [comment]
I've found the reason, `QProcess::exitCode()` is invalid when the process is not finished, I checked only the `QProcess::exitCode()` but not whether it has finished, thus made an undefined behavior, and result in this bug.

**Comment by ouuan** [comment]
@allcontributors add @WYWFlash as a contributor for bug report.
