### ISSUE TITLE
Key Binding for delete line

### ISSUE THREAD

**Issue by Razdeep** [cpeditor/cpeditor#196]
**Is your feature request related to a problem? Please describe.**
The `Shift + Delete` binding for deleting line is missing.

**Comment by ouuan** [comment]
It's actually available with Ctrl+Shift+K (you can see that in the Edit section of the main menu, I got that keybinding from Sublime, which supports both these two keybindings but has only Ctrl+Shift+K in its menu). But one more shortcut is also good.
