### ISSUE TITLE
Font on Mac os looks stretched [see picture below]

### ISSUE THREAD

**Issue by GoToCoding** [cpeditor/cpeditor#197]
May be it's hard to see it on screenshot, but look to github site font and back to editor font - it hurts my eyes.

---
![image](https://user-images.githubusercontent.com/16542586/76670001-4fb9bf00-659f-11ea-8ab4-6006fff0f56c.png)

---

I've tried many different fonts, and tried to change font size - problem is still exist.
Earlier, such a problem was in the vscode terminal.

**Comment by ouuan** [comment]
How did you solve that problem in the VS Code terminal?

**Comment by GoToCoding** [comment]
@ouuan I don't know - just one day the terminal started working with normal fonts.

**Comment by ouuan** [comment]
Have you tried `write -g CGFontRenderingFontSmoothingDisabled -bool NO`? (found [here](https://bugreports.qt.io/browse/QTBUG-71075)).

However, I think I can't do anything more than Google for you on this, it's some bug/feature with Mac and/or Qt.

**Comment by GoToCoding** [comment]
I've tried, it doesn't help (i've tried to rebuild from source after disabling smoothing).

**Comment by ouuan** [comment]
Close this in favor of #225.

**Comment by ouuan** [comment]
@allcontributors add @GoToCoding as a contributor for bug report.
