### ISSUE TITLE
Set output limit, and make message length limit, HTML diff viewer length limit and open file length limit customizable

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#202]
**Is your feature request related to a problem? Please describe.**

Now the application (maybe the whole system) will hang up when the output is too big.

And users can't set a suitable limit for messages, HTML diff viewer length limit  and code length limit on their device.

**Describe the solution you'd like**

Set customizable length limits for output, message, HTML diff viewer and codes.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by coder3101** [comment]
User will be given choice to set the value of the length of the output/message texts. There should be a upper limit also that we won't allow user to set beyond. The upper limit should be such that we fear might result in ui freeze.

Consider the case of reading big output from child process of user. The length 10^7 will result in some kind of hang..

Try this code : 
```cpp
int main()
{
	int t=1000000;
	while(t--)
	{
		cout << 1000000 - t << " " << "a\n";
	}
}
```

It freezes in my machine, depending upon the hardware of machine, it may hang. For me it does hangs for 0.5 sec
