### ISSUE TITLE
add multi testcases in a time

### ISSUE THREAD

**Issue by StudyingFather** [cpeditor/cpeditor#204]
**Is your feature request related to a problem? Please describe.**

Now the input file and output file can only be added one by one.

**Describe the solution you'd like**

See the title.

**Describe alternatives you've considered**

**Additional context**

**Comment by ouuan** [comment]
In addition: we can let the user set regex patterns for a pair of input and output (like [lemon](https://github.com/Sojiv/Project_lemon)).

**Comment by ouuan** [comment]
@allcontributors add @StudyingFather as a contributor for ideas.
