### ISSUE TITLE
auto complete { } only option

### ISSUE THREAD

**Issue by tuwuna** [cpeditor/cpeditor#206]
**Is your feature request related to a problem? Please describe.**

Sometimes I don't want the auto-completion of [] and (), but I still want the auto-completion of {}.

**Describe the solution you'd like**

Add an option to enable the auto-completion of {} only.

**Comment by ouuan** [comment]
> ( ) auto complete not always work but { } works perfectly

What does this mean?

**Comment by tuwuna** [comment]
for { -> for { } but if ( remain if (, a[ remain a[ ]

**Comment by ouuan** [comment]
> ( ) auto complete not always work but { } works perfectly

Is this a feature request? This sounds like a statement.

**Comment by tuwuna** [comment]
it is a feature request, I wanted an option to auto complete { bracket only

**Comment by ouuan** [comment]
That doesn't sound like a feature request to me :thinking: 

You should say:

**Is your feature request related to a problem? Please describe.**

Sometimes I don't want the auto-completion of `[]` and `()`, but I still want the auto-completion of `{}`.

**Describe the solution you'd like**

Add an option to enable the auto-completion of `{}` only.

**Comment by tuwuna** [comment]
sorry I don't understand

why is it not a feature request :(

**Comment by tuwuna** [comment]
I updated the issue from "You should say" btw

**Comment by ouuan** [comment]
I Googled for it and found something like this: [Declarative, interrogative, and imperative statements | Learning English Grammar](https://grammar.collinsdictionary.com/easy-learning/declarative-interrogative-and-imperative-statements).

**Comment by ouuan** [comment]
Not only your sentence sounds like a statement rather than a request, the header is also "Is your feature request related to a problem? Please describe.". So I thought that there was something wrong with the completion of `()`.

**Comment by tuwuna** [comment]
I will put it in the form next time

I just felt like the title was clear enough, sorry for that

**Comment by ouuan** [comment]
> I just felt like the title was clear enough but it wasn't, sorry for that

The title is clear enough, but the body makes it confusing.

**Comment by ouuan** [comment]
However, I think there's no good reason to treat `{}` differently, so I suggest adding an option to each parenthesis. This requires #166.
