### ISSUE TITLE
Shows stderr when the verdict is AC

### ISSUE THREAD

**Issue by tuwuna** [cpeditor/cpeditor#207]
**Is your feature request related to a problem? Please describe.**

It's usually not useful when using the built-in checker, or when you test on the sample testcases. But if you use CP Editor as a judger, and the problem has multiple solutions (for example, a constructive problem, you don't need to construct the best solution), it may be useful.

**Describe the solution you'd like**

Like the title.

**Comment by ouuan** [comment]
There should be an option for this.
