### ISSUE TITLE
Checker return no verdict when Expected Output is empty

### ISSUE THREAD

**Issue by tuwuna** [cpeditor/cpeditor#208]
**Screenshots**

![](https://cdn.discordapp.com/attachments/686387177902702626/688981373524246561/unknown.png)

**Comment by ouuan** [comment]
I'd like to say this is not a bug :thinking: 

I treated this "fix" as a feature in f06c58b.

**Comment by coder3101** [comment]
If expected is empty, You don't know what to check your output against and
so Checker is not invoked at all. Checker runs only if *expected* is
non-empty.

This is always behavior with all checkers since 3.0

**Comment by ouuan** [comment]
This will become a good first issue after #166 is done.

**Comment by tuwuna** [comment]
actually if you test something using stderr only output and expected will be empty hence you get an AC
