### ISSUE TITLE
Add package on AUR

### ISSUE THREAD

**Issue by tuwuna** [cpeditor/cpeditor#209]
**Is your feature request related to a problem? Please describe.**

It will be much easier to install, update for Arch users

**Describe the solution you'd like**

So for any arch based user with package helper they can install it with 

yay -S cpeditor

Since it is build from source, you will have all features, custom style like breeze and other things,

To update you need 

yay -Syu --aur 

To uninstall you need

yay -Rns cpeditor (Rns to remove dependency of Qt as well with editor)

**Comment by coder3101** [comment]
There will be two AUR packages namely `cpeditor` and `cpeditor-git`.

This is the usually agreed upon convention of AUR, the base `cpeditor` provides latest stable release. You can update with `yay -Syu cpeditor` if an update is available.

`cpeditor-git` will never get updates, it's like Artifacts. You have to run `makepkg -si` and it will pull latest master and build and install the editor. Everytime you need to reinstall directly from master, do this. No AUR helper will help here!

You need to download from AUR website the PKGBUILD file and run above command on the directory where you have this PKGBUILD

**Comment by coder3101** [comment]
First, I will be releasing `cpeditor-git` package on AUR. This package when installed builds the latest `master` and installs it in user PC (just like normal apps). (Not appimage)

**Comment by coder3101** [comment]
Later `cpeditor` and `cpeditor-beta` will be made. It requires some changes in CI so that it automatically publishes on AUR, So it may take some time.

**Comment by coder3101** [comment]
https://aur.archlinux.org/packages/cpeditor-git/

AUR package for alpha is available. 

Install any package helper like `yay`, then run this command `yay -S cpeditor-git` . This will install the editor after building the master branch and also add Icon to launcher and anything else. To unintall the application, do `pacman -Rns cpeditor-git`

**Comment by coder3101** [comment]
Can anyone confirm this if you use `Arch Linux`?

**Comment by ouuan** [comment]
![image](https://user-images.githubusercontent.com/30581822/78257687-c4dc3c80-752c-11ea-9f85-b627868ceecc.png)

**Comment by coder3101** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/30581822/78257687-c4dc3c80-752c-11ea-9f85-b627868ceecc.png)

Fixed!

**Comment by ouuan** [comment]
BTW, why use clang instead of g++?

**Comment by coder3101** [comment]
> BTW, why use clang instead of g++?

I find it more stable and latest than `g++` in terms of features and also it will download `clang-format` along with it. So format will work out of the box

**Comment by ouuan** [comment]
But users don't have to format codes :thinking: 

I think all Arch Linux users have g++ but not all have clang?

**Comment by ouuan** [comment]
BTW, it works on my machine.

**Comment by coder3101** [comment]
Agreed that `g++` is pre-installed while `clang++` is not but if the user is willing to install `alpha` (-git) of AUR, they should expect it. On top of the benefits I mentioned above, clang diagnostic messages are far better and more detailed and beatified than `g++`. So if compilation failed in case, the error messages will be more detailed and meaningful. (GCC is also adding this starting 9.0 but yet not closet so clang++)

**Comment by ouuan** [comment]
OK

**Comment by ouuan** [comment]
I think the license should be `GPLv3+`?

**Comment by coder3101** [comment]
@ouuan Will be done before the PR is merged

**Comment by ouuan** [comment]
Is cpeditor-beta still in the plan?

**Comment by ouuan** [comment]
It seems that it's time to automate beta and stable.

**Comment by coder3101** [comment]
@ouuan No beta is no longer in plan. The reason is that because I only find in aur two types of packages, cpeditor and cpeditor-git.

**Comment by ouuan** [comment]
We still need to distinguish beta and stable if we want to push only stable to AUR automatically.

**Comment by ouuan** [comment]
However, I kinda don't like `-beta` and `-stable` in the tags.

**Comment by coder3101** [comment]
> We still need to distinguish beta and stable if we want to push only stable to AUR automatically.

So how do I prevent release_aur from running in case of beta release?
Do you have some environment variable that says it?

**Comment by ouuan** [comment]
How about changing `on: tag:` when releasing a new minor version? In fact, it's easier than tag with `-beta` each time.
