### ISSUE TITLE
Add tooltips for widgets

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#211]
**Is your feature request related to a problem? Please describe.**

The functions of some widgets are not clear enough.

**Describe the solution you'd like**

We can add tooltips for them.

**Describe alternatives you've considered**

Write a manual with more information than "Tips".

**Additional context**

This is easy for first-time contributors. Only `widget->setToolTip("A tooltip");` is enough.

**Comment by ouuan** [comment]
However, most worth-add-a-tooltip widgets are in the preferences window, so most of this can only be done after #166 is done.

**Comment by ouuan** [comment]
@neko-para I think we should add a "tooltips" property to the settings, and set tooltips for the labels.

**Comment by neko-para** [comment]
@ouuan You can create a branch so that I can push to it.

**Comment by neko-para** [comment]
Actually, I'm not sure which widget needs tips. I think the label is clear enough.

**Comment by ouuan** [comment]
> @ouuan You can create a branch so that I can push to it.

I think you can create a branch as well?

**Comment by neko-para** [comment]
> > @ouuan You can create a branch so that I can push to it.
> 
> I think you can create a branch as well?

Yes, I can. I've just done it. I used to think I cannot.

**Comment by ouuan** [comment]
> Actually, I'm not sure which widget needs tips. I think the label is clear enough.

Is WhatsThis is better than ToolTip? Maybe the labels are as clear as a tooltip, but WhatsThis can be more detailed.
