### ISSUE TITLE
Wrong behavior of "Toggle Comment" when wrap text is on

### ISSUE THREAD

**Issue by samael042** [cpeditor/cpeditor#213]
**Describe the bug**

When I try to select a few lines and press Ctrl + / to comment on those lines, few lines disappear and incorrect lines are commented.

**To Reproduce**

Turn Wrap text on.

**Screenshots**

![image](https://user-images.githubusercontent.com/44134245/77411469-81722780-6de2-11ea-8b87-31442f5967f8.png)

after pressing Ctrl + /

![image](https://user-images.githubusercontent.com/44134245/77411499-8b942600-6de2-11ea-80ea-28360880eb2b.png)

**Environment**
 - OS: [Windows 10]
 - CP Editor Version: [e.g. 6.1.3]

**Additional context**

Doesn't happen when I turn the wrap text feature off.

**Comment by ouuan** [comment]
@allcontributors add @samael042 as a contributor for bug report.
