### ISSUE TITLE
Please enable System-wide dark theme

### ISSUE THREAD

**Issue by rng70** [cpeditor/cpeditor#215]
Most of the time I do code during midnight. But dark theme only for editor but not for whole system cause is the only thing that hurts me and my eyes most. It will be helpful for others including me if system wide dark theme is made available as I have gone through some comments from CF-blog and found that it was disabled by the developer. So, just add it.

**Comment by coder3101** [comment]
If you use macOS then changing system theme to Dark will make application in dark mode, On Linux with KDE plasma desktop environment also if you enable dark theme from Settings, application will become dark.

On windows 10,  you do have System wide dark theme but it is not compatible with Any QT Apps. However Even if I add some workaround for Windows, It will be based on System settings on Windows 10. 

*For our reference*

Inserting the below code into our project main.cpp file will check if Windows Settings is using Dark mode, if so then it turns everything dark (except editor), You might also need to restart if Settings are changed while CP editor is running.

**Comment by coder3101** [comment]
This change will be removed since Qt will automatically change themes on windows like it does on Linux or Mac, Once this is resolved https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-72028

**Comment by coder3101** [comment]
![ ](https://i.imgur.com/7MODnNC.jpg)

Coming in next release 6.3.x

> **YOU NEED TO RESTART THE APPLICATION EVERYTIME YOU CHANGE EDITOR THEME**

**Comment by ouuan** [comment]
The above "fix" makes the editor background white in all themes. I've reverted that.

**Comment by coder3101** [comment]
@ouuan Did you restart the application after you change the system theme to Dark? While in dark mode it is important and mentioned that you need to restart application if you change the editor theme, other wise it will not be applied correctly.

**Comment by ouuan** [comment]
> @ouuan Did you restart the application after you change the system theme to Dark? While in dark mode it is important and mentioned that you need to restart application if you change the editor theme, other wise it will not be applied correctly.

I didn't check by myself, I heard from @neko-para. I've just confirmed that it works after restarting.

Sorry for not reading about restarting.

**Comment by ouuan** [comment]
I

**Comment by ouuan** [comment]
@allcontributors add @rng70 as a contributor for ideas.
