### ISSUE TITLE
Toggle "view all fonts" when choosing font

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#217]
**Is your feature request related to a problem? Please describe.**

Some monospace fonts don't display when `QFontDialog::MonospacedFonts` is set. It's reported that PragmataPro is one of them.

**Describe the solution you'd like**

Add a "view all fonts" option in the settings.

Since there are more and more font settings, it's good to split Appearance into Appearance/Fonts and Appearance/Miscs.

**Additional context**

It seems that QFontDialog doesn't support this or I didn't find it, so I don't know how to implement this up to now.

**Comment by coder3101** [comment]
Do you think this is important? Font's for code need to be monospaced for a better experience. See [this answer](https://stackoverflow.com/questions/218623/why-use-monospace-fonts-in-your-ide#218639). Why give users customisation that is discouraged in coding?

**Comment by ouuan** [comment]
> Do you think this is important?

No, as it's marked of low p

> Why give users customisation that is discouraged in coding?

For example, the user may want to use a font with ligatures, as mentioned in "Is your feature request related to a problem? Please describe".

**Comment by coder3101** [comment]
![image](https://user-images.githubusercontent.com/22212259/85201815-db21b980-b31f-11ea-83db-d162e2652608.png)

Ligatures are supported by fonts like Cascadia Code, which are pure monospaced.

**Comment by coder3101** [comment]
From commit referenced above.

> In fact, the example in #217, the PragmataPro font, is actually not a
real monospace font, which has ligatures, and doesn't look good on
CP Editor. Users can't have a better experience even if we let them
use that font.

Even you agree to it.

**Comment by ouuan** [comment]
Fira code is another example.

**Comment by coder3101** [comment]
![image](https://user-images.githubusercontent.com/22212259/85202198-4f5d5c80-b322-11ea-8f6f-0146431ddd97.png)

Fira Code Regular works fine!

PS: I am testing on latest beta

**Comment by ouuan** [comment]
I installed `ttf-fira-code` via `pacman` and it's not in the monospaced fonts.

![图片](https://user-images.githubusercontent.com/30581822/85202580-eda8ec80-b339-11ea-9f88-93c2cf753127.png)

![image](https://user-images.githubusercontent.com/30581822/85202563-c0f4d500-b339-11ea-952f-e00d51a70458.png)

![image](https://user-images.githubusercontent.com/30581822/85202569-cce09700-b339-11ea-9b19-b1dd48ad988c.png)

**Comment by coder3101** [comment]
Can you manually install the font from the above repository? Just install a font say fira_code-Regular.ttf

If this works, it means that package `ttf-fira-code` is not purely mono-spaced. Otherwise, It will be a Qt issue!

**Comment by Ravenclaw-OIer** [comment]
Note: Fira code 5.2 installed from the aforementioned repository does **not** work as of v6.6.2

**Comment by Ravenclaw-OIer** [comment]
> ![image](https://user-images.githubusercontent.com/22212259/85202198-4f5d5c80-b322-11ea-8f6f-0146431ddd97.png)
> 
> Fira Code Regular works fine and is identified in CP Editor as a monospaced font!
> 
> PS: I am testing on latest beta and downloaded font from https://github.com/tonsky/FiraCode

Did you install this in the "releases" tab?

**Comment by coder3101** [comment]
![image](https://user-images.githubusercontent.com/22212259/90130061-6ac76f80-dd87-11ea-8228-df18576f0624.png)
We can add a checkbox like CLion (Jetbrain's IDE) does.

**Comment by ouuan** [comment]
> ![image](https://user-images.githubusercontent.com/22212259/90130061-6ac76f80-dd87-11ea-8228-df18576f0624.png)
> We can add a checkbox like CLion (Jetbrain's IDE) does.

That's what I requested at the very beginning. The problem is that QFontDialog doesn't support this.

**Comment by coder3101** [comment]
> That's what I requested at the very beginning. The problem is that QFontDialog doesn't support this.

https://github.com/cpeditor/cpeditor/blob/f2f0d3a4951c9d38e6c4707a6134eab653e7add1/src/Settings/FontItem.cpp#L51
Use a conditional `SettingsHelper::showOnlyMonospacedFonts()` 

It will not be specific to Editor font but for all places.

**Comment by ouuan** [comment]
OK, so your point is that the checkbox is outside of the font dialog.

I think it's good to make a separate page for the fonts.

**Comment by coder3101** [comment]
> OK, so your point is that the checkbox is outside of the font dialog.

That's how CLion does it. The checkbox is outside and when checked the font dialog box shows only monospaced otherwise all fonts.

> I think it's good to make a separate page for the fonts.

The above method is quick and gets the thing done.

**Comment by ouuan** [comment]
> The above method is quick and gets the thing done.

I don't mean a new widget, but splitting Appearance into Appearance/Fonts and Appearance/Miscs.

**Comment by coder3101** [comment]
> > The above method is quick and gets the thing done.
> 
> I don't mean a new widget, but splitting Appearance into Appearance/Fonts and Appearance/Miscs.

OK, fine then.

**Comment by sonulohani** [comment]
Hi @coder3101 , @ouuan ,

Anybody working on this issue otherwise I am interested in working on this.

**Comment by coder3101** [comment]
@sonulohani Yes you can work on this!

**Comment by sonulohani** [comment]
Hi @coder3101 ,
With the current design if I add checkbox "Show only monospaced fonts" in settings.json and add it as a dependency to for example **Editor Fonts** then the layout would be vertical as addRow calls twice in this case. 

![image](https://user-images.githubusercontent.com/2958681/91630574-0267c780-e9f0-11ea-9f08-e7a6c69e012c.png)

What I would suggest is 
To refactor the addRow method in PreferenceGridPage to adopt multiple widget in single row. Currently each row can have only one widget.
Or
To create a new Wrapper class for font(or can modify **FontItemWrapper**). But I am still wondering whats the use of Wrapper class. I don't see any benefit in using it. We could've simply used Qt widgets classes. But this is the topic to discuss for some other time.

**Comment by ouuan** [comment]
> and add it as a dependency to for example **Editor Fonts**

Why do you add it as a dependency of anything? I don't think it's a dependency of anything.

> To refactor the **addRow** method in PreferenceGridPage to adopt multiple widget in single row.

Is that very useful? I don't get what the problem is. I think "Show only monospaced fonts" shouldn't be in the same row as any other setting.

**Comment by sonulohani** [comment]
> > and add it as a dependency to for example **Editor Fonts**
> 
> Why do you add it as a dependency of anything? I don't think it's a dependency of anything.
> 
> > To refactor the **addRow** method in PreferenceGridPage to adopt multiple widget in single row.
> 
> Is that very useful? I don't get what the problem is. I think "Show only monospaced fonts" shouldn't be in the same row as any other setting.

Hi @ouuan 

I was trying to make the widget same as the  one you've shared above of intellij. However it required two widget in a row, one is font item and the other is the checkbox. Are you supposed to have a common checkbox for all 3 fonts items.

**Comment by ouuan** [comment]
> Are you supposed to have a common checkbox for all 3 fonts items.

Yes.

BTW, I thought "dependency" was the "depends" attribute of a setting.
