### ISSUE TITLE
Double quotes or single quotes (",') are autocompleted but closing is not handled.

### ISSUE THREAD

**Issue by ApoorvaRajBhadani** [cpeditor/cpeditor#226]
**Describe the bug**

When we add a quote the other quote is automatically added to the right which is good but when we close it by putting the other quote after the writing of string is completed one more pair of the quote is created.

**To Reproduce**
Just type a quote then write something inside the string then try closing it by putting a new quote.
A new pair of the quote will be created.

**Environment**
 - OS:  Windows 10 
 - CP Editor Version: 6.1.5

**Comment by ouuan** [comment]
@allcontributors add @ApoorvaRajBhadani as a contributor for bug reports.
