### ISSUE TITLE
Better log messages

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#227]
**Is your feature request related to a problem? Please describe.**

The current logs are just full of "invoked"s, a lot of important information is missing. There are also some grammar mistakes and strange sentences.

**Describe the solution you'd like**

Remove some useless log messages and add more information like compile/run commands, parameters of the functions, etc.

Usually, we need the log file because we can't reproduce it on our own devices, and this is often caused by features related to the system and external programs, like compile & run, CF Tool, Competitive Companion, etc. So we need more information on these parts.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by ouuan** [comment]
I don't mean the word "invoked" is bad. In fact, I think "invoked" is better than the description, the description should be the function name or code comments. The descriptions in the logs just make it harder to read.

By "useless 'invoked's", I meant some "invoked"s shouldn't be logged, it's useless to know that they are invoked. However, it's a question which "invoked"s are useful.

**Comment by coder3101** [comment]
I don't think after you reverted this commit, logs contain Compiler invoked commands and other useful information and formatting like "true" instead of 1 and other useful information.

I believe this issue is still open.

**Comment by ouuan** [comment]
> I don't think after you reverted this commit, logs contain Compiler invoked commands and other useful information and formatting like "true" instead of 1 and other useful information.

IMO, "Invoked" is better than different kinds of "Invoked"s, "1" and "true" are the same except the latter is longer.

> I believe this issue is still open.

This was closed because of the "Fix" in the title.
