### ISSUE TITLE
Branch protection fails Push from clang-format bot

### ISSUE THREAD

**Issue by coder3101** [cpeditor/cpeditor#229]
**Describe the bug**
The clang-format bot fails to push the formatted code to the repository because all branches are protected. Either unprotect them (not recommended) or make sure to leverage or whitelist the bot so that it can push to the repository. For more information check https://github.com/cpeditor/cpeditor/runs/573397303

 - OS: NA
 - CP Editor Version: NA

**Comment by coder3101** [comment]
How did you fix it?

**Comment by ouuan** [comment]
I think this is good because we don't want formatting commits in the log. In non-protected branches, we can rebase before merging, but it's better not to do this on the master branch.

**Comment by ouuan** [comment]
> How did you fix it?

Format and force-push.

**Comment by ouuan** [comment]
The format workflow can warn you, and then you can manually format and force-push.

In case anyone thinks force-push is bad, I'd like to introduce `git push --force-with-lease` which checks whether the remote has updated or not before force-push.

**Comment by ouuan** [comment]
I just realized that it's a good idea to use `git push --force-with-lease` for the formatting workflow :thinking: 

However, if we use something like personal tokens, it won't work on forks. So we still can't solve this problem without removing the branch protection rule.

**Comment by ouuan** [comment]
I think many IDEs can format codes on save, so this is not a big problem.
