### ISSUE TITLE
Extra empty lines after the last line of code

### ISSUE THREAD

**Issue by tuwuna** [cpeditor/cpeditor#230]
**Is your feature request related to a problem? Please describe.**

![](https://cdn.discordapp.com/attachments/686387177902702626/698157182415405196/unknown.png)

**Describe the solution you'd like**

![](https://cdn.discordapp.com/attachments/686387177902702626/698157243178156072/unknown.png)

**Comment by ouuan** [comment]
IMO it's very hard to implement, you can open an issue for Qt and wait for them to add this feature.

**Comment by tuwuna** [comment]
![](https://cdn.discordapp.com/emojis/676503440687628348.png?v=1)
