### ISSUE TITLE
VCRUNTIME140_1.dll missing while installing

### ISSUE THREAD

**Issue by return-z** [cpeditor/cpeditor#231]
![cpeditor exe - System Error 4_10_2020 7_11_25 PM](https://user-images.githubusercontent.com/63389752/78996190-b233ba00-7b61-11ea-92ef-01e1783dcbca.png)

It seems like an installation issue. I'm not really sure if something is wrong on my end or not, but it happens on my Win 10 PC.

Something is not allowing smooth installation and execution of the program. I've tried re-installing and the issue still persists.

 - OS: Windows 10 Home Ver 10.0.18362
 - CP Editor Version: 6.1.6

**Comment by ouuan** [comment]
https://github.com/cpeditor/cpeditor#faq
