### ISSUE TITLE
When the dark theme is enabled in Windows 10, the application theme does not change.

### ISSUE THREAD

**Issue by luparev22** [cpeditor/cpeditor#234]
**Describe the bug**

After changing the system theme to dark, the application theme does not change, no matter how many times I restart the program or change the theme.

**To Reproduce**

Run the program with the dark theme enabled. (Perhaps this bug is only mine)

**Screenshots**

![image](https://user-images.githubusercontent.com/18050309/79198384-99771d00-7e5d-11ea-91fe-e551dec7e12a.png)
![image](https://user-images.githubusercontent.com/18050309/79198520-cfb49c80-7e5d-11ea-9402-ccc7caf45ca9.png)

**Environment**

 - OS: Windows 10
 - CP Editor Version: 6.1.6

**Additional context**

- I saw that when parsing a dark theme, the AppUseLightTheme registry key is scanned. With him everything is in order, with a dark theme, it is set to 0.
- I tried to run the program on behalf of the Administrator - nothing changes.
- Rebooting the system does not help

**Comment by coder3101** [comment]
The dark theme did not make it into this stable release. Please use the beta version or wait for the next beta release.

**Comment by coder3101** [comment]
Neither the changelog of 6.1.6 says that Dark theme was added. So wait with Patience or use the beta release.

**Comment by ouuan** [comment]
Just to clarify, the feature you requested has been added in v6.3, which is not available now but will be available soon. If you want, you can [use the Artifacts](https://github.com/cpeditor/cpeditor/blob/master/doc/INSTALL.md#Use-Artifacts) before v6.3 is released. However, it's recommended to wait for the next release.
