### ISSUE TITLE
First problem in Codeforces competition cannot be submitted

### ISSUE THREAD

**Issue by alexei-R** [cpeditor/cpeditor#236]
**Describe the bug**

I have noticed in the last 2 or 3 Codeforces contests in a row (since I discovered and started using CP Editor), that after I enter the competition, the first problem I parse using the plug-in, has a zero in the name of the tab, instead of the capital letter like the subsequent problems do. Because of that, it is also not possible to submit the problem from the editor directly.

**To Reproduce**

Prerequisites: CP Editor, CF Tool, Competitive Companion plugin.
Steps:
- Register for a Codeforces contest (a real contest, I could not reproduce the issue in a virtual contest).
- Have the CP Editor ready (opened) and enter the contest when it begins.
- Open the link with the statement of the first problem (labelled A usually).
- Parse the problem and its test cases by pressing the green button of the Competitive Companion plug-in.
- Go to CP Editor, and observe that a tab labelled 0 was generated from the problem just parsed.
- Write code to solve the problem.
- Test it by pressing "Compile and Run" button and checking the test cases.
- Attempt to submit the code by pressing "Submit" button.
- Observe the messages in the "Messages and stderr" window. It looks like CF Tool complains about the wrong label (0 instead of e.g. A) and cannot make a valid submission.
- Go to the list of your submissions for the contest on Codeforces and observe that there is no submission resulting from this attempt, hence the code needs to be submitted manually on the contest page.

Note that it only occurs for the first problem, my guess would be that the first _parsed_ problem is relevant, rather than the first problem of the contest, but I did not try to start with another problem to confirm or disprove it yet.
**Screenshots**
![grafik](https://user-images.githubusercontent.com/63749693/79389531-c9faac00-7f6e-11ea-9eeb-b435a322ee4b.png)

Only the first tab in the screen shot is relevant for this issue, the others (B to D) were generated later, and the screen shot was taken after contest.

**Environment**

 - OS: Ubuntu 16.04.6 LTS
 - CP Editor Version: 6.1.6
 - CF Tool Version: 1.0.0
 - Competitive Companion plug-in Version: 2.15.0
 - Browser and Version: Firefox 75.0 64-bit

**Additional context**
I can not tell if the issue is caused by CP Editor, might come from the plug-in.

**Comment by ouuan** [comment]
See xalanq/cf-tool#79.

In fact, the problem ID "0" was replaced by "A" in CP Editor before CF Tool 1.0.0. However, it's not a completely correct solution —— it fails if the first problem is not "A", for example, it may be [A1](https://codeforces.com/contest/1188/problem/0). CF Tool has supported `cf submit <url>` since 1.0.0, so we decided to leave this for CF Tool because it can get the real problem ID.

I'd recommend you to parse the whole contest in the dashboard instead of parsing each problem separately before this is fixed.
