### ISSUE TITLE
Add duplicate line feature

### ISSUE THREAD

**Issue by m3h3d1** [cpeditor/cpeditor#237]
**Is your feature request related to a problem? Please describe.**

This is a very common feature but missing from our editor.

**Describe the solution you'd like**

Add a keybinding to duplicate a line

**Additional context**

N/A

**Comment by ouuan** [comment]
Do you think <kbd>Ctrl+Alt+D</kbd> is good? Or should I use <kbd>Ctrl+Alt+D</kbd> for detached run and <kbd>Ctrl+Shift+D</kbd> for duplicate line?

**Comment by m3h3d1** [comment]
Using `Ctrl+Shift+D` for duplicate line is more convenient. So it's better to use `Ctrl+Alt+D` for detached.

**Comment by ouuan** [comment]
This shortcut conflict stopped me from adding this feature. However, since you are requesting this, I'd like to add it now.

**Comment by m3h3d1** [comment]
Thanks for your consideration...

**Comment by ouuan** [comment]
> Thanks for your consideration...

It has already been added in ffac70c (6 hours ago), but you may have to wait for several weeks for v6.4 unless you [bulid from source](https://github.com/cpeditor/cpeditor/blob/master/doc/INSTALL.md#Build-from-source) / [use Artifacts](https://github.com/cpeditor/cpeditor/blob/master/doc/INSTALL.md#Use-Artifacts).

**Comment by ouuan** [comment]
@allcontributors add @m3h3d1 as a contributor for ideas.
