### ISSUE TITLE
Can you add Completions from Sublime Text to CP Editor?

### ISSUE THREAD

**Issue by DarkWarrior703** [cpeditor/cpeditor#240]
If it's hard to implement Auto-complete code, can you implement Completions? It's great to have a page like Snippets where you submit some definition and some shortcuts and save. When you write the text using the shortcut, it automatically writes the definition. For example 
`vector<int> ` with vi or `long long` with ll.

**Comment by ouuan** [comment]
1. Auto-complete will be added soon. You can track the progress at #156.
2. You can add snippets in the Preferences, and use them by <kbd>Ctrl+T</kbd> and enter the name of the snippet.
3. I think you can use `typedef vector<int> vi;` and `typedef long long ll`?
