### ISSUE TITLE
Wrong details of memory and time limits in the comments above.

### ISSUE THREAD

**Issue by cs-mshah** [cpeditor/cpeditor#245]
The comments have memory and time limits both 0.

**Comment by ouuan** [comment]
See <https://github.com/jmerle/competitive-companion/commit/da1ec823b0f7e2fff0d07b9b9b30f21a086519c4>.

![image](https://user-images.githubusercontent.com/30581822/79951263-f2bcfd00-84aa-11ea-9588-4f4dd318477f.png)

![image](https://user-images.githubusercontent.com/30581822/79951280-f9e40b00-84aa-11ea-84e3-aee83c3afc8b.png)

You should wait for this update available on Chrome store.
