### ISSUE TITLE
Python doesn't work!

### ISSUE THREAD

**Issue by utk-dev** [cpeditor/cpeditor#255]
**Describe the bug**

A certain codeforces ACCEPTED problem solution gives EOF error in CP Editor.

**To Reproduce**

1. [This solution](https://codeforces.com/contest/1343/submission/77941933) is an accepted solution of [this problem](https://codeforces.com/contest/1343/problem/D).
2. Use Competitive Helper Browser Extension to fetch the question and test cases automatically.
3. The question appears inside the editor, now switch to Python on top-right corner of the window and save the file.
4. Write the solution. **Compile and Run** it, or just **Run** it since it's Python script.
5. You get `unexpected EOF while parsing` error for the sample test case.
6. Weird because it is an **Accepted Problem**.

**Screenshots**
 
![screen](https://user-images.githubusercontent.com/25015384/80272329-e7094a80-86e5-11ea-9291-1dc1911fae5a.jpg)

**Environment**

 - OS: Lubuntu 20.04
 - CP Editor Version: 6.2.4
 - g++ 9.3.0
 - python 3.8.2

**Additional context**
1. Here is the full error:
```python 
Traceback (most recent call last):
  File "/home/utkarsh/Desktop/D.py", line 2, in <module>
    n, k = map(int, input().split())
  File "<string>", line 1
    4 2
      ^
SyntaxError: unexpected EOF while parsing
]
```

2. If you run this script from a separate terminal and enter the sample test case manually, it doesn't give any error and gives correct output. So there is certainly something wrong with how CP Editor feeds input to the python script!

![screen01](https://user-images.githubusercontent.com/25015384/80272468-4f0c6080-86e7-11ea-9f52-feb34450e5eb.jpg)

3. Something is wrong only with how python is handled because C++ code for the exact same question works fine!

![screen02](https://user-images.githubusercontent.com/25015384/80272673-140b2c80-86e9-11ea-9695-0d205668c3b5.jpg)

**Comment by ouuan** [comment]
1. This runs well on my machine.
2. Can you reproduce this error and upload the log file? You can find the log file by clicking options->Show Log Files.

**Comment by coder3101** [comment]
Works fine on my Windows and Linux machine both.
Same app version and Same python version.

![Annotation 2020-04-25 120329](https://user-images.githubusercontent.com/22212259/80273064-cabcdc00-86ec-11ea-88d1-ab6567349814.jpg)

**Comment by utk-dev** [comment]
Ah I changed the execute command for python from preferences menu from just `python` to `python3` and it works on my machine as well.

**Comment by coder3101** [comment]
For others who might get EOF Error !

EOF (End of File) error occurs with Python if your input text is less than what you are reading in your program. Like

```python
testcase = int(input())
for _ in range(testcase):
    y = input()
    print(solve(y))
```

Input that works fine: 
```
2
Foo
Bar
```

Input that doesn't works:
```
3
Foo
Baaz
```

Missing one string! EOF Error

This is not the case with C++, it reads some garbage stuff.

**Comment by ouuan** [comment]
> For others who might get EOF Error !

I think the difference of `input()` in Python2 and Python3 is more important :thinking:
