### ISSUE TITLE
Jump outside of closing brackets/quote with Tab when typing

### ISSUE THREAD

**Issue by GoBigorGoHome** [cpeditor/cpeditor#256]
**Is your feature request related to a problem? Please describe.**
When coding, frequently I have to move the cursor outside of closing brackets/quote by pressing the right arrow key, and I find it kinda slow to do that. 

**Describe the solution you'd like**
Implement the "Jump outside of closing brackets/quote with Tab when typing" feature for the editor.
This feature is available in Visual Studio and CLion, and also in VS Code by [extension](https://github.com/microsoft/vscode/issues/22864#issuecomment-388989201).

**Describe alternatives you've considered**

**Additional context**

**Comment by coder3101** [comment]
This feature requests is to `QCodeEditor` but I will keep it here on `cpeditor` because when QCodeEditor adds it, this feature should get its place in new preference window. 

@ouuan you can re-prioritize this issue and maybe add it as per your convenience.

**Comment by ouuan** [comment]
In addition, I think it should be treated like #206, i.e. has a separate configuration for each parenthesis.

It's not hard to implement, just add checks for parentheses in these lines:

https://github.com/cpeditor/QCodeEditor/blob/7b7bf07834a23185e78a3e3582123fa6f04653b7/src/internal/QCodeEditor.cpp#L592-L604

And here's a good reference:

https://github.com/cpeditor/QCodeEditor/blob/7b7bf07834a23185e78a3e3582123fa6f04653b7/src/internal/QCodeEditor.cpp#L663-L693

**Comment by ouuan** [comment]
@allcontributors add @GoBigorGoHome as a contributor for ideas.
