### ISSUE TITLE
Support app-wide dark theme in the settings

### ISSUE THREAD

**Issue by Ravenclaw-OIer** [cpeditor/cpeditor#265]
**Is your feature request related to a problem? Please describe.**

Now, we cannot use app-wide dark theme on GNOME desktop environment.

**Describe the solution you'd like**

Support app-wide dark theme on GNOME.

**Describe alternatives you've considered**

~~When launching, force the user to switch to KDE~~

**Additional context**

Currently using Ubuntu 20.04 LTS with default GNOME

**Comment by coder3101** [comment]
I propose this we fix it just as we fix Dark theme for Windows.

Check if a Dark theme type is being used in GTK, if so we apply the dark palette. 

We still need to add check for Plasma where we will not apply dark palette because KDE integrates nicely with Qt and automatically changes the theme.

**Comment by coder3101** [comment]
Are you able to compile our editor from source? If you are able to please check if changing theme via Palette works fine on GNOME.

Add inside `appwindow.cpp`. Inside constructor of AppWindow, in very last of its body.

```cpp
qApp->​setStyle​(​QStyleFactory::create​(​"​Fusion​"​));
qApp->​setPalette​(​Util::windowsDarkThemePalette​());
qApp->​setStyleSheet​(​"​QToolTip { color: #ffffff; background-color: #2a82da; border: 1px solid white; }​"​);
```

Compile it and You will have system wide Dark mode. See if it is consistent and reliable on your GTK.

Report your discovery here!

**Comment by coder3101** [comment]
I think I will add a new settings in General or Appearance named "Enforce Dark Palette" checkbox.

If checked the application will use Dark Palette but also warn the user that if in macOS, Windows or KDE use System dark theme from Settings and not this option.

This way for any other OS/DE where dark mode is not supported, user still has a chance some dark layout.

@ouuan Add this to #269 
Also let me know any other options that you think would be better than this.

**Comment by ouuan** [comment]
> but also warn the user that if in macOS, Windows or KDE use System dark theme from Settings and not this option

I don't think it's necessary :thinking: For macOS and KDE users, it should be dark without this option. It's also unnecessary for Windows users.

**Comment by ouuan** [comment]
> @ouuan Add this to #269

That issue is for the settings without an issue, not for all settings. I opened it just for convenience. The current issue is the best place for this feature request.

**Comment by ouuan** [comment]
We can also make styles like fusion available in the preferences, by `QStyleFactory::keys` and `QStyleFactory::create`.

**Comment by coder3101** [comment]
> 
> 
> We can also make styles like fusion available in the preferences, by `QStyleFactory::keys` and `QStyleFactory::create`.

As for now, on KDE you can change the looks from Settings, for Windows the default white theme uses "Windows" Style and Dark theme uses "Fusion" style. The dark colour palette only looks good on the "Fusion" style, so people can use both styles by just changing the theme. 

For reference, you can try applying dark palette on "Windows" Style, it looks awful. However the "Fusion" style looks equally good in both Dark and Light theme. So, I can;t figure out what approach is best here.

**Comment by ouuan** [comment]
> For reference, you can try applying dark palette on "Windows" Style, it looks awful. However the "Fusion" style looks equally good in both Dark and Light theme. So, I can;t figure out what approach is best here.

The user can simply not use dark palette with the Windows style, nothing bad happens. Or we can restrict the dark palette to the fusion style only.

**Comment by coder3101** [comment]
GTK (GNOME) does not have Dark theme support for Qt, however, the palette used for Windows dark theme if used looks really good 

![image](https://user-images.githubusercontent.com/22212259/84149946-d6871680-aa7e-11ea-9575-364062ee8979.png)

We can add an option in Settings for Linux only. (Enforce Dark Palette). Whenever the user checks this, we should warn that if they are using "KDE" they should instead use the dark theme as it is will be more consistent. Also, whenever the Editor theme is changed while in Dark Palette, we should tell the user to restart as we do in case of Windows!

As for the style, like "Fusion", "Windows" etc, I think they are only good for "Windows OS" or will that setting be for all platforms?

At this point, I think that there should be an option for `settings.json` to specify os. Like:

```
{
        "name": "Enforce Dark theme",   
        "desc": "Overrides default Palette with a Dark Palette",  
        "type": "bool",  
        "os": ["linux", "mac"] // Only makes this setting, visible in Linux and Mac!  
}
```

**Comment by ouuan** [comment]
My plan:

The user can choose from:
1.  The default style.
2.  The system provided styles, we can get them by `QStyleFactory::keys`.
3.  If the system provides the fusion style, the user can choose the fusion style with the dark palette.
     -   When the user changes the editor theme when the application style is fusion with the dark palette, the user gets warned to restart the application.

**Comment by coder3101** [comment]
> 
> 
> My plan:
> 
> The user can choose from:
> 
>     1. The default style.
> 
>     2. The system provided styles, we can get them by `QStyleFactory::keys`.
> 
>     3. If the system provides the fusion style, the user can choose the fusion style with the dark palette.
>        
>        * When the user changes the editor theme when the application style is fusion with the dark palette, the user gets warned to restart the application.

I get it, **Dark palette for only Fusion style**. I recommend dark palette be only visible for Linux and not for Windows or macOS because they natively or intelligently(as with windows) change the palette to dark.

My concern:

There should not be two ways to darken the theme. Palette and System Setting theme default.

**Comment by ouuan** [comment]
> There should not be two ways to darken the theme. Palette and System Setting theme default.

I suggest either remove the system dark theme check on Windows, or add an option to follow the system dark theme.

**Comment by ouuan** [comment]
My idea is not to force the application to use the system theme, and make it changeable in the settings besides in the command line.

**Comment by coder3101** [comment]
At this point, I think it would be better to just have an option in appearance called Theme with 3 options:

- Default
- Dark (Always enforced with Palette)
- System Default (On windows with dark theme use palette otherwise no change, OS will handle colours)

We can also provide Style likewise, let the user choose whichever they feel is okay. Leave the "Windows" style too. They can tune it for themselves.

**Comment by coder3101** [comment]
Obviously System default will have no impact on "GNOME". But user can use "Dark" to get a dark theme instead. This is how most application deal with it. In system settings, some people keep timed (day/night) themes, they can use the System default, otherwise, most user will prefer to use always the dark theme for just CP Editor and they can use "Dark".

**Comment by coder3101** [comment]
> At this point, I think it would be better to just have an option in appearance called Theme with 3 options:
> 
>     * Light
> 
>     * Dark (Always enforced with Palette)
> 
>     * System Default (On windows with dark theme use palette otherwise no change, OS will handle colours)

I just realized we might need a Light Palette as well because how do you plan to keep application light when KDE setting is using Dark theme?

**Comment by ouuan** [comment]
1.  The default style.
2.  The system provided styles, we can get them by `QStyleFactory::keys`, except fusion.
-   If the system provides the fusion style:
    3.  Light fusion.
    4. Dark fusion.
    - If we can determine whether the system theme is light or light:
        5. Automatic fusion. (depending on system dark/light theme)

**Comment by coder3101** [comment]
Let's move ahead with your above recommendation. I will test it on GNOME, Windows and Mac and you can test on KDE (that has Auto dark for Qt apps) and we can refine or fine-tune as we proceed.

**Comment by ouuan** [comment]
Or we can try [BreezeStyleSheets](https://github.com/Alexhuszagh/BreezeStyleSheets).

**Comment by sonulohani** [comment]
Hi @coder3101 

In my opinion, you should provide either xml or json option for color schemes instead of hard coding the color values in the code(saw it in PR). This gives user flexibility to add their own color scheme as well. Whats your opinion on this.

**Comment by ouuan** [comment]
> In my opinion, you should provide either **xml** or **json** or **group box with color picker in setting dialog for every palette** in color schemes instead of hard coding the color values in the code(saw it in PR). This gives user flexibility to add their own color scheme as well. Whats your opinion on this.

That could be an option. We can let the user use a custom `qss` file, along with the current options.

**Comment by coder3101** [comment]
> In my opinion, you should provide either **xml** or **json** or **group box with the color picker in setting dialogue for every palette** in colour schemes instead of hard coding the colour values in the code(saw it in PR). This gives the user flexibility to add their own colour scheme as well. What's your opinion on this.

It is a nice idea but the current PR is to solve a different issue, for OS that does not provide dark theme or qt does get darken (like in gnome). We will provide Styles that are darker.

These are just standard styles, not colour schemes. We can have a different issue for colour customization. A custom `qss` file will be a better idea.
