### ISSUE TITLE
Logo display broke on GNOME 3.36 dark theme

### ISSUE THREAD

**Issue by Ravenclaw-OIer** [cpeditor/cpeditor#266]
**Describe the bug**

The logo display is not functioning as should.

**To Reproduce**

Just run it on gnome 3.36, with dark theme.

**Screenshots**

**Environment**

- OS: Ubuntu 20.04 LTS with GNOME 3.36
- CP Editor: 6.3.1

**Additional context**

**Comment by ouuan** [comment]
Don't you think a screenshot or more details are necessary for us to understand?

**Comment by Ravenclaw-OIer** [comment]
Sorryyyyy... I had one but github 502ed when I tried to submit it...

Anyway...

On the top of the desktop environment is a "Activities" bar, and I am using the dark theme.

The logo of the editor on the bar is not a green-to-cyan circle, instead, it is an oval with everything inside cramped up.

**Comment by coder3101** [comment]
A picture speaks a thousand words!

**Comment by Ravenclaw-OIer** [comment]
Trying to get the screenshot... It is beyond the normal window area so deepin screenshot is of no use.

**Comment by Ravenclaw-OIer** [comment]
![Screenshot from 2020-04-27 00-16-06.png](https://i.loli.net/2020/04/27/fiZYGElTxKSnoCF.png)

**Comment by Ravenclaw-OIer** [comment]
![Screenshot from 2020-04-27 00-17-40.png](https://i.loli.net/2020/04/27/iNEfJkKXgG2ozWe.png)

**Comment by coder3101** [comment]
@ouuan Is that set using `app->setWindowIcon()` ??

**Comment by coder3101** [comment]
On my GNOME, with Arch Linux this looks normal.

**Comment by neko-para** [comment]
It seems not because of the dark theme. It's just happened on Ubuntu 20.04
![pic](https://user-images.githubusercontent.com/26452623/80550319-52a72c80-89f2-11ea-950b-1b3037f922d2.png)

**Comment by coder3101** [comment]
I can't produce this issue on **GNOME 3.36.2**. You could wait for canonical to release an update of GNOME. As for the colour of the icon, (black and white) is with all applications. That status bar does not support coloured images.

![image](https://user-images.githubusercontent.com/22212259/84151969-b0af4100-aa81-11ea-8889-a3a99ff3fbfd.png)

**Comment by Ravenclaw-OIer** [comment]
This is probably a GNOME internal issue.

Closing this.

~~BTW KDE is much better~~

**Comment by Ravenclaw-OIer** [comment]
@Ravenclaw-OIer Slightly off topic: Canonical is just really slow at releasing everything!
