### ISSUE TITLE
Improve the way that language server alerts about errors

### ISSUE THREAD

**Issue by DarkWarrior703** [cpeditor/cpeditor#267]
When you are in a contest, it's hard to realise if there is a red line. It will be better if you show the warnings inside the message box like on VS Code or make a new table with Syntax errors and compilation errors.

**Comment by coder3101** [comment]
This issue will be closed when #241 is merged because in it we brought change to QCodeEditor that highlights the line number containing error or warning in addition to Error underline

**Comment by ouuan** [comment]
@allcontributors add @DarkWarrior703 for ideas.
