### ISSUE TITLE
More settings

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#269]
![near-future plan](https://user-images.githubusercontent.com/30581822/77845345-c500d300-71e0-11ea-99c0-a449c48d88ff.png)

_Originally posted by @ouuan in https://github.com/cpeditor/cpeditor/issues/166#issuecomment-605607699_

Some settings of this plan are neither added nor requested in an issue, so I open this for them.

**Comment by neko-para** [comment]
Why this issue is still open? It seems that all the settings have been added.

**Comment by ouuan** [comment]
> It seems that all the settings have been added.

No.

**Comment by ouuan** [comment]
Now there are the following places to choose a file path (or directory):

1. Open Files
2. Save File / Save As
3. Open Contest
4. Export/Import settings
5. Export/Load session
6. Export/Load snippets
7. Choose C++ template
8. Choose Java template
9. Choose Python template
10. Choose various executable files in the settings, including CF Tool and Clang Format.
11. Load a single test case from file
12. Add pairs of test cases from files
13. Choose a custom checker

My plan is to give the user 13 (or more) default paths, and the setting for each action consists of two options, the default path to use and the default path to change. The default path to use is used as the default path in the QFileDialog, and the default path to change is changed after choosing the path. Both of them can be omitted, i.e. the default path in the QFileDialog can be empty and there can be nothing changed after choosing the path. Each default path can also be changed manually in the settings. In addition to this, the default path for saving a file can be overridden by "Default File Paths For Problem URLs".

This is a little bit too complicated, however, the user can ignore it and use the default settings. Are there any better ideas?

**Comment by ouuan** [comment]
Now except for the log-file-related settings, other unimplemented settings have their own issues. Because the log file is very basic, now I think it's better not to have those settings.

So all things are finished.
