### ISSUE TITLE
Add an option to save the executable files in the temp directory or the source file directory

### ISSUE THREAD

**Issue by cs-mshah** [cpeditor/cpeditor#271]
**Describe the solution you'd like**
Automatically delete the filename.out file after execution or on closing the tab for that problem in editor.

As we click to submit other problems on codeforces, the folder contains the .out files of several problems along with the .cpp files.
These files should be deleted to make the folder cleaner.
**Describe alternatives you've considered**

having a common a.out file instead of filename.out or deletion of the .out file after exectution. Also tell if there are any arguments that can be passed to fix this.
we can have something like rm filename.out
**screenshot**

![Screenshot from 2020-04-29 18-39-38](https://user-images.githubusercontent.com/56499208/80599681-ee638780-8a48-11ea-9c6e-f8d277695102.png)
The problems candies, constant palindrome sum have been done on CP editor and have those .out files there whereas others done using sublime have them removed using custom build

**Comment by ouuan** [comment]
1. In the current version, you can disable "Save Testcases on Save" in the preferences window.
2. In the next version, in which #176 is added, you can save all test case files in the same directory or anywhere you like.
3. To submit to Codeforces, you can use CF Tool, which is very convenient.

**Comment by cs-mshah** [comment]
It is not the test cases that I am talking about, it is the .out file which gets generated after compiling the cpp file. Just have a look at what I am saying.

**Comment by ouuan** [comment]
I think "executable files" is much more clear. ".out files" is just confusing, even in your screenshot the executable files are without any suffix. The most possible guess is that ".out files" are the test case files.

I suggest adding an option to save the executable file in the temp directory or the source file directory, instead of deleting them after execution.

**Comment by ouuan** [comment]
@allcontributors add @cs-mshah as a contributor for ideas.
