### ISSUE TITLE
Add All Contributors

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#277]
We can add [All Contributors](https://allcontributors.org/) in the README to thank the contributors.

Some advantages of it over <https://github.com/cpeditor/cpeditor/graphs/contributors>:

1. It's in the README so it's more obvious.
2. We can specify the types of contributions for each contributor.
2. We can add contributors that only report a bug or request a feature, not only those who contributed with commits.

**Comment by ouuan** [comment]
@allcontributors add @ouuan for code, maintenance, and doc.

**Comment by ouuan** [comment]
@allcontributors add @coder3101 for maintenance, code, doc, ideas and bug report.

**Comment by ouuan** [comment]
@allcontributors add @neko-para for code, doc, translation and ideas.

**Comment by ouuan** [comment]
@allcontributors add @sadykhzadeh for translation.

**Comment by ouuan** [comment]
@allcontributors add @IZOBRETATEL777 for translation.

**Comment by ouuan** [comment]
@allcontributors add @Razdeep for code and ideas.

**Comment by ouuan** [comment]
@allcontributors add @testitem for code, ideas and bug report.

**Comment by ouuan** [comment]
@allcontributors add @polyomino-24 for doc.

**Comment by ouuan** [comment]
@allcontributors add @ouuan for review.

**Comment by ouuan** [comment]
@allcontributors add @coder3101 for review.

**Comment by ouuan** [comment]
@allcontributors add @nikhil-sarda for bug reports.

**Comment by ouuan** [comment]
@allcontributors add @tuwuna for ideas.

**Comment by coder3101** [comment]
Is it complete? Can it be closed now.

**Comment by ouuan** [comment]
@allcontributors add @Razdeep for bug report.

**Comment by ouuan** [comment]
@allcontributors add @testitem for doc.

**Comment by ouuan** [comment]
@allcontributors add @ouuan for infra.

**Comment by ouuan** [comment]
@allcontributors add @coder3101 for infra.

**Comment by ouuan** [comment]
@allcontributors add @ouuan for infra.
