### ISSUE TITLE
Customizable message logger font

### ISSUE THREAD

**Issue by 2740365712** [cpeditor/cpeditor#331]
**Describe the bug**
The font in the warning messages does not support Chinese.I think this problem has an impact on debugging.

**To Reproduce**
My file is stored in E:/编程/C++/NOIP普及组 .

**Screenshots**
![](https://s1.ax1x.com/2020/05/10/Y1RXjS.png)

**Environment**

 - OS: Windows 10
 - CP Editor Version: 6.3.2

**Comment by ouuan** [comment]
To fix this, we have to let the user choose the font of the message.

**Comment by ouuan** [comment]
@allcontributors add @2740365712 as a contributor for ideas.
