### ISSUE TITLE
Giving a space while typing fast!!!

### ISSUE THREAD

**Issue by Mahmud-cse** [cpeditor/cpeditor#351]
**Describe the bug**
while I type for loop then after the bracket a space is creat and the second bracket goes near the number.

**To Reproduce**

**Screenshots**
![Annotation 2020-05-12 135742](https://user-images.githubusercontent.com/52972839/82047542-ccb70100-96d4-11ea-948c-b08e0eb6fe23.png)
![Annotation 2020-05-12 140039](https://user-images.githubusercontent.com/52972839/82047551-cf195b00-96d4-11ea-847a-f1f3f7708adb.png)

**Environment**

 - OS: [e.g. Windows 10 ]
 - CP Editor Version: [ 6.3.3]

**Additional context**

**Comment by ouuan** [comment]
1. Did you press <kbd>Enter</kbd> or <kbd>Shift+Enter</kbd>?

2. Did you enable text wrap? It will be better if you can provide a screenshot of you Code Edit settings.

**Comment by ouuan** [comment]
I guess you pressed <kbd>Shift+Enter</kbd>. This behavior is changed in v6.4 (it is the same as <kbd>Enter</kbd> in v6.4) because it affects the language server linting. We thought it doesn't harm much without linting so we didn't change this in v6.3.

**Comment by Mahmud-cse** [comment]
of course,i press enter.and why i will press shift+enter?
![Annotation 2020-05-15 182046](https://user-images.githubusercontent.com/52972839/82049870-f2dea000-96d8-11ea-953f-f141bdb98a99.png)

**Comment by ouuan** [comment]
> and why i will press shift+enter

In your title, you said you were "typing fast", and you might be holding Shift when typing "{".

**Comment by Mahmud-cse** [comment]
lol.typing fast means i type fast with holding shift?

**Comment by ouuan** [comment]
> typing fast means i type fast with holding shift?

I was guessing, not saying you were. You didn't describe how to reproduce it, so I HAVE TO GUESS.

So, can you reproduce it (make this "bug" happen again)? If you can, please describe a minimal way step by step.

**Comment by coder3101** [comment]
This issue will be closed if you cannot reproduce it and report the steps within next  48 hours.
