### ISSUE TITLE
Auto-cursor to desired location on template loading

### ISSUE THREAD

**Issue by shakeabi** [cpeditor/cpeditor#352]
**Is your feature request related to a problem? Please describe.**

Whenever I parse a question or use a template I would like the cursor to go to a desired location(e.g. inside the main function). It's frustrating to scroll down all the time. (especially if you have a long template)

**Describe the solution you'd like**

Having a special key like %DEFAULT_POS% inside template. When such a template is loaded, the cursor can move to that loc directly on open.

**Comment by ouuan** [comment]
I think it will be better if the user can provide a regular expression (like `main()`), and the default cursor position is where it matches first.
