### ISSUE TITLE
Open File Length Limit causes file loss after language server is added

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#353]
**Describe the bug**

The origin file will be lost if the Open File Length Limit is exceeded. In v6.3, only the editor will be changed to "Open File Length Limit Exceeded", but it won't be saved to the file.

**To Reproduce**

Open a file that is longer than the Open File Length Limit.

**Screenshots**

![image](https://user-images.githubusercontent.com/30581822/82110599-523cbe80-9772-11ea-8f89-b1fb4a875085.png)

**Environment**

 - OS: Manjaro KDE
 - CP Editor Version: since 5fc3dd9.

**Additional context**

I'm investigating this.

And it's better to change this behavior even before the Language Server is added, because the user may save the text "Open File Length Limit Exceeded" by accident.

**Comment by ouuan** [comment]
In addition, now a file is saved when switching to its tab.

**Comment by ouuan** [comment]
We need a clear compile & run path, save path, language server path system. And #271 is related to this.

**Comment by ouuan** [comment]
My plan:

1. All operations which need a source file except saving the file, like compile, run, linting, etc. use the same temporary directory, which contains the source file, no matter the tab is titled or not.
2. The user can choose the path of the compiled binary, some keywords like `${tempdir}`, `${filename}` and `${basename}` are provided, so that the user can choose where to save and run the executable file, including the temporary directory, an absolute path or a path relative to the source file 
3. The user can choose to save the source file on compile/run or not.

**Comment by ouuan** [comment]
This will be a big change, though it fixes a bug, since the change is too big, we won't be 100% sure that it won't introduce new bugs. And, this bug doesn't affect v6.3 very much, so I suggest only make this change in v6.4.

**Comment by ouuan** [comment]
What about making the compile command and the run command completely customizable? i.e. Let the user add `-o ${tmpdir}/${basename}`, etc.

**Comment by coder3101** [comment]
> What about making the compile command and the run command completely customizable? i.e. Let the user add `-o ${tmpdir}/${basename}`, etc.

It will be better

**Comment by ouuan** [comment]
> > What about making the compile command and the run command completely customizable? i.e. Let the user add `-o ${tmpdir}/${basename}`, etc.
> 
> It will be better

I just realized that in this way the user needs to set the path of the executable file twice, which is not good :thinking:
