### ISSUE TITLE
open a window when checking for updates

### ISSUE THREAD

**Issue by StudyingFather** [cpeditor/cpeditor#361]
**Is your feature request related to a problem? Please describe.**

When I click "check for updates", all I can do is to wait for results.

If I can not connect with the Github server, I can not get any response about this situation.

**Describe the solution you'd like**

1. Open a window when checking for updates so that I know the update checker is working. And if possible I can close the window to terminate the update check.
2. Add a timeout. If the checker do not get response within the timeout, show the error message.

**Describe alternatives you've considered**

**Additional context**

**Comment by coder3101** [comment]
In addition to it we can also show changelog of new update as well.

**Comment by coder3101** [comment]
I am working on this. Just to let others not work on the same Issue.
