### ISSUE TITLE
UI Localization

### ISSUE THREAD

**Issue by neko-para** [cpeditor/cpeditor#377]
Having native language is quite important for beginners. It's worthy to add more UI languages.

We can use Qt's solutions to support different locale.

**Comment by neko-para** [comment]
I've done some tests and found that ```tr``` works well with the preferences window. So there won't be any technical problems.

**Comment by coder3101** [comment]
This would be really great. Maybe you could start the process and keep a draft PR and we all can write the translation for our locale. 

I am not familiar with how "tr" works and in General, your draft PR would significantly help us through it.

I am assigning this to you!

**Comment by coder3101** [comment]
Having these three Languages will be good:

- English (current)
- Chinese (any variation you all agree to)
- Russian (with help of @sadykhzadeh)

**Comment by neko-para** [comment]
There is a problem. Some window use ui file, and I can use ui->retranslate to update text after changing language. But Some windows are (partly) generated(e.g. testcases, preference window), and it's not easy to update all their text.
After all, we can ask user to reopen the program to apply the new language, which won't be a bad idea.

**Comment by ouuan** [comment]
Personally, I'll leave the translation job for other (new) contributors. This is easy for them and not very interesting for me :thinking:. We need to prepare a new-comer-friendly environment for translation.

**Comment by coder3101** [comment]
@ouuan Release and CI, overall complete CI structure need some changes before translation can be done by new contributer, that is what his draft PR should do.

**Comment by neko-para** [comment]
Now what should translators do is to use linguist to update the ts files under the ```translations``` directory.
