### ISSUE TITLE
failed to compile code

### ISSUE THREAD

**Issue by animesh9455** [cpeditor/cpeditor#382]
when u try to compile and run the code compiler fails and says failed to compile the code and doesnt run and my compiler is working fine
![Screenshot (51)](https://user-images.githubusercontent.com/39373901/83492321-be3c5800-a4d0-11ea-8626-e3daec44a339.png)

**Comment by coder3101** [comment]
Do you use any antivirus software?

**Comment by ouuan** [comment]
Can you click Options->Show Log Files and upload the log file?

**Comment by animesh9455** [comment]
No only window defender

**Comment by animesh9455** [comment]
log files
![Screenshot (52)](https://user-images.githubusercontent.com/39373901/83496139-483aef80-a4d6-11ea-8de2-ee0824bdd713.png)

**Comment by coder3101** [comment]
Follow these steps:

- Close the CP Editor if running
- Launch again
- Type some minimal code that is failing to run
- Click Options->Show Log Files
- A File will be selected (usually last file in the list)
- Upload that file here, you can drag drop it into comment box, it will upload it.

**Comment by animesh9455** [comment]
I think window defender was blocking log files as they were listed as virus in it so i removed them from there and now it seems to be working fine

**Comment by coder3101** [comment]
So, it is fine now, working as expected?

**Comment by animesh9455** [comment]
I ll see if after clearing log files will it work the same way

**Comment by animesh9455** [comment]
@coder3101 Window defender was not allowing it to run properly i think and it seems its been fixed for now.

**Comment by coder3101** [comment]
If you get the same error as mentioned in the description of the issue, it is due to your antivirus blocking `exe` from running, Add it to Exceptions or save the file before compiling and running. An unsaved file `exe` is produced inside %TEMP% directory and it might trigger antivirus to blocking them.
