### ISSUE TITLE
CP Editor的提交按钮在哪里哈

### ISSUE THREAD

**Issue by zhk1211** [cpeditor/cpeditor#383]
CP Editor的提交按钮在哪里哈

![360截图16491216789794.png](https://i.loli.net/2020/06/02/CwjRYitKzfnq9Zo.png)

**Comment by zhk1211** [comment]
https://i.loli.net/2020/06/02/CwjRYitKzfnq9Zo.png

**Comment by ouuan** [comment]
请阅读 https://github.com/cpeditor/cpeditor/blob/master/README_zh-CN.md#faq

**Comment by ouuan** [comment]
哦，你用的是 codeforces.ml，暂未支持

**Comment by ouuan** [comment]
在 #212 完成后就可以使用镜像以及部分其它 OJ 了。

**Comment by zhk1211** [comment]
> 哦，才发现你用的是 codeforces.ml，暂未支持

哦，原来如此
