### ISSUE TITLE
False external file change when auto-save is enabled

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#392]
**Describe the bug**

When auto-save is enabled, sometimes a false alert of external file change is shown.

**To Reproduce**

I haven't figured out how to reproduce it yet.

**Environment**

 - OS: Arch Linux with KDE
 - CP Editor Version: 6.5.1

**Additional context**

I'll try to find a way to reproduce it. Everyone who has ever met this can confirm it and it will be better if someone knows how to reproduce it.

**Comment by sonulohani** [comment]
I couldn't able to reproduce this. I am using manjaro 20.01 gnome edition.

**Comment by ouuan** [comment]
It nearly always happens when the auto-save interval is very small.

**Comment by ouuan** [comment]
I figured out what happened: it takes time to save the file, and during the auto-save the application is not blocked since it's started by the timer, and I guess the timer is in a different thread. So, we can change the document during the auto-save, and when the file is finally auto-saved, the document and the file are not the same, which causes the external file change.
