### ISSUE TITLE
Test cases with no inputs

### ISSUE THREAD

**Issue by tb148** [cpeditor/cpeditor#408]
**Is your feature request related to a problem? Please describe.**

Sometimes I will write some code that outputs without inputs. However the runner refuses to run if no input is provided.

**Describe the solution you'd like**

Also run the code if no inputs provided.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by ouuan** [comment]
We can make this optional in the settings.

**Comment by ouuan** [comment]
As for now, you can add an arbitary input, or click the "Run" button beside the test case.

**Comment by ouuan** [comment]
@allcontributors add @tb148 as a contributor for the idea.

**Comment by tb148** [comment]
This might be caused by this line:
https://github.com/cpeditor/cpeditor/blob/bdf2d29998a78d22b72fb7d84a477d0a8b1a9af5/src/mainwindow.cpp#L171

**Comment by ouuan** [comment]
> This might be caused by `!testcases->input(i).trimmed().isEmpty()` in this line:
> 
> https://github.com/cpeditor/cpeditor/blob/bdf2d29998a78d22b72fb7d84a477d0a8b1a9af5/src/mainwindow.cpp#L171

Yes, exactly. Hopefully, you can propose a pull request to add this option. However, we don't want to totally change the old logic, so we need a setting for this. To add a new setting, you need to modify `src/Settings/settings.json` and `src/Settings/PreferencesWindow.cpp`.

**Comment by tb148** [comment]
> 
> 
> As a substitute, I simply give input 0 in input box and my code with no input needed runs perfectly.
> :)

This is just what @ouuan said:


> 
> 
> As for now, you can add an arbitary input, or click the "Run" button beside the test case.

**Comment by coder3101** [comment]
@neko-para  It was assigned to me but you worked on it. It does not matter for small issues like this, but it is better for all of us to ask for the assigned person before taking their Issue, maybe the assignee has solved already and another person is working on the same thing twice again.

**Comment by neko-para** [comment]
@coder3101 I'm sorry for that. I noticed the assignee but forget to ask. I won't do it any more.
