### ISSUE TITLE
Re-sizable individual input and output windows

### ISSUE THREAD

**Issue by lakshits11** [cpeditor/cpeditor#414]
**Is your feature request related to a problem? Please describe.**
Yes..

**Concise description of what the problem is**.
I think there should be re-sizable input and output windows since many times i have to swipe my mouse to right to see the complete output.

**Describe the solution you'd like**
So if there were individually re-sizable output window, this would really a great help and will save time a lot.

**Comment by ouuan** [comment]
I've tried some implementations but they all failed with no luck. I'll mark this with low priority until someone provides a good implementation.

I think an alternative solution is to let the user set the maximum height of a test case, which is hardcoded as 300px now.

**Comment by coder3101** [comment]
Another idea would be to have a separate window to view or edit testcase.

 Currently we do have a option if you right click "Edit in big window" but that only applies to Edit for testcases. 

I think we should add an option (per test basis), called "Expanded Mode", when clicked a new window launches with Input, Ouput, Expected. It should update in real-time for changes in Testcase, should always be on Top of Editor. 

I think no matter what solution we find for this issue the expanded size of one one widget will take from size of other widgets. 

In general not all testcases will be Big, so not too many windows will be there! Finally with this we can get rid of "Edit in big window" option as well.

**Comment by ouuan** [comment]
As discussed in #190, what could you get from manually reading a big input?

**Comment by ouuan** [comment]
Maybe it's helpful to make the horizontal sizes of input/output/expected resizable :thinking:

**Comment by coder3101** [comment]
> As discussed in #190, what could you get from manually reading a big input?

It is not for reading big testcases manually, the point is to create a new window with just say `#1` Input, Output, Expected. It updates in real-time as code is recompiled and ran.

**Comment by lakshits11** [comment]
The idea to manually set width of each windows will be best according to me.Because your current layout is great and in competitive programming this will be ok.

**Comment by ouuan** [comment]
> since many times i have to swipe my mouse to right to see the complete output

I didn't notice this. I was thinking of the heights.

**Comment by lakshits11** [comment]
> > As discussed in #190, what could you get from manually reading a big input?
> 
> It is not for reading big testcases manually, the point is to create a new window with just say `#1` Input, Output, Expected. It updates in real-time as code is recompiled and ran.

Wouldn't it be messy to manually switch to other window to see output?? Please clear me.

**Comment by ouuan** [comment]
> Wouldn't it be messy to manually switch to other window to see output?

I agree.

I think it's good to make the width resizable, and make the maximum height customizable.

**Comment by coder3101** [comment]
Width can be resized, but again are you willing to loose the width of one of your other widget like "Input or Expected" input boxes.

**Comment by coder3101** [comment]
Because you will have to again resize stuff if you wish to edito tescase (which can be big) again resize to see it's output (which can be big).

It's a trade-off and depends on your usecase!

**Comment by ouuan** [comment]
> i have to swipe my mouse to right to see the complete output

Do you think it's good to use the Diff Viewer (click the `**`/`AC`/`WA`)?

**Comment by ouuan** [comment]
@allcontributors add @lakshits11 as a contributor for ideas.
