### ISSUE TITLE
Refactor Settings to support more types

### ISSUE THREAD

**Issue by neko-para** [cpeditor/cpeditor#417]
**Is your feature request related to a problem? Please describe.**
To support custom language, many setting will be changed. Currently the snippets and editor status are load manually. But these could be loaded automatically, and more settings like these will be introduced to support custom language. So it's better to make the current settings manager able to handle these.

**Comment by ouuan** [comment]
I think this is finished? Next time you can use "fixes/closes" instead of "related issue".
