### ISSUE TITLE
[You will not be able to submit code to Codeforces because CFTool is not installed or is not on SYSTEM PATH. You can set it manually in settings.]

### ISSUE THREAD

**Issue by sinnersneversleep** [cpeditor/cpeditor#418]
C:\~\Downloads\cf_v1.0.0_windows_64\cf_v1.0.0_windows_64 this is what i have given in the systems path is there any problem. I keep getting this error however sometime it works after changing the cf tools settings to default. but lot of times during contest i get this issue.

I am very thankful to you for creating this wonderful editor

**Comment by coder3101** [comment]
Goto settings and Set CF Path to full path to CF.exe like

`C://Users/Myname/Downloads/sundor/inside/cf.exe`

Use full path, sometimes PATH Variables to download folder doesn't loads properly.

**Comment by coder3101** [comment]
Close this issue if the above mentioned comment fixes your problem.

**Comment by sinnersneversleep** [comment]
Hi, however i was using full path only. but when i read your blog again you mentioned to put cf.exe in Users/bin and that suggestion worked. so the issue is resolved thanks again for this wonderful contribution.
