### ISSUE TITLE
Save session as a file

### ISSUE THREAD

**Issue by tuwuna** [cpeditor/cpeditor#437]
**Is your feature request related to a problem? Please describe.**

The current way of handling session doesn't work in all cases

For example, it cannot restore the previous session if it is a force-ful shut down

**Describe the solution you'd like**

Like the title, save session as a file

![](https://cdn.discordapp.com/attachments/686387177902702626/724240183003709460/unknown.png)

**Comment by ouuan** [comment]
I think the point is to save the session periodically, save it as a separate file is just an implementation.

However, saving the session as a separate file has some benifits, for example, if you want to export the settings, you probably don't want to export the session.

**Comment by coder3101** [comment]
This is basically "Hot Exit" but periodically invoked instead of just at closing of the editor. If we want we can make hot exit be saved in a separate file. We can call that file `cp_editor_session`.
