### ISSUE TITLE
OpenSSL is not deployed, so it's not able to check for updates with the binary releases

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#449]
**Describe the bug**

Can't check for updates with the binary releases.

**To Reproduce**

1. Download a binary release.
2. Run it.
3. Check for updates.
4. Get "TLS initialization failed".

**Screenshots**

![image](https://user-images.githubusercontent.com/30581822/85647012-0b76a880-b6d0-11ea-9170-720f2442b194.png)

**Environment**

Tested on both Arch Linux and Windows 10.

I believe we've never deployed OpenSSL, so the bug has been there since the update checker was added.

**Additional text**

On Windows, we can fix it by copying `Qt/Tools/OpenSSL/Win_x64/bin/*.dll` into the executable file directory.

**Comment by ouuan** [comment]
It seems that we shouldn't deploy OpenSSL because it's a security-related library.

And on Arch Linux, we can solve it by installing `openssl-1.0`.

**Comment by ouuan** [comment]
Maybe we should add a friendly error message to guide the user to install the compatible OpenSSL manually.

**Comment by Ravenclaw-OIer** [comment]
@ouuan It  seems that openssl-1.0 is deprecated and cannot be installed easily on ubuntu. It is 1.1.1f-1ubuntu2 on my machine.

**Comment by ouuan** [comment]
> @ouuan It seems that openssl-1.0 is deprecated and cannot be installed easily on ubuntu. It is 1.1.1f-1ubuntu2 on my machine.

Can you check updates with the AppImage?

**Comment by Ravenclaw-OIer** [comment]
@Ravenclaw-OIer Yes

**Comment by ouuan** [comment]
https://wiki.qt.io/Qt_5.15.0_Known_Issues#OpenSSL

It seems that bundle OpenSSL with the application might have some legal issues :thinking:
