### ISSUE TITLE
Issue in compiling cpp code.

### ISSUE THREAD

**Issue by Suyash-leo** [cpeditor/cpeditor#450]
**Describe the bug**
When i try to compile the code, the message says that ["Compilation has started"], but it stays stuck there for about 10 mins after which i may or may not get the code compiled i.e. i have to kill the compilation and start again. But the result can still be the same.

**To Reproduce**
write a cpp code. put in a sample test case and click on the compile and run button.

**Screenshots**
It can be seen clearly in the screenshot attached that my code took around 20 minutes to compile.
![Screenshot (5)](https://user-images.githubusercontent.com/55657523/85686850-f446b380-b6ed-11ea-96ce-8142c02d19a9.png)

**Environment**
O.s.- Windows 10
CP editor version- 6.3.4

 - OS: [e.g. Windows 10 / Ubuntu 18.04]
 - CP Editor Version: [e.g. 6.0.2]

**Additional context**

**Comment by coder3101** [comment]
Share your Settings: `Language -> C++ -> Compiler Commands`

**Comment by Suyash-leo** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/55657523/85692206-d760af00-b6f2-11ea-9a48-5ad02c8132e6.png)

**Comment by ouuan** [comment]
How long does it take to compile in the cmd?

**Comment by Suyash-leo** [comment]
It compiles fine in cmd, like it takes a few seconds only.

**Comment by Suyash-leo** [comment]
Here are the log files after reproducing the issue.
[cpeditor-2020-06-25-16-53-40-614-0.log](https://github.com/cpeditor/cpeditor/files/4830951/cpeditor-2020-06-25-16-53-40-614-0.log)

**Comment by Suyash-leo** [comment]
I would like to add that the editor takes a long time only in the first compilation of a code, i.e. once it has taken around 10-20 mins to compile, it starts compiling the code immediately after that.

**Comment by ouuan** [comment]
Can you turn off all anti-virus software and test again?

**Comment by Suyash-leo** [comment]
Im using guardian netsecure. It doesnt have an option to be turned off but I can add an exclusion for cp editor. I have to mention the file extension that has to be excluded. What file type should i mention there?

**Comment by coder3101** [comment]
The first compilation on my windows is also slower as compared to subsequent compilation. It could be because OS caches the compiler in RAM and is able to quickly load and compile, as compared to first time where it loads compiler from disk.

Still The time is never 10-20 min, usually 2-3 sec for first and subsequently <1 sec on M2 NvME drive. On my other machine with SATA SSD, first compilation takes around 7-8 sec, subsequent compilation is 1 sec. 

I do not have HDD to test the timing but it shouldn't be 10 min for sure, maximum 10 sec is acceptable.

*Tested by compiling same source after a fresh cold boot in latest stable CP Editor*

**Comment by coder3101** [comment]
> Here are the log files after reproducing the issue.
> [cpeditor-2020-06-25-16-53-40-614-0.log](https://github.com/cpeditor/cpeditor/files/4830951/cpeditor-2020-06-25-16-53-40-614-0.log)
> 

This Log is too long and isn't very clear. 

We updated log system to generate better logs with latest versions. Optionally, Can you please update to latest stable. So we can get better logs. You should follow these steps to generate clear logs.

1. Close all tabs
2. Close application
3. Launch App
4. In the new tab (opened by default)
5. Write a simple program (add 2 numbers)
6. Add a Testcase 
7. Hit 'Compile and Run' (Note long time if it takes long times)
8. Options->Show Logs
9. Upload log here!

**Comment by coder3101** [comment]
Remove 

`#include<bits/stdc++.h>`

Do do this. Include only those files you want to use. You include way too much things than you use this way!

**Comment by ouuan** [comment]
The latest stable version and the latest beta version both provide an option to choose where to store the executable file, can you update CP Editor and set the executable file path to `${basename}` and test again?

**Comment by neko-para** [comment]
> Remove
> 
> `#include<bits/stdc++.h>`
> 
> Do do this. Include only those files you want to use. You include way too much things than you use this way!

Actually, many of competitors use this headers, as it provides a very simple way to include files. This won't cause the compilation too slow. However, it does lead to slow linting.

**Comment by coder3101** [comment]
> Actually, many of competitors use this headers, as it provides a very simple way to include files. This won't cause the compilation too slow. However, it does lead to slow linting.

I know, it does slows down the time for compilation. Because `#include<something.h>` means replace this line with content of `something.h`. You if you include whole of standard library with that header, the final text that compiler has to compile becomes in millions of line. 

In subsequent compilation it doesn't happen because of pch (pre compiled headers) are used instead of re parsing whole thing.

**Comment by coder3101** [comment]
I think if you remove `#include<bits/stdc++.h>`, your first compilation speed will be significantly reduced. 

If that fixes your issue! Close this issue, upon no reply in 24 hours. We will close it.

**Comment by coder3101** [comment]
Closed: No response from OP
