### ISSUE TITLE
Things to check before releasing v6.6

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#454]
A checklist before releasing v6.6:

- [x] ~~Wait for the [PPA](https://launchpad.net/~beineri) for Qt 5.15.~~
- [x] Run a release in a fork, and check whether the AppImage ~~and the portable version~~ is correctly built.
- [ ] Check whether the SSL version in the warning of SSL library missing is correct. (Should be 1.0.X because it's built on Ubuntu 16.04)
- [x] Solve all issues on the website with milestone 6.6. See the list [here](https://github.com/cpeditor/cpeditor.github.io/issues?q=is%3Aissue+is%3Aopen+milestone%3Av6.6)

**Comment by coder3101** [comment]
It can be delayed a lot since upto now, 5.15.0 is only available under focal (20.04).

**Comment by coder3101** [comment]
Updated the Checklist

**Comment by ouuan** [comment]
After many tries, I finally managed to make the AppImage with the Qt installed by aqtinstall. The release is [here](https://github.com/ouuan/cpeditor/releases/tag/aqtinstall-qmake-test-6).

However:

1.   The portable version is not working because the `QCoreApplication::applicationDirPath()` of an AppImage is something like `/tmp/.mount_cpeditmfakMr`.
2.   I can't test the OpenSSL warning on my Arch Linux. I don't know why but the update checker is working even if I uninstalled `openssl-1.0`.

**Comment by ouuan** [comment]
I'm wondering whether Linux and Mac users really need a portable version :thinking: Now the portable version on Linux and Mac only saves the settings file in the same path as the executable file, but the user can export and import settings instead.

So I suggest providing the portable version on Windows only.

@neko-para What do you think?

**Comment by neko-para** [comment]
It may not be so important. If AppImage performs well, we can remove the portable version support to non-windows system.

**Comment by coder3101** [comment]
https://github.com/cpeditor/cpeditor/pull/510#issuecomment-660754115_

**Comment by ouuan** [comment]
The SSL version check is not very important :thinking: I think everything is fine now.
