### ISSUE TITLE
Use the class name as the name of the temporary file of Java

### ISSUE THREAD

**Issue by neko-para** [cpeditor/cpeditor#459]
**Describe the bug**
Currently, the option `Java Class Name` only changed the run command but not change the temp source filename. However, javac would fail if the source name isn't the same as the class name in the source. So when compiling java source, the program copy the source as `$tempdir/sol.java`, which forced user name the class `sol`. Meanwhile, if the `Java Class Name` isn't `sol`, the run command would fail either.

**To Reproduce**
* Write a simple java program with class called Main.
* Compile

**Environment**
 - OS: Windows 10
 - CP Editor Version: 6.6.0/master

**Additional context**
Use openjdk 8 from redhat.

**Comment by ouuan** [comment]
Actually, we were asking the user to use a non-public class. However, I just tested and found that the main class must be public to be submitted to Codeforces.

**Comment by ouuan** [comment]
Maybe it's better to always save `classname.java` in the temporary directory.

**Comment by neko-para** [comment]
I'm not sure about it. I get some sources from others and want to test them, and I find this problem. I don't know how java coders think about it.

**Comment by ouuan** [comment]
The request for using a non-public class has been there before I knew CP Editor, and since I don't use Java, I haven't considered that before.

**Comment by neko-para** [comment]
@coder3101 How do you think about it?

**Comment by coder3101** [comment]
Since, I don't use Java I did not tested by submitting to CF that public class is required.

We can add an option allow user set the name of class.

**Comment by neko-para** [comment]
We have an option "Java Class Name", but it causes problem. Actually I don't know why do we name the temp source `sol.$suffix`. I think at least it should be the same as the real name. And I think it's ok to compile the origin source directly, so why do we copy sources?

**Comment by ouuan** [comment]
> And I think it's ok to compile the origin source directly, so why do we copy sources?

The main reason is to make the logic more clear. See #357 for details. It also makes it easier to fix this (#459) issue.

**Comment by ouuan** [comment]
> Actually I don't know why do we name the temp source `sol.$suffix`. I think at least it should be the same as the real name.

Because we need a name for untitled tabs, and if we use the actual file name for titled tabs, there will be more codes without any benefits.

**Comment by coder3101** [comment]
When multiple tabs of java are opened with the same public class name. If one is compiled the compiled bytecode of other class will be over-ridden, requiring a re-compilation. This is not the case with C++ or python since they are suffixed with numbers, so each is separate. So, We made it non-public class.

**Comment by coder3101** [comment]
Furthermore, it is very difficult to identify which .class belongs with which tab. Since all tabs will create one .class file.

If we make the class name as a temporary file path. How do you deal with spaces? If only competitive companion parser can guarantee that parsed problem id/name does not contain spaces.

**Comment by ouuan** [comment]
> If one is compiled the compiled bytecode of other class will be over-ridden, requiring a re-compilation. This is not the case with C++ or python since they are suffixed with numbers, so each is separate.

The temporary directory of each tab is separated. You are describing the situation before #106 when we were using [BaseFiles](https://github.com/cpeditor/cpeditor/blob/fcbc8ea125da080290b6de60014a8e23fe8edd6b/include/BaseFiles.hpp).

**Comment by coder3101** [comment]
It's fine then!

**Comment by ouuan** [comment]
> If we make the class name as a temporary file path. How do you deal with spaces?

A valid class name must be a valid file name, and if the name of the temporary file is invalid, there will be a message "failed to open temporary file".
