### ISSUE TITLE
QWizard for Opening Contest

### ISSUE THREAD

**Issue by coder3101** [cpeditor/cpeditor#467]
**Is your feature request related to a problem? Please describe.**
A new contest is created using "Open Contest" menu option and it launches the Directory picker followed by a Number Input dialog followed by a QCombo box for language selection. This sequencial flow can be better managed and be made verbose with a [QWizard](https://doc.qt.io/qt-5/qwizard.html)

**Describe the solution you'd like**

Open a QWizard for choosing all Contest-related parameters.

**Describe alternatives you've considered**

Use plain old style

**Additional context**

![image](https://user-images.githubusercontent.com/22212259/86143593-3f0f6380-bb12-11ea-903c-e69141ff6be9.png)

See a small and ugly number picker.

**Comment by ouuan** [comment]
I think they can be a single page (a custom widget) instead of a `QWizard` :thinking: I used three dialogs for convenience, and I thought it's good enough.

**Comment by coder3101** [comment]
Wizard can be of a single page. Like, "Create new C++ file" wizard has one page only to select name of header and source and the directory.

**Comment by ouuan** [comment]
I know a `QWizard` can be of a single page, but how is it better than a normal widget?

> A wizard (also called an assistant on macOS) is a special type of input dialog that consists of a sequence of pages. A wizard's purpose is to guide the user through a process step by step. Wizards are useful for complex or infrequent tasks that users may find difficult to learn.

**Comment by coder3101** [comment]
It is the same thing, implementing via QWizard will be easy and by custom widget, it will be relatively difficult. I favour both ways.
