### ISSUE TITLE
Submit to all judges

### ISSUE THREAD

**Issue by Salil03** [cpeditor/cpeditor#472]
**Is your feature request related to a problem? Please describe.**

Currently cpeditor only supports submitting solutions to codeforces

**Describe the solution you'd like**

You can use https://github.com/online-judge-tools/api-client to submit solutions to many websites. This will make submitting solutions quicker. List of supported judges is here: https://github.com/online-judge-tools/oj

**Describe alternatives you've considered**

You can also use https://github.com/online-judge-tools/oj 

**Additional context**

This will take care of #212

**Comment by ouuan** [comment]
Why did you open this if you knew #212 is there :thinking:

**Comment by ouuan** [comment]
I don't think built-in submit can be better than custom command.

**Comment by ouuan** [comment]
You can see the reasons 2. and 3. in #212.

> 2. Users may use mirrors like <https://codeforc.es/> for Codeforces, now they are forced to use <https://codeforces.com>.
>
> 3. Users have no way to fix bugs caused by external API changes like #194 by themselves.

They can't be fixed by built-in submit.
