### ISSUE TITLE
Allow user to excute other programs

### ISSUE THREAD

**Issue by neko-para** [cpeditor/cpeditor#478]
We can add a menu entry and allow user add items under it. Each item links to a certain command. The command should also support variables like `basename`, `filename`, etc.

This feature will partially solve #17, which allows user to excute gdb/gdbgui in the cpeditor.

**Comment by ouuan** [comment]
Do you mean <https://github.com/cpeditor/cpeditor/issues/17#issuecomment-590174110>? Is it helpful to enable this for things other than debugging?

**Comment by neko-para** [comment]
Yes, this is the reason I add this issue. But I think this feature could be useful in other aspects.

**Comment by coder3101** [comment]
Related to #638
