### ISSUE TITLE
Use Qt Property System to refactor settings.

### ISSUE THREAD

**Issue by neko-para** [cpeditor/cpeditor#485]
We can deal settings with two levels.
Level1: class SettingsManager, which loads all settings but doesn't perform any checks.
Level2: class Settings, which is generate by scripts. object setting, created by SettingsManager and filled values and provide default values.
The class Settings may have some child object.

As the Qt Property System is quite powerful, I believe it's not hard to make PageTemplate support them. But some refactor is also needed to support Object type. Currently, I think it's better to make template page a widget, so that it can nest itself, which is necessary when showing Object.

**Comment by ouuan** [comment]
I'm not sure how Qt Property System is better exactly :thinking:

**Comment by neko-para** [comment]
The script add sth. like `Q_PROPERTY(QFont EditorFont MEMBER EditorFont)` and `QFont EditorFont`, and then we can enum entries, read, write and so on.
I'm still testing which is better. I'll write a sketch.

**Comment by neko-para** [comment]
We can use Q_DECLARE_METATYPE to add the info structure, and then we can set it as a property as well. Then SettingsInfo is not needed.

**Comment by ouuan** [comment]
I know we can use Qt Property System to do the things we already can do now, but how is it better?

**Comment by neko-para** [comment]
After all, I don't know how to extend current system to support Object.

**Comment by neko-para** [comment]
This is just a test. Maybe it becomes more complex. But I still want to have a try.

**Comment by ouuan** [comment]
I searched about Qt Property System, and don't think it's suitable (I mean, not better than our current implementation) for storing settings. It's for communication between different classes, and communication between C++ and QML (for example, you can change the properties in Qt Designer).

**Comment by neko-para** [comment]
But at least it provides reflection, which is need in loading & saving settings. And when upgrading the PageTemplate, I believe it 
will help a lot.

**Comment by neko-para** [comment]
Of course, we could do all things with the current system, but I think the property system will be a better choice.

**Comment by ouuan** [comment]
> Of course, we could do all things with the current system, but I think the property system will be a better choice.

I thought we could do all things with Qt Property System, but the current system was a better choice.

> But at least it provides reflection, which is need in loading & saving settings.

What's reflection?

> And when upgrading the PageTemplate, I believe it will help a lot.

I've no idea how. You can either explain why the Qt Property System helps, or write the codes first.

**Comment by neko-para** [comment]
I'm writing code.
The reflection, means querying, modifying, enumerating object itself.

**Comment by neko-para** [comment]
I've write some codes. I think using the property system make it easy to duplicate settings. It allows us to create multiple settings environment.

**Comment by neko-para** [comment]
All settings are stored in a single object, and it's ok to simply copy them. This would be useful in PageTemplate
