### ISSUE TITLE
Runner not working

### ISSUE THREAD

**Issue by codingiitg** [cpeditor/cpeditor#493]
**The Bug:**
On clicking Compile and Run, the program is getting compiled but the runner is prompting that it has failed to run the file and tells to "please compile first".

**Screenshots**
![image](https://user-images.githubusercontent.com/21168393/87007256-95019c80-c1df-11ea-8228-df037bd9593a.png)

**Environment**

 - OS: Windows 10
 - CP Editor Version: 6.5.2
 - Compiler Version: g++ 5.1.0

**Additional context**

The Problem is getting submitted without any error. But it is not running.

**Comment by codingiitg** [comment]
This is the log file for reference.

[cpeditor-2020-07-09-12-33-30-153-0.log](https://github.com/cpeditor/cpeditor/files/4895071/cpeditor-2020-07-09-12-33-30-153-0.log)

**Comment by ouuan** [comment]
According to the log file, your setting "C++/Output Path" is empty, which shouldn't be. You can set it to the default value `${tmpdir}/${basename}`.

Do you remember you have changed this setting?

**Comment by codingiitg** [comment]
Thank you, it has been resolved.
