### ISSUE TITLE
Pressing tab will not move string

### ISSUE THREAD

**Issue by sonulohani** [cpeditor/cpeditor#498]
**Describe the bug**

Please see the gif attached with this issue.

**Environment**

 - OS: Windows 10 2004
 - CP Editor Version: Latest master

![bug](https://user-images.githubusercontent.com/2958681/87240854-e6599800-c43a-11ea-9de5-e3f379d61f8c.gif)

**Comment by ouuan** [comment]
It's an optional feature (#256).

**Comment by ouuan** [comment]
Do you think it should be disabled by default? I think it's rare that a closing parenthesis is at the beginning of a line, and you press Tab at the beginning of that line. How did you discover this?

**Comment by sonulohani** [comment]
Hi @ouuan 
 I was formatting the code to see how indentation look when I split the line into multiple. The problem right now is that if i press enter before the string in our above example it doesnt provide indentation by default which is lacking. So when i pressed tab, instead of moving the string it was moving the content inside double quotes.
