### ISSUE TITLE
Support compile_commands.json or compile_flags.txt for clangd

### ISSUE THREAD

**Issue by tb148** [cpeditor/cpeditor#501]
**Is your feature request related to a problem? Please describe.**

Clangd does not work well since I don't have Visual Studio, and I can't set compile_commands.json or compile_flags.txt to use mingw-w64.

**Describe the solution you'd like**

Allow users to customize compile_commands.json or compile_flags.txt.

**Describe alternatives you've considered**

Ask users to download Visual Studio.

**Additional context**

https://stackoverflow.com/questions/39871656/how-to-use-clang-with-mingw-w64-headers-on-windows/47148323#47148323

**Comment by ouuan** [comment]
How do you set `compile_commands.json` without CP Editor? Does it need to be in the same/parent directory of the source file like `.clang-format`?

**Comment by coder3101** [comment]
From Clangd-9 Manual, See `man clangd`.

> clangd compilation flags options:
>
> --compile-commands-dir=<string> - Specify a path to look for compile_commands.json. If path is invalid, clangd will look in the current directory and parent paths of each source file

We do provide you with setting arguments for clangd. Doesn't that worked for you? Or did you missed this? I think that the same argument will be acceptable in windows.

**Comment by coder3101** [comment]
From Additional Information

You can compile your code without msvc using clang and mingw, by setting following C++ compiler command.

`clang++ -target x86_64-pc-windows-gnu`

**Comment by tb148** [comment]
> 
> 
> From Clangd-9 Manual, See `man clangd`.
> 
> > clangd compilation flags options:
> > --compile-commands-dir= - Specify a path to look for compile_commands.json. If path is invalid, clangd will look in the current directory and parent paths of each source file
> 
> We do provide you with setting arguments for clangd. Doesn't that worked for you? Or did you missed this? I think that the same argument will be acceptable in windows.

Thanks, closed because resolved.
