### ISSUE TITLE
CP editor is crashing

### ISSUE THREAD

**Issue by sonulohani** [cpeditor/cpeditor#503]
**Describe the bug**

Segmentation fault due to nullptr

**To Reproduce**

Build the project in linux mint and launch. BOOM the software crashes!!!! 

**Environment**

 - OS: Linux mint 20
 - CP Editor Version: latest master
**Additional context**

I debugged and saw that the `QVariantMap *SettingsManager::cur` is nullptr which means its not got initialized. 

![image](https://user-images.githubusercontent.com/2958681/87441359-a3e9b400-c610-11ea-82c8-446bf90b9a27.png)

**Comment by coder3101** [comment]
![image](https://user-images.githubusercontent.com/22212259/87447275-02666080-c618-11ea-882e-b0d8703b3130.png)

This builds fine on windows.

**Comment by coder3101** [comment]
> Environment
>
>  -  OS: Linux mint 20
>  -  CP Editor Version: latest master
>  -  Additional context

Version should be a git hash. `latest master` is always changing.

**Comment by sonulohani** [comment]
I am able to reproduce this issue. I can share the video if you want

**Comment by coder3101** [comment]
This crash is related with `Settings`. Could you please re/move your config from `~/.config/CP Editor/cp_editor_settings.ini`. This will force editor to use default values for all settings.

**Comment by sonulohani** [comment]
But no folder is created for cp editor in config folder. 

Could you please tell me where are we initializing the  `QVariantMap *SettingsManager::cur` pointer.

**Comment by coder3101** [comment]
> 
> 
> I am able to reproduce this issue. I can share the video if you want

The tag "can't reproduce" does mean "Issue doesn't exists", it simply mean the one who tagged it was not able to reproduce it. If any maintainer is able to reproduce the issue, they will remove it.

**Comment by coder3101** [comment]
> Could you please tell me where are we initializing the `QVariantMap *SettingsManager::cur` pointer

@ouuan and @neko-para made maintain the stuff inside `Core/Settings`. I have absolutely Zero contribution in that directory. They will help you better or maybe you can figure it out yourself.

**Comment by sonulohani** [comment]
> > I am able to reproduce this issue. I can share the video if you want
> 
> The tag "can't reproduce" does mean "Issue doesn't exists", it simply mean the one who tagged it was not able to reproduce it. If any maintainer is able to reproduce the issue, they will remove it.

Got it.

**Comment by ouuan** [comment]
> Could you please tell me where are we initializing the `QVariantMap *SettingsManager::cur` pointer.

https://github.com/cpeditor/cpeditor/blob/32aa633d620b116eb24438fee911f8b70024d0d2/src/Settings/SettingsManager.cpp#L116

Can't reproduce it, and no one reported this before. Since it's a critical bug, it's not likely that no one has noted it yet. Can you provide more info like the log file?

**Comment by neko-para** [comment]
@sonulohani Do you add any more querying or modifying actions to the code? It seems that you try to use setting before initialize it.

**Comment by sonulohani** [comment]
> @sonulohani Do you add any more querying or modifying actions to the code? It seems that you try to use setting before initialize it.

I didn't do any changes to the code. I will upload video.

**Comment by sonulohani** [comment]
Hi @ouuan , @neko-para 

Here is the video of the issue:- https://vimeo.com/user5679921/review/438448239/5f31c8104b

**Comment by ouuan** [comment]
I can confirm it happens when there's no settings file on the disk. It's introduced in https://github.com/cpeditor/cpeditor/commit/d9d90f589f26738acd84ea1544c1f4bc3cc24e01#diff-83b965effe1043e05e93813b06ccbe42R45-R46.

**Comment by ouuan** [comment]
We can fix it by simply deleting `if (!path.isEmpty())`, but I think it's better to make loading settings and generating default settings separated. I think the confusing function name is the cause of this mistake.

**Comment by sonulohani** [comment]
@ouuan  That was quick.
