### ISSUE TITLE
please add New File option in File menu

### ISSUE THREAD

**Issue by HurayraIIT** [cpeditor/cpeditor#508]
**Is your feature request related to a problem? Please describe.**

when solving random problems I need to create a new file from terminal and then go to CP Editor to open it. There is no option to create a new file from within CP Editor.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ouuan** [comment]
There is. It was "New Tab", has been renamed to "New File" and will be released in v6.6.

**Comment by ouuan** [comment]
You have to save the untitled tab to actually create a new file.
