### ISSUE TITLE
The background color of the diff viewer is black on Windows with Dark Fusion theme

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#519]
**Describe the bug**

The background color of the diff viewer is black on Windows with Dark Fusion theme.

**To Reproduce**

Open the diff viewer.

**Screenshots**

![image](https://user-images.githubusercontent.com/30581822/88260882-d58d0a00-ccf7-11ea-8456-6c93953a067e.png)

**Environment**

 - OS: Windows 10
 - CP Editor Version: 6.6.2

**Additional context**

The palette is set to white Base:

https://github.com/cpeditor/cpeditor/blob/3904ce28b17b34a7393e6d529a9ee918ba00a3ca/src/Widgets/DiffViewer.cpp#L103-L108

The background color is white on Arch Linux with KDE with both Dark Breeze and Dark Fusion.

We can use HTML style instead of palette as a workaround.

**Comment by ouuan** [comment]
As it's not very critical, we can merge #520 into master after the next release.

**Comment by Shashikant-alt** [comment]
![Screenshot from 2021-06-03 20-32-54](https://user-images.githubusercontent.com/53302882/120668069-bd575100-c4ab-11eb-9ab6-bc2560d2ed40.png)

The visibility is very low in solarised dark theme. Please tell me how to fix this.

**Comment by coder3101** [comment]
> ![Screenshot from 2021-06-03 20-32-54](https://user-images.githubusercontent.com/53302882/120668069-bd575100-c4ab-11eb-9ab6-bc2560d2ed40.png)
> 
> The visibility is very low in solarised dark theme. Please tell me how to fix this.

Duplicate of #533 in #581 it should be fixed (we are adding option to disable current line highlighting)
