### ISSUE TITLE
Option to change the color of messages shown in the message logger

### ISSUE THREAD

**Issue by sahilkhan03** [cpeditor/cpeditor#521]
*I find red color irritating and difficult to read, unfortunately, by default all the variables printed in cerr are shown red in console. So it would be better if there is an option to select the color of messages*

**Comment by ouuan** [comment]
@allcontributors add @sahilkhan03 as a contributor for ideas.

**Comment by ouuan** [comment]
Now there are some places using a color name instead of `warn`, `info`, `error`, for example, when showing an accepted verdict. We should add a function `accepted` and make the function using the color name private.

**Comment by coder3101** [comment]
Agreed, and there can be a setting tab titled "Colors" under appearance. Whatever is now in appearance should go under "Appearance->General".

**Comment by brun0-matheus** [comment]
I've looked into this issue and made a pull request (that I think closes it). It's my first contribution, so if I've made something wrong, warn me.
