### ISSUE TITLE
Code not getting restored

### ISSUE THREAD

**Issue by modinitin13** [cpeditor/cpeditor#528]
**Describe the bug**
Firstly my code file was not saved,then I tried to copy paste large input,then it was not responding,Eventually I closed the editor, after this when I opened the editor my code was not there,It was restored to some previous state.   

**To Reproduce**

**Screenshots**

**Environment**

 - OS: Windows 10 
 - CP Editor Version: 6.5.3

**Additional context**
The testcase length was around 10^6 lines
can't share the file,but the testfile was of FacebookHackerCup Problem C

**Comment by coder3101** [comment]
Which Version of CP Editor? Which OS? How much long Testcase (in characters) you tried copy pasting? You could have added the Testcase link in Additional Information if it's publicly available.

Did you assume we can guess all these for you? Please take time and make bug reports  detailed. We need to reproduce the behaviour in order to help you better.

**Comment by coder3101** [comment]
@ouuan testcases are elided when limit exceeds and it's loaded from file. What about when it's copy pasted?

**Comment by modinitin13** [comment]
Updated all the details in the,Also in my editor setting I have already increased the input length.BTW,I tried copy-pasting the input from input file

**Comment by coder3101** [comment]
Can you tell me if it was Paste action that made editor hung up or it was running your code on that big testcases that made editor hung up.

For code not getting restored.

In CP Editor settings, find Restore Sessions. Enable periodically saving session and Optionally change the interval to your desired value. When Editor hangs up, it cannot save your sessions.

**Comment by modinitin13** [comment]
The paste action

**Comment by ouuan** [comment]
> What about when it's copy pasted?

Not elided. You should drag the file into the editor or use file dialog to open it.

I guess it wouldn't be much faster if we elide pasted test cases, because QPlainTextEdit processes the pasted text, what we can do is only to elide after it has been in the edit.

**Comment by ouuan** [comment]
@modinitin13 For the big test case elide and periodically saving session, you should use v6.6. We can do nothing when you force the application to close, we can only periodically save it.

I think this solves the problem.
