### ISSUE TITLE
Solarized Dark focus area is not readable

### ISSUE THREAD

**Issue by sonulohani** [cpeditor/cpeditor#533]
**Is your feature request related to a problem? Please describe.**
While using cpeditor, I found out that the solarized dark theme is unusable due to the color used when the line is in focus. The screenshot would provide more info. I am comparing the cpeditor solarized dark theme with vscode solarized dark theme.

**Describe the solution you'd like**
Make it like in vscode.

![image](https://user-images.githubusercontent.com/2958681/88766180-394e8180-d195-11ea-989c-c6bef75bc8f9.png)

![image](https://user-images.githubusercontent.com/2958681/88766224-49666100-d195-11ea-8102-80f29e4830ca.png)

**Comment by coder3101** [comment]
This will be resolved by #516

**Comment by coder3101** [comment]
This is being resolved by adding an option to disable the highlight colour of the current line by #581 
A new issue to change the colour of the highlight will be added by #516
