### ISSUE TITLE
Setup automatially restarts Windows

### ISSUE THREAD

**Issue by nutzboi** [cpeditor/cpeditor#545]
After the setup is done, before I even choose to restart now or later, it automatically attempts to restart the computer.

 - OS: Windows 10
 - CP Editor Version: 6.5.4

**Comment by ouuan** [comment]
I can't reproduce this. Can you try installing again to see if this happens again?

**Comment by coder3101** [comment]
Never ever encountered it. Are you sure it's CP Editor not some other tool like Antivirus software?

**Comment by nutzboi** [comment]
i failed to reproduce it, guess it was something else then...

**Comment by ouuan** [comment]
I can confirm this. It's vcredist that restarts the computer. We should add the `/norestart` option.

**Comment by ouuan** [comment]
@allcontributors add @nutzboi for reporting the bug.
