### ISSUE TITLE
FreeBASIC Compiler

### ISSUE THREAD

**Issue by c-sanchez** [cpeditor/cpeditor#546]
Support to use **FreeBASIC** compiler with **CP Editor**.
FreeBASIC is a moderm free and open source QuickBASIC implementation for Microsoft Windows, DOS and Linux.
https://freebasic.net/

**Comment by ouuan** [comment]
We won't specifically support FreeBASIC because very few people use it for competitive programming. We may support custom compile command, run command, etc. in the future, see #371.
