### ISSUE TITLE
_fail verdict read as WA wrongly

### ISSUE THREAD

**Issue by StudyingFather** [cpeditor/cpeditor#567]
**Describe the bug**

When the checker return a `_fail` verdict, the verdict displayed is WA.

`_fail` verdict shows that there are problems while checking the answer, it's different from a simple Wrong Answer.

**To Reproduce**

Here is a checker to produce `_fail` verdict.

```cpp
#include "testlib.h"
int main(int argc,char** argv)
{
 registerTestlibCmd(argc,argv);
 int pans=ouf.readInt(),jans=ans.readInt();
 quitf(_fail,"Failed to check the answer.");
}
```

Add this checker in cpeditor. When the checker terminated, the output displays WA verdict.

**Screenshots**

![photo](https://user-images.githubusercontent.com/23295419/90317183-1f18ef80-df5a-11ea-81d9-e879b2ac05cc.png)

**Environment**

 - OS: Windows 10 1909
 - CP Editor Version: f8f8b0f

**Additional context**

**Comment by ouuan** [comment]
CP Editor is an IDE, not a judger. Do you think it's important to distinguish FAIL and WA in the verdict?

**Comment by coder3101** [comment]
Maybe we can have an extra verdict called "ERR"

**Comment by ouuan** [comment]
`ensure`/`ensuref` are usually used to check whether the answer is correct, if a condition fails, the verdict is `FAIL`. So `FAIL` is not necessarily different from `WA`.
