### ISSUE TITLE
indent format doest not work in cpp as clicking return(enter) an how to install clang format ?

### ISSUE THREAD

**Issue by ArbitCode** [cpeditor/cpeditor#584]
**Describe the bug**

while writing the code during the contest and when we click Tab the new line is not indented from that. we need to format indent automatically but the new line started from beginning.

**To Reproduce**

![image](https://user-images.githubusercontent.com/35590355/92299052-b2977c00-ef6c-11ea-905a-19bb4895325d.png)

**Screenshots**

**Environment**

 - OS: [Ubuntu 20.04]
 - CP Editor Version: [e.g. 6.0.2]

**Additional context**

**Comment by ArbitCode** [comment]
@ArbitCode ..

**Comment by ouuan** [comment]
1. I don't know what "when we click Tab the new line is not indented from that" means. When I press Tab at the beginning of a line, it adds an indent. Can you describe how to reproduce it in detail?
2. It seems that you are using `clang-11` for Clang Format, you should use `clang-format` or `clang-format-11` depending on what's installed on your system.

**Comment by ArbitCode** [comment]
![image](https://user-images.githubusercontent.com/35590355/92399091-58064780-f147-11ea-8619-e75c47c2790f.png)

thank you @ouuan, 
the `clang-format` is working now on clicking  `ctr+shift+I`.  also on vscode, there is an automatic suggestion
and the new line is formatted by clicking enter at the end of the line.  do we have this type of feature in CPeditor ??

**Comment by coder3101** [comment]
> ![image](https://user-images.githubusercontent.com/35590355/92399091-58064780-f147-11ea-8619-e75c47c2790f.png)
> 
> thank you @ouuan, 
> the `clang-format` is working now on clicking  `ctr+shift+I`.  also on vscode, there is an automatic suggestion
> and the new line is formatted by clicking enter at the end of the line.  do we have this type of feature in CPeditor ??

There is no such feature. It will be nice to have but we have to experiment and discover how it is done. If you want you can open an issue demanding that feature.
