### ISSUE TITLE
Save Settings to disk as it is applied

### ISSUE THREAD

**Issue by souravbiswassanto** [cpeditor/cpeditor#590]
**Describe the bug**
I lost my last saved settings and snippets after exiting or shutting down windows. But Everything other is fine. How to fix it?

**To Reproduce**

**Screenshots**

**Environment**

 - OS: [e.g. Windows 10 / Ubuntu 18.04]
 - CP Editor Version: [e.g. 6.0.2]

**Additional context**

**Comment by coder3101** [comment]
When you run and change settings, it is applied instantly but the save take place at exit of application. If something makes CP Editor close unexpectedly the settings are not saved and lost. 

A solution will be to save settings to disk as soon as it is applied. To reproduce the behaviour, run CP editor and change a setting. Send SIG_KILL to CP editor process. Launch again and the setting will be lost.

@ouuan and @neko-para I never understood this lazy saving behaviour of Settings.

**Comment by coder3101** [comment]
You should provide version and OS

**Comment by souravbiswassanto** [comment]
windows 10
version 1909 (os build 18363.418)

**Comment by coder3101** [comment]
CP Editor Version?

**Comment by souravbiswassanto** [comment]
Cp editor version is 6.6.4.

**Comment by coder3101** [comment]
Can you use 6.5.x (Stable version) and see if it has the same issue?

**Comment by souravbiswassanto** [comment]
Ok can you provide the link??

**Comment by coder3101** [comment]
> Ok can you provide the link??

https://github.com/cpeditor/cpeditor/releases/tag/6.5.5

**Comment by souravbiswassanto** [comment]
Same problem exists both version..
It saves all settings if only i close application after changing settings.
But its ok for me now..Thanks guys..

**Comment by ouuan** [comment]
> @ouuan and @neko-para I never understood this lazy saving behaviour of Settings.

The main reason is that I didn't think it causes problems. I assumed users normally close CP Editor, instead of being killed when closing Windows.

And I met several problems before when I tried to save the settings when it is applied, but now I can't remember what those problems were. You can try to save on disk when it's applied, but you should test it well. The settings system is a very basic part of CP Editor, so small changes could lead to unexpected problems. Maybe adding a button to save the settings on disk is better, but I'm not sure.

**Comment by souravbiswassanto** [comment]
I thought to post it as an another issue, but later i changed my mind because it might be only mine problem, problem is,
if i want to open any cpp file, i had to open it from inside of cpeditor, how to make cp editor as default for cpp file, there is no option there for cp editor, i have tried every possible way results in nothing,

**Comment by coder3101** [comment]
1. Don't close this issue. It can be converted into an enhancement feature.

2. You can open a cpp file with CP Editor. Just do this, right click a cpp file, open with, choose another program, find CP Editor.exe, click always use this to open cpp files. Click Ok

**Comment by souravbiswassanto** [comment]
Sorry cpeditor not available there. [https://drive.google.com/file/d/1a5SPNmKcNk_0AITa39lhnm4VXjPzRgUk/view?usp=sharing](url) see the photo

**Comment by coder3101** [comment]
@souravbiswassanto If you scroll down to "other options" there will be a option that says "Choose a program" then a file dialog will open. Choose where you installed cpeditor.exe

**Comment by ouuan** [comment]
I was thinking of monitoring the settings file like `QSettings`, which is not easy. Simply saving on apply seems fine.

**Comment by coder3101** [comment]
If you encounter some issue when saving settings as they are applied. We can do this.

Create a temporary (hidden) file that saves settings to disks as soon as it is applied. We can use this file to restore original settings in case of abnormal exit, for normal exit we delete this file.

By temporary, I do not mean a setting file in temporary directory. It should be in same config folder.

**Comment by coder3101** [comment]
> Simply saving on apply seems fine.

> > And I met several problems before when I tried to save the settings when it is applied, but now I can't remember what those problems were.

**Comment by ouuan** [comment]
> > Simply saving on apply seems fine.
> 
> > > And I met several problems before when I tried to save the settings when it is applied, but now I can't remember what those problems were.

I think I meant live-updating like QSettings instead of saving on apply.
