### ISSUE TITLE
Failed to parse Codeforces GYM URL

### ISSUE THREAD

**Issue by ammardab3an** [cpeditor/cpeditor#591]
At first, I would like to thank you for this awesome project which will save a lot of time for me, especially that I do most of my programming on a low spec laptop.

The issue I'm submitting is very simple: the function parseCfUrl could not parse a url for a problem from cf-gym.
![image](https://user-images.githubusercontent.com/40296428/93226091-9de09280-f77b-11ea-8792-835f9bf71fd4.png)
![image](https://user-images.githubusercontent.com/40296428/93226129-a8029100-f77b-11ea-87cf-7b96395c3fcb.png)

**Comment by coder3101** [comment]
Please open a PR and help us solve this issue. PR should add to the above code, no need to compile or setup Qt. It is a basic Regular expression code.  You can edit using any editor of your choice.

**Comment by coder3101** [comment]
Seems it is related with CF Tool. Which version of CF tool are you running?? `cf --version`

**Comment by coder3101** [comment]
@all-contributors add @ammardab3an for bugs

**Comment by ammardab3an** [comment]
Thank you everyone for the fast response.
