### ISSUE TITLE
View problem statement/page in the editor itself

### ISSUE THREAD

**Issue by Vaibhavch9876** [cpeditor/cpeditor#596]
**Issue :**

Generally while solving problems we need to switch the tab to the browser to have look on problem statement, most probably to see constraints and corner cases. So, sometimes it becomes too frequent in case the problem statements are too large.

**Suggestive Solution :**

So, a option would be that the problem statement itself get displayed in the editor and then there wouldn't be any need to switch tabs.

**Comment by coder3101** [comment]
Where exactly do you want them to be displayed? Can you not split the screen and change mode to "View" so one side you have browser in the other side you have CP Editor?

The quickest way to solve this is by opening a webview with the URL from a competitive companion, but I do not know where should the view go in the main window? It is already filled.
