### ISSUE TITLE
Issue with typing speed with the default font.

### ISSUE THREAD

**Issue by sinnersneversleep** [cpeditor/cpeditor#611]
The default font provided is monospace, when we type in it its too slow, however when I change the font to consolas, we can type lot faster.

**Comment by ouuan** [comment]
1. You can change the font by yourself.
2. The default font is the default system fixed-width font instead of monospace since v6.6.

**Comment by sinnersneversleep** [comment]
Thats what i told i have already changed the font, I was just informing about the issue.
