### ISSUE TITLE
Check for updates issue

### ISSUE THREAD

**Issue by harshitkapoor00** [cpeditor/cpeditor#622]
I'm using "cpedtior-6.7.1-windows-x64" version.
Check for updates option give some error of "TLS initialization failed"

![Screenshot (381)](https://user-images.githubusercontent.com/57800273/94901790-cde6a000-04b4-11eb-9129-642f56cb09f0.png)

**Comment by coder3101** [comment]
The error is self explanatory. What's the issue?
