### ISSUE TITLE
Thank you very much for the free open source program!

### ISSUE THREAD

**Issue by mrkaban** [cpeditor/cpeditor#637]
Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D1%83/ide/cp-editor.html).

Special thanks for translating the interface into Russian and for supporting Python!

The project is interesting, so please don't abandon it!

**Comment by Ravenclaw-OIer** [comment]
@ouuan Maybe we can have a "casual comments" issue?

@mrkaban This is really not an enhancement request. Please don't post it in issues. You may hop into the Telegram group and chat there though?

**Comment by mrkaban** [comment]
I am sorry if I offended someone.

It is very unpleasant when a person is rudely communicated, especially since I just wanted to thank for an excellent program. As a developer, I am pleased when they write me thanks for my programs.

**Comment by coder3101** [comment]
[Telegram group](t.me/cpeditor) is the best place for such talks. Come hang out with us over there.

I am grateful for your support, thanks goes to wonderful people @ouuan , @IZOBRETATEL777 for adding Russian language support.

As long as you all support, there is no chance this project will be abandoned.

**Comment by coder3101** [comment]
> I am sorry if I offended someone.
> 
> It is very unpleasant when a person is rudely communicated, especially since I just wanted to thank for an excellent program. As a developer, I am pleased when they write me thanks for my programs.

We have a [Code of Conduct](https://github.com/cpeditor/cpeditor/blob/master/CODE_OF_CONDUCT.md) that prevents rude behaviour from/to any individual.

His comments didn't sound offending, hurting. It was just a suggestion or request.

**Comment by ouuan** [comment]
> @ouuan Maybe we can have a "casual comments" issue?

There will be one in the GitHub Discussions when it's available for all projects. The GitHub Discussions will be the recommended place to ask questions. [It will be available soon](https://github.com/github/roadmap/projects/1#column-8536383).
