### ISSUE TITLE
The main window is not always brought to the foreground when the second session is launched

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#657]
**Describe the bug**

When a CP Editor is running and another CP Editor is started, the already running CP Editor should be brought to the foreground. However, now it's not brought to the foreground if the main window is under other programs but is not minimized.

**To Reproduce**

1. Open CP Editor.
2. Open an arbitary program to cover the main window of CP Editor.
3. Open another CP Editor. The icon of CP Editor in the taskbar flashes, but the main window of CP Editor is still under another program.
4. Minimize CP Editor.
5. Open another CP Editor. CP Editor is brought to the foreground.

**Environment**

 - OS: Arch Linux with KDE and Windows 10 
 - CP Editor Version: 99478c27

**Additional context**

We can minimize the window first and then show the window on top:

```cpp
void AppWindow::showOnTop()
{
    showMinimized();
    QTimer::singleShot(1, [this] { Util::showWidgetOnTop(this); });
}
```

However, this may cause an unexpected animation according the the OS/DE.

On Windows, [`AllowSetForegroundWindow(ASFW_ANY);`](https://stackoverflow.com/a/3320500/12601364) works.

However, this is not strictly a bug. Some users find it confusing that they can't open two CP Editors at the same time, and are not aware of the reason that the new CP Editor is not opened.

**Comment by ouuan** [comment]
The animation of minimizing then bring to the foreground is really strange and is not very acceptable :thinking:

**Comment by coder3101** [comment]
Doesn't any of the solution [here](https://stackoverflow.com/questions/6087887/bring-window-to-front-raise-show-activatewindow-don-t-work) worked?

**Comment by ouuan** [comment]
> Doesn't any of the solution [here](https://stackoverflow.com/questions/6087887/bring-window-to-front-raise-show-activatewindow-don-t-work) worked?

https://github.com/cpeditor/cpeditor/blob/99478c27af48aed3041f32bd23c6e58a3ae06c87/src/Util/Util.cpp#L25-L31

**Comment by ouuan** [comment]
It seems that minimizing at first doesn't always work on Linux, either. And this is not a bug: a setting prohibits this behavior:

![image](https://user-images.githubusercontent.com/30581822/98581323-47677e80-22fc-11eb-9523-2956353602f1.png)

When "Focus stealing prevention" is set to None, the master branch works well.
