### ISSUE TITLE
`-tabnext` has the wrong effect in fakevim

### ISSUE THREAD

**Issue by yzy-1** [cpeditor/cpeditor#711]
My English is not good, please allow me to use Google Translate.

**Describe the bug**

I cloned the source code of cpeditor, checked out the "fakevim-support` branch (commit hash is 2fca5fd8965aba1843adee9e53ec95d912e65615), and then proceeded to build.

After the build was completed, I ran `build/cpeditor`, opened `code editing> enable vim emulation` in the settings, and set `vim configuration` to empty.

Then I created 3 new tabs, switched to the second, and typed `:-tabnext` under vim-normal-mode, which would switch to the previous tab (ie the first) in "real vim" , But in cpeditor, it switches to the next tab page (that is, the third).

**To Reproduce**

```bash
git clone https://github.com/cpeditor/cpeditor
git checkout fakevim-support
git submodule init
git submodule update
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
./cpeditor
```

Then open the settings, enable `code editing > enable vim emulation`, and set `vim configuration` to empty.

Create three new tabs, use the mouse to switch to the second one, enter `:-tabnext` under "vim-normal-mode".

**Environment**

- OS: Archlinux 5.4.82-1-lts x86_64 GNU/Linux
- DE: KDE plasma 5.20.4
- QT: 5.15.2
- cmake: 3.19.1
- cpeditor branch: fakevim-support
- git commit hash: 2fca5fd8965aba1843adee9e53ec95d912e65615
- cpeditor version (in Help>Build Info): 6.8.0

**Chinese version:**

我克隆了 cpeditor 的源代码, checkout 到了 "fakevim-support` 分支 (commit hash 为 2fca5fd8965aba1843adee9e53ec95d912e65615), 然后进行了 build.

build 完成后我运行了 `build/cpeditor`, 在设置中打开了 `code editing > enable vim emulation`, 并把 `vim configuration` 设置为空.

然后我新建了 3 个标签页, 切换到了第二个, 然后在 vim-normal-mode 下输入 `:-tabnext`, 这在 "真正的 vim" 中会切换到上一个标签页 (即第一个), 可是在 cpeditor 中, 它切换到了下一个标签页 (即第三个).

**Comment by coder3101** [comment]
`tabn` or `tabnext` will switch to next tab. `tabp` or `tabprevious` will switch to previous tab. 

I think you mean `-tabn` should negate `tabn` and instead perform `tabp`.

From Fakevim code 

https://github.com/hluk/FakeVim/blob/bbe5e16ad252155eeb2eed899ce831635de1cb42/fakevim/fakevimhandler.cpp#L5614-L5630

Behaviour of `-tabn` to perform `tabp` should have been handled by the fakevim library but it doesn't handle it. It only matches the command name to perform the action.

**Comment by coder3101** [comment]
You can re-open this issue on [fakevim repository](https://github.com/hluk/fakevim)

Closing as it is not an issue of CP Editor.
