### ISSUE TITLE
C++ compile command never gets saved

### ISSUE THREAD

**Issue by Valkyrie006** [cpeditor/cpeditor#718]
**Describe the bug**

When we go to Options->Preferences->Language->C++->C++ commands->C++ compile command. When I change my C++ compile command it doesn't change after a restart of my computer. I added some flags in my compile command and every time I restart then the command changes to the original command. This did not happen in earlier versions.

**To Reproduce**

Open CP Editor go to Options->Preferences->Language->C++->C++ commands->C++ compile command and change C++ compile command and click apply. Close CP Editor and then reopen it after a restart of computer and check C++ compile command. The command changes to the original command.

**Environment**

 - OS: Ubuntu 20.10
 - CP Editor Version: 6.6.5

**Comment by coder3101** [comment]
Related to #590

**Comment by coder3101** [comment]
Settings are saved when cpeditor exits successfully (i.e with exit code 0). If cpeditor crashes (i.e non zero exit code) while closing or in any other way, all the setting changes are lost.

Could you confirm if its only compile command or any/all other setting are also lost?

A quick way to check cpeditor's exit code would be to run it from command line and then quit it, then issue `echo $?` in same command line to get exit code of last process(i.e cpeditor in this case).

**Comment by Valkyrie006** [comment]
It shows exit code 0, still my settings does not get saved.

**Comment by ouuan** [comment]
Can you describe how the "restart of computer" affects the behaviour? Is the setting saved before the restart?

Are all settings or only the compile command, reset to default or reset to a previous state but not the default?

Could you please upload the log file?

1.  Close CP Editor if it's still running.
2.  Open CP Editor.
3.  Reproduce the unexpected behavior with as few operations as you can. (i.e. change the previously unsaved settings)
4.  Click Options->Show Log Files.
5.  Close CP Editor.
6.  Upload the latest log file which was revealed in step 4.
