### ISSUE TITLE
Can you provide a windows-x86-setup?

### ISSUE THREAD

**Issue by lijunhan0** [cpeditor/cpeditor#719]
Our school only have computers with odd 32-bit Windows and I really want to use cp-editor at school.
So can you pls provide a 32-bit version?

**Comment by ouuan** [comment]
Can anyone test [this](https://github.com/ouuan/cpeditor/releases/tag/0.43179.432) on 32-bit Windows?

**Comment by lijunhan0** [comment]
> Can anyone test [this](https://github.com/ouuan/cpeditor/releases/tag/0.43179.434) on 32-bit Windows?

Yes it works good all right, at least it did until now.

**Comment by ouuan** [comment]
> Yes it works good all right, at least it did until now.

This is really confusing... May I assume that you meant "it has been working well up to now" by "at least it did until now"?

**Comment by lijunhan0** [comment]
> > Yes it works good all right, at least it did until now.
> 
> This sentence is really confusing... May I assume that you meant "it has been working well up to now" by "at least it did until now"?

Yes. Sorry for that.
