### ISSUE TITLE
CPEditor crashes when searching specific font 

### ISSUE THREAD

**Issue by sonulohani** [cpeditor/cpeditor#746]
**Describe the bug**

CPEditor is crashing with the message **FAIL Don't use rand(), use rnd.next() instead** when searching for font.

**To Reproduce**

1. Run CPEditor for the first time.
2. Go to Option->Preferences.
3. In preferences dialog, go to Appearance->Font
4. Click on Editor font and search for any font.  

Screenshot
![image](https://user-images.githubusercontent.com/2958681/106386766-99500a00-63fc-11eb-9324-c1fe8d62369e.png)

**Environment**

 - OS: Linux mint 20.1
 - CP Editor Version: 6.8.0
 - Qt 5.15.2

![bug](https://user-images.githubusercontent.com/2958681/106385756-e8477080-63f7-11eb-8766-e2d4ec12f6dd.gif)

**Comment by ouuan** [comment]
I can't reproduce this. Can you build it with `-D CMAKE_BUILD_TYPE=Debug` and run it in the terminal and show me the output?

"FAIL Don't use rand(), use rnd.next() instead" is a message from [testlib](https://github.com/MikeMirzayanov/testlib/), I don't know how it can appear when CP Editor crashes.

BTW, although a GIF is informative, I need to wait for a long time to wait for it to cycle again, so multiple screenshots are more helpful.

**Comment by sonulohani** [comment]
I dont know If this Qt bug. However I am using build provided by the Qt devs(using setup) not from source. QFontDialog is where its crashing.

**Comment by sonulohani** [comment]
Here is the output you've asked for:

![Build with debug option](https://user-images.githubusercontent.com/2958681/106386474-272af580-63fb-11eb-8d72-973b471b91ac.gif)

**Comment by sonulohani** [comment]
The example from Qt is working fine. 

![Notepad example from Qt is working fine](https://user-images.githubusercontent.com/2958681/106386599-c6e88380-63fb-11eb-80c4-a241543f7094.gif)

**Comment by sonulohani** [comment]
I haven't uploaded screenshot for now because there is not enough info available to look at. But I will upload screenshot if its more informative

**Comment by ouuan** [comment]
Can you run it in gdb and get the backtrace?

**Comment by sonulohani** [comment]
This is what the output from gdb

>  ~/Documents/github/cpeditor/build> gdb cpeditor                                                                                                       ✔ 
> GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
> Copyright (C) 2020 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> Type "show copying" and "show warranty" for details.
> This GDB was configured as "x86_64-linux-gnu".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
>     <http://www.gnu.org/software/gdb/documentation/>.
> 
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> Reading symbols from cpeditor...
> (gdb) run
> Starting program: /home/sonul/Documents/github/cpeditor/build/cpeditor 
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> [New Thread 0x7ffff1e24700 (LWP 20460)]
> [New Thread 0x7fffe9fb6700 (LWP 20461)]
> [New Thread 0x7fffe97b5700 (LWP 20462)]
> [New Thread 0x7fffe34fe700 (LWP 20463)]
> [New Thread 0x7fffe2cfd700 (LWP 20464)]
> [New Thread 0x7fffe24fc700 (LWP 20465)]
> [New Thread 0x7fffe1cfb700 (LWP 20466)]
> [New Thread 0x7fffe14fa700 (LWP 20467)]
> [New Thread 0x7fffe0cf9700 (LWP 20468)]
> [New Thread 0x7fffbffff700 (LWP 20469)]
> [New Thread 0x7fffbf7fe700 (LWP 20470)]
> [New Thread 0x7fffbeffd700 (LWP 20471)]
> [New Thread 0x7fffbcc9f700 (LWP 20473)]
> [New Thread 0x7fffab05b700 (LWP 20474)]
> [New Thread 0x7fffaa85a700 (LWP 20475)]
> [New Thread 0x7fffaa059700 (LWP 20476)]
> [New Thread 0x7fffa9858700 (LWP 20477)]
> [New Thread 0x7fffa8ab5700 (LWP 20478)]
> [New Thread 0x7fff93fff700 (LWP 20479)]
> QTextCursor::setPosition: Position '1' out of range
> [New Thread 0x7fff924f8700 (LWP 20481)]
> [New Thread 0x7fff91cf7700 (LWP 20482)]
> [Thread 0x7fff924f8700 (LWP 20481) exited]
> FAIL Don't use rand(), use rnd.next() instead
> [Thread 0x7fffaa059700 (LWP 20476) exited]
> [Thread 0x7fffaa85a700 (LWP 20475) exited]
> [Thread 0x7fffab05b700 (LWP 20474) exited]
> [Thread 0x7fffbcc9f700 (LWP 20473) exited]
> [Thread 0x7fffbeffd700 (LWP 20471) exited]
> [Thread 0x7fff91cf7700 (LWP 20482) exited]
> [Thread 0x7fff93fff700 (LWP 20479) exited]
> [Thread 0x7fffa8ab5700 (LWP 20478) exited]
> [Thread 0x7fffa9858700 (LWP 20477) exited]
> [Thread 0x7fffbf7fe700 (LWP 20470) exited]
> [Thread 0x7fffbffff700 (LWP 20469) exited]
> [Thread 0x7fffe0cf9700 (LWP 20468) exited]
> [Thread 0x7fffe14fa700 (LWP 20467) exited]
> [Thread 0x7fffe1cfb700 (LWP 20466) exited]
> [Thread 0x7fffe24fc700 (LWP 20465) exited]
> [Thread 0x7fffe2cfd700 (LWP 20464) exited]
> [Thread 0x7fffe34fe700 (LWP 20463) exited]
> [Thread 0x7fffe97b5700 (LWP 20462) exited]
> [Thread 0x7fffe9fb6700 (LWP 20461) exited]
> [Thread 0x7ffff1e24700 (LWP 20460) exited]
> --Type <RET> for more, q to quit, c to continue without paging--
> [Inferior 1 (process 20456) exited with code 03]

I dont see any useful info

**Comment by sonulohani** [comment]
Let me build Qt from source using developer-build option. That way I could debug the Qt libs as well. Give me some time.

**Comment by ouuan** [comment]
You need to run `backtrace` or `bt` in gdb to get the backtrace.

**Comment by ouuan** [comment]
BTW, when did "FAIL Don't use rand(), use rnd.next() instead" appear? It should appear only when running a custom checker.

**Comment by sonulohani** [comment]
I can't run bt. The process is already getting killed after the crash. If I run bt it says "No stack."

**Comment by sonulohani** [comment]
> BTW, when did "FAIL Don't use rand(), use rnd.next() instead" appear? It should appear only when running a custom checker.

This message appears after the crash

**Comment by ouuan** [comment]
I'm also wondering how "QTextCursor::setPosition: Position '1' out of range" happened. Are you sure you are running without any configs? Check `~/.config/CP Editor` and delete all files in it.

**Comment by sonulohani** [comment]
> I'm also wondering how "QTextCursor::setPosition: Position '1' out of range" happened. Are you sure you are running without any configs? Check `~/.config/CP Editor` and delete all files in it.

I tried but still able to reproduce this issue.

**Comment by sonulohani** [comment]
Hi @ouuan The problem has got introduced after this commit: https://github.com/cpeditor/cpeditor/commit/e3c72b5e125298c9496e503705e8a48b3788ae00 . In testlib.h if I comment out line no. 4271 which is `quitf(_fail, "Don't use rand(), use rnd.next() instead");` I couldn't able to reproduce the bug after that. The testlib library doesn't allow the use of rand method.

**Comment by ouuan** [comment]
Can you find out where was the `rand()` function called?

**Comment by ouuan** [comment]
Maybe it's a bad idea to use `testlib.h` in a project rather than in a checker/validator, etc. :thinking:
