### ISSUE TITLE
Auto Indent does not work for me 

### ISSUE THREAD

**Issue by sanskarsharma100** [cpeditor/cpeditor#751]
**Describe the bug**

In my laptop auto-indent doesn't work. when I use "{" and press enter, auto-indent doesn't work. I have already turned on my auto-indent.

**To Reproduce**

Write a simple code in c++

**Screenshots**
![image](https://user-images.githubusercontent.com/56783054/106764347-b9323880-665d-11eb-8d97-f9d2197b0099.png)

![image](https://user-images.githubusercontent.com/56783054/106764511-dbc45180-665d-11eb-92e6-2e79d6ba70df.png)

**Environment**

 - OS: Windows 10
 - CP Editor Version: 6.6.5

**Additional context**

Auto indent works on my friend's laptop with the same specs.

**Comment by ouuan** [comment]
> Auto indent works on my friend's laptop with the same specs.

If you can't reproduce it on your friend's laptop, I surely can't reproduce it on my laptop thus have no idea what happened on your laptop.

It's very likely that there's something wrong with your configs or operations during typing. If no more information is provided, there's nothing I can do for you.

**Comment by coder3101** [comment]
Try to clean all your configs. Located at `C:/Users/<USER>/AppData/Local/CPEditor`. If you still cannot auto-indent, make sure your keyboard layout is ENG-US, When `ENTER` key is detected, we auto-indent, It could be that you are using some other slightly different keyboard layout. Lastly, try a different keyboard, like and external keyboard and check if issue persists.

**Comment by pumaWay** [comment]
i have the same issue , and in my laptop, when you press enter ,the auto indent does not work either.
here the video
there's nothing wrong with the settings, but it just doesn't work.i've checked the settings.
i remove the editor from my laptop as well as some setting files related to it and install again.sometimes the auto indent work but after some time using, it just don't work.

https://user-images.githubusercontent.com/109681432/185537956-fe2c2115-8602-440d-bdb6-17c55890b13b.mp4
