### ISSUE TITLE
Can cpeditor support mac m1?

### ISSUE THREAD

**Issue by Maydaytyh** [cpeditor/cpeditor#752]
**Describe the bug**
I download cpeditor on my new m1 mba, and the logo just jumped. But it can't be used, I can't open it. Is this my own problem?

**To Reproduce**

**Screenshots**

**Environment**

 - OS: MacOS Bigsur 11.1
 - CP Editor Version: latest version

**Additional context**

**Comment by coder3101** [comment]
> I download cpeditor on my new m1 mba, and the logo just jumped. But it can't be used, I can't open it. Is this my own problem?

Neither your nor our problem. We don't test nor can we test or build for ARM processor. Ideally, It was upto the Rosetta 2 to translate our application to be able to run in your ARM mba.

Did you had same issue with any other x64 application?

**Comment by ouuan** [comment]
Qt doesn't support Apple Silicon (arm64) as for now:
- https://bugreports.qt.io/browse/QTBUG-85279
- https://lists.qt-project.org/pipermail/interest/2020-June/035445.html.

**Comment by Roxiun** [comment]
Qt now supports arm64/Apple silicon

**Comment by Roxiun** [comment]
M1 is now supported by Qt
