### ISSUE TITLE
CF-tool configuration **5.7 Now it ask other suffix. Keep it empty**

### ISSUE THREAD

**Issue by iamworldian** [cpeditor/cpeditor#757]
_**5.7 Now it ask other suffix. Keep it empty**__

~~~~~
if I keep it empty  cp-editor arise this error :
~~~~~

~~~~~
log details : 

[ MessageLogger.cpp  ](72)::MessageLogger Information <head>: [CF Tool], <body>: [/tmp/CP Editor-VeyRYX/sol.cpp can not match any template. You could add a new template by `cf config`
~~~~~
source of this error from CF-tool repo :
(https://github.com/xalanq/cf-tool/blob/master/cmd/cmd.go)

line : 106

trying with some dummy instead of keeping it empty works.

**Comment by ouuan** [comment]
I can't understand your problem description. What is "Now it ask other suffix. Keep it empty"? What is "if I keep it empty"? To keep what empty?

Whatever, I hope [this](https://cpeditor.org/docs/faq/#when-i-click-the-submit-button-i-get-some-message-saying-template-is-required) helps.

**Comment by ouuan** [comment]
OK, I got it. You mean `Other suffix? (e.g. "cxx cc"), empty is ok:` in `cf config`. CF Tool is not maintained by us, so your problem description is really confusing.

**Comment by ouuan** [comment]
This is a problem of CF Tool or your configuration of CF Tool and has nothing to do with CP Editor.

**Comment by iamworldian** [comment]
@ouuan As you have claimed in this blog on [codeforces](https://codeforces.com/blog/entry/72952) , 
_**5.7 Now it ask other suffix. Keep it empty**_
this might can mislead people while installing this tool.So I want you to have notice on that and edit the blog details.

**Comment by ouuan** [comment]
1. It's @coder3101, not me, who wrote the blog. So it's hard for me to understand "5.7".
2. As it's a problem with the blog, it's better to write a comment under that blog.
3. Leaving the suffix empty works for me. I don't know why it doesn't work for you. I don't know much about CF Tool since I don't develop it.

**Comment by coder3101** [comment]
> trying with some dummy instead of keeping it empty works.

It might have been changed for the latest CF tool. I will update the blog, with this information. 

Thanks, fo it @iamworldian
