### ISSUE TITLE
Breaking changes for CP Editor 7.0 in the future

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#769]
There could be some changes that break something, especially the settings.

We can list them here, and apply them when we are ready for CP Editor 7.0.

~~- [ ] Drop support for the current editor themes. (#516)~~ Now KSyntaxHighting supports [many themes](https://github.com/KDE/syntax-highlighting/tree/master/data/themes).
- [ ] #925
- [ ] #926
- [ ] #927
- [ ] #928

**Comment by coder3101** [comment]
Closed, Individual issues are created and marked with v7.0 milestone.
