### ISSUE TITLE
Failure occured at build while installing

### ISSUE THREAD

**Issue by devkant** [cpeditor/cpeditor#772]
**Describe the bug**

A Failure occurred in build();

**To Reproduce**

Install cpeditor from: yay cpeditor

**Screenshots**

![cperror](https://user-images.githubusercontent.com/32243035/108025919-5cffe900-704d-11eb-8b73-70ec89e7ca05.png)

**Environment**

 - OS: Manjaro 
 - CP Editor Version: 6.7.2-1

**Additional context**

[devkant@devkant-pc ~]$ yay cpeditor
2 aur/cpeditor 6.7.2-1 (+1 0.00%) 
    The editor for competitive programming
1 aur/cpeditor-git 6.8.1.r15.g7df7a6d2-1 (+2 0.01%) 
    The editor for competitive programming
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 2
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo Make: 1]  ninja-1.10.2-1
[Aur: 1]  cpeditor-6.7.2-1

==> Remove make dependencies after install? [y/N] N 
  1 cpeditor                                 (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> N
:: PKGBUILD up to date, Skipping (1/1): cpeditor
  1 cpeditor                                 (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> N
:: Parsing SRCINFO (1/1): cpeditor
[sudo] password for devkant: 
resolving dependencies...
looking for conflicting packages...

Packages (1) ninja-1.10.2-1

Total Installed Size:  0.30 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                     [#######################] 100%
(1/1) checking package integrity                   [#######################] 100%
(1/1) loading package files                        [#######################] 100%
(1/1) checking for file conflicts                  [#######################] 100%
(1/1) checking available disk space                [#######################] 100%
:: Processing package changes...
(1/1) installing ninja                             [#######################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
==> Making package: cpeditor 6.7.2-1 (Tuesday 16 February 2021 11:42:27 AM)
==> Retrieving sources...
  -> Found cpeditor-6.7.2-full-source.tar.gz
==> Validating source files with sha256sums...
    cpeditor-6.7.2-full-source.tar.gz ... Passed
ninja not satisfied, flushing install queue
==> Making package: cpeditor 6.7.2-1 (Tuesday 16 February 2021 11:42:28 AM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found cpeditor-6.7.2-full-source.tar.gz
==> Validating source files with sha256sums...
    cpeditor-6.7.2-full-source.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting cpeditor-6.7.2-full-source.tar.gz with bsdtar
==> Sources are ready.
==> Making package: cpeditor 6.7.2-1 (Tuesday 16 February 2021 11:42:30 AM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
-- The CXX compiler identification is GNU 9.2.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /usr/bin/python3.8 (found version "3.8.1") found components: Interpreter 
-- The C compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Will build the setup version
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Git commit hash: a587851
-- Display version: 6.7.2
-- Minor version: v6.7
-- Configuring done
-- Generating done
-- Build files have been written to: /home/devkant/.cache/yay/cpeditor/src/cpeditor-6.7.2-full-source/build
[1/94] Automatic MOC and UIC for target QtFindReplaceDialog
FAILED: third_party/QtFindReplaceDialog/dialogs/CMakeFiles/QtFindReplaceDialog_autogen third_party/QtFindReplaceDialog/dialogs/QtFindReplaceDialog_autogen/mocs_compilation.cpp 
cd /home/devkant/.cache/yay/cpeditor/src/cpeditor-6.7.2-full-source/build/third_party/QtFindReplaceDialog/dialogs && /usr/bin/cmake -E cmake_autogen /home/devkant/.cache/yay/cpeditor/src/cpeditor-6.7.2-full-source/build/third_party/QtFindReplaceDialog/dialogs/CMakeFiles/QtFindReplaceDialog_autogen.dir/AutogenInfo.json Release

AutoUic subprocess error
------------------------
The uic process failed to compile
  "SRC:/third_party/QtFindReplaceDialog/dialogs/findreplacedialog.ui"
into
  "SRC:/build/third_party/QtFindReplaceDialog/dialogs/QtFindReplaceDialog_autogen/include/ui_findreplacedialog.h"
included by
  "SRC:/third_party/QtFindReplaceDialog/dialogs/finddialog.cpp"
  "SRC:/third_party/QtFindReplaceDialog/dialogs/findreplacedialog.cpp"

Command
-------
/usr/bin/uic -o /home/devkant/.cache/yay/cpeditor/src/cpeditor-6.7.2-full-source/build/third_party/QtFindReplaceDialog/dialogs/QtFindReplaceDialog_autogen/include/ui_findreplacedialog.h /home/devkant/.cache/yay/cpeditor/src/cpeditor-6.7.2-full-source/third_party/QtFindReplaceDialog/dialogs/findreplacedialog.ui

Output
------
/usr/bin/uic: error while loading shared libraries: libicui18n.so.68: cannot open shared object file: No such file or directory

[4/94] Automatic MOC and UIC for target QCodeEditor
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
Error making: cpeditor
[devkant@devkant-pc ~]$

**Comment by ouuan** [comment]
Have you updated your system via `yay` or `sudo pacman -Syu` recently?

**Comment by devkant** [comment]
@ouuan
No, I haven't updated the system.

**Comment by ouuan** [comment]
> @ouuan
> No, I haven't updated the system.

I think you should update your system instead of sending this reply. You may want to read [Partial upgrades are unsupported](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported).

**Comment by ouuan** [comment]
As an Arch-based distro user, you need to update your system very often, especially before installing any packages, more especially when errors happen.
