### ISSUE TITLE
Add multi-caret support

### ISSUE THREAD

**Issue by DrSwad** [cpeditor/cpeditor#773]
**Is your feature request related to a problem? Please describe.**

Without multi-caret support, refactoring a variable/number has to be done -
- either by manually editing each of it's instances, which is very inconvenient,
- or using `find & replace` on all it's instances, which might cause unintentional changes to other variables/numbers producing nasty bugs.

**Describe the solution you'd like**

There should be a shortcut for multi-caret feature. For example, in Sublime Text it can be triggered by pressing `⌘` `D`. For the purpose of describing this feature's specifications, I'll assume that the shortcut we're using is `⌘` `G` (I'm considering `G` instead of `D` in the shortcut, because we'll be needing `⌘` `⇧` `G` too for this feature, and `⌘` `⇧` `D` appears to be already assigned for line duplication).

I know there are a lot of details and corner-cases to be handled for this feature, but it's an important part of my workflow and I'm willing to contribute as much as possible for it to be implemented, with some guidance from the team. Let me briefly start the discussion of this feature's specifications below (imitating this feature's behaviour from Sublime Text and IntelliJ IDE):

* Every action that the user takes should be imitated across all the available carets (including pressing `⌘` `G` or `⌘` `⇧` `G`).
* If the user had just pressed, without loss of generality, `⌘` `G`, then consider 2 possible cases -
    1. If the caret already has some text selected (let's call this selected piece of text `T`), then consider the next occurrence of `T` -
        1. If there is already a caret present at the end of this new occurrence, then do nothing.
        2. Otherwise, select this new occurrence of `T` and place a new caret at the end of it.
    2. If the caret doesn't have any text selected yet, then there are 4 possible cases -
        1. If the caret is in between a word (a continuous sequence of characters), then select the word, and move the caret at the end of the word.
        2. If the caret is at the end of a word, then select the word.
        3. If the caret is at the beginning of a word, then select the word, and move the caret at the end of the word.
        4. Otherwise, select all the continuous whitespaces in the current line that includes the caret, and move the caret at the end of the selection.
* If the user instead presses `⌘` `⇧` `G`, then swap all the next/previous logics in the previous bullet point.
* Notice that, step 1 is performed for all the available carets.

Now, there are obviously a few corner-cases/flaws in my stated procedure above. For example, what happens when multiple carets cross each other during deletion, or how to handle when multiple selections from multiple carets overlap, et cetera.

But I'm hoping that this would serve as a good enough starting point for the discussion, kindly let me know your thoughts on the matter.

**Describe alternatives you've considered**

I can't find any efficient and safe alternative to it. Manually editing and `find & replace`-ing appear to be the only alternatives at the moment and they both seem to be terrible solutions to me.

**Additional context**

Double clicking/selecting a variable/number seems to be correctly highlighting all the instances of that variable/number in the code, and not just highlighting all the *textual* occurrences of it. So, I guess the editor is already intelligent enough to find out all the instances based on context correctly, now it just needs to be able to edit multiple instances simultaneously.

**Comment by ouuan** [comment]
First of all, we are using [QTextEdit](https://doc.qt.io/qt-5/qtextedit.html). It will be very difficult for us to implement this if Qt doesn't support this.

About your problem, I don't understand why Find/Replace causes more trouble than multi-caret. It seems that what solves your problem is a correct way to get the text which needs to be replaced. Does it solve your problem if Find/Replace can replace the text which in your specifications should be selected by multi-caret? BTW, are you aware of the "Whole words only" checkbox in the Find/Replace dialog?
