### ISSUE TITLE
Press QKeySequence::MoveToStartOfLine, go to the first non-blank character

### ISSUE THREAD

**Issue by andreaemonti** [cpeditor/cpeditor#774]
When you press the home-key, the cursor would move at the beginning of the line, but AFTER the indentation tabs/spaces.

I know, I am asking again for a feature from geany, but I am so used to it, that I can't help making mistakes as if it worked the same in CPeditor. Maybe it's just me used to it, but if it is easy to implement, I think it would be a little nice feature for everyone (maybe flaggable in settings > code edit).
Thank you.

**Comment by coder3101** [comment]
Overriding `home` KeyPress event in QCodeEditor to move to first non-white character should do the job.

**Comment by ouuan** [comment]
> Overriding `home` KeyPress event in QCodeEditor to move to first non-white character should do the job.

As stated in the modified title, we should use `QKeySequence::MoveToStartOfLine` because it's not Home on macOS.
