### ISSUE TITLE
Configurable text cursor width

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#781]
**Is your feature request related to a problem? Please describe.**

The text cursor width is 1px now, it can be too narrow on some device or for some people.

**Describe the solution you'd like**

Make its width configurable.

**Additional context**

https://doc.qt.io/qt-5/qtextedit.html#cursorWidth-prop

https://forum.qt.io/post/368794

**Comment by sonulohani** [comment]
Hi @coder3101 Could you please assign this to me
