### ISSUE TITLE
Competitive Companion is not parsing anything

### ISSUE THREAD

**Issue by SpagBetty** [cpeditor/cpeditor#783]
**Describe the bug**

Competitive Companion is not parsing anything on CP Editor

**To Reproduce**

Competitive Companion is set to port 10046 and CP editor as well, but for some reason when parsing the problem, nothing happens. It started happening today, it was working yesterday. Surprisingly, when i ran the Competitive Companion in debug mode, it does send the metadata to console.. so maybe it's working?

**Screenshots**

NA

**Environment**

OS: [Windows 7 Ultimate 64-Bit]
CP Editor Version: [6.8]

**Additional context**

I was working normally yesterday, and today i am pressing the Competitive Companion Parse Task button and its doing nothing. Its possible that it's some issue on Competitive Companion's side, but since i made absolutely no change to my PC it makes no sense why would this happen.

I checked on my laptop as well OS: [OSX Big Sur] its not working there too, is it working for y'all?

**Comment by coder3101** [comment]
Competitive companion (any browser extension) is automatically updated by the browser. Since it was working yesterday and not working today could mean two things:

1. Competitive companion updated itself automatically and not for some reason it doesn't sends data to cpeditor

2. Your OS or antivirus might have got some security update and it now prevents cpeditor from starting a local server to listen for competitive companion data.

Former is more likely, however we need more confirmation.

**Comment by coder3101** [comment]
Some tips that may help us and you troubleshooting the problem:

1. Try with a different browser (Firefox recommended)

2. Provide us log files. Open cpeditor, (if already open, close it and re-open) then open browser and try to parse a problem. Switch to cpeditor, click Options->Show log file, and upload it here.

**Comment by coder3101** [comment]
I would also like to bring to your notice that starting 6.8(latest beta) we use QHttp for creating local server to get data from competitive companion.

If you recently updated cpeditor, please try with latest stable version (6.7).

**Comment by SpagBetty** [comment]
I tried what you said, it's a problem with Brave Browser it seems. I tried using Chrome and Firefox and it works. 

The Brave Browser did update itself it seems and something broke inside. So, maybe they'll fix it in further updates.

Thanks for the quick and helpful response :)
