### ISSUE TITLE
Press <Esc> to cancel select

### ISSUE THREAD

**Issue by Empathy117** [cpeditor/cpeditor#786]

**Comment by sonulohani** [comment]
Esc should cancel the selection. Hey @ouuan Could you assign this issue to me. Thanks

**Comment by coder3101** [comment]
You should intercept Esc inside QCodeEditor. There is a method `onKeyPressed(QEvent*)` (something like this) where we handle everything like indenting when enter is pressed and other things like indenting on closing brace. This way Esc is intercepted only when editor is in focus.

**Comment by sonulohani** [comment]
Hi @coder3101 In my opinion, F11 key should do the toggle of full screen/restore screen to normal. We should not restore the window using Esc key. What do you want to say in this regard?

**Comment by ouuan** [comment]
> In my opinion, F11 key should do the toggle of full screen/restore screen to normal. We should not restore the window using Esc key. What do you want to say in this regard?

If a user accidentally pressed F11, maybe they don't know how to exit full-screen, and they may try <kbd>Esc</kbd>.

**Comment by Empathy117** [comment]
> > In my opinion, F11 key should do the toggle of full screen/restore screen to normal. We should not restore the window using Esc key. What do you want to say in this regard?
> 
> If a user accidentally pressed F11, maybe they don't know how to exit full-screen, and they may try Esc.

I'm using chrome if i pressed F11, chrome just display a message to tell me how to exit full-screen. Maybe you can solve it like chrome?

**Comment by sonulohani** [comment]
I tried using ESC while I was in full screen in vs code and it didn't restore the vs code in normal state and nowadays its common to use F12 for full screen. Only a newbie who wouldnt have used computer would have problem.

**Comment by sonulohani** [comment]
Hi @coder3101 , Can we have entry in CP Editor config ini for non gui elements. I can't find any way to add an entry in ini without adding it in preferences page.

**Comment by ouuan** [comment]
> Hi @coder3101 , Can we have a way to enter the key and value in CP Editor config ini file for non gui elements. I can't find any way to add an entry in ini without adding it in preferences page.

I've been confused by your "Hi, @" for a long time. This sentence is good if you want to talk to a specific person, but it's often weird in a public thread. My understanding is that you only want answers from @coder3101 but not from me.

**Comment by coder3101** [comment]
Guys! 
Please don't escalate things anymore.

@sonulohani you should ask it in general, Settings module of cpeditor was written by @ouuan, he can better guide you.

I request @ouuan to help him with his issues. Please guys.

**Comment by ouuan** [comment]
I don't know what I was "escalating". If any sentence sounded like escalating something please point it out so that I can prevent speaking misleading sentences the next time.

**Comment by ouuan** [comment]
> Can we have a way to enter the key and value in CP Editor config ini file for non gui elements. I can't find any way to add an entry in ini without adding it in preferences page.

Why do you want to do this? What config are you adding?

**Comment by sonulohani** [comment]
> > Can we have a way to enter the key and value in CP Editor config ini file for non gui elements. I can't find any way to add an entry in ini without adding it in preferences page.
> 
> Why do you want to do this? What config are you adding?

Sorry for tagging the specific user. I will not repeat it again. 

I want to show dialog only for the first time when I am in full screen mode to let user know that, to exit out of full screen one need to press F11 again. This is only for the first time. To keep track of whether the dialog is ever shown or not, will be stored in config file and thats where I want to introduce the settings for the same.

**Comment by ouuan** [comment]
> I want to show dialog only for the first time when I am in full screen mode to let user know that, to exit out of full screen one need to press F11 again. This is only for the first time. To keep track of whether the dialog is ever shown or not, will be stored in config file and thats where I want to introduce the settings for the same.

You can simply add it in settings.json and not put it in PreferencesWindow, like:

https://github.com/cpeditor/cpeditor/blob/ba8c1eaf1e5b2559a12399674bb6857c3ca97eb4/src/Settings/settings.json#L1151-L1156.

**Comment by coder3101** [comment]
This is how we use above `setting.json` to show PreferenceWindow for first time user launches application.

https://github.com/cpeditor/cpeditor/blob/ba8c1eaf1e5b2559a12399674bb6857c3ca97eb4/src/appwindow.cpp#L165-L170

**Comment by coder3101** [comment]
@sonulohani could you de-list this video https://youtu.be/GQ1hvU0RZmE

**Comment by sonulohani** [comment]
> @sonulohani could you de-list this video https://youtu.be/GQ1hvU0RZmE

Done

**Comment by coder3101** [comment]
Added in https://github.com/cpeditor/cpeditor/commit/1c6032f41dc833367cda6ff25500dbdb0e6620d5
