### ISSUE TITLE
Selected characters in Dark Fusion has dark background

### ISSUE THREAD

**Issue by tiger2005** [cpeditor/cpeditor#788]
When I open Dark Fusion and use Monokai to write code, I found that the selected code are black and difficult to see clearly.
![AOLOONHKXPQKCKY$@EQ(%JL](https://user-images.githubusercontent.com/41613797/110744826-4c6e1780-8275-11eb-84a9-961bc029b984.png)
It doesn't affect the use of editor, but I think it's better to make the selected characters white so that they can be seen clearly.
Here is how Sublime Text solves the problem.
![_J~%P@GZ36J@RA$O{ASDIFL](https://user-images.githubusercontent.com/41613797/110745007-93f4a380-8275-11eb-8af5-8eea188eae0a.png)
Sorry for my poor English as I'm a Chinese.

**Comment by coder3101** [comment]
More information required:

1. Version of cpeditor
2. Your OS
3. Your system theme
4. Anything else you find could be helpful for us.

**Comment by coder3101** [comment]
@all-contributor add @tiger2005 for bugs

**Comment by tiger2005** [comment]
Install by cpeditor-6.8.1-windows-x86-setup.exe
Here are some of the information of the computer.
![PS6I6_4U7UI9O2U0( OXKCG](https://user-images.githubusercontent.com/41613797/110753352-71688780-8281-11eb-9694-c1aab9429c68.png)

**Comment by coder3101** [comment]
> Install by cpeditor-6.8.1-windows-x86-setup.exe
> Here are some of the information of the computer.
> ![PS6I6_4U7UI9O2U0( OXKCG](https://user-images.githubusercontent.com/41613797/110753352-71688780-8281-11eb-9694-c1aab9429c68.png)
> 
> 

Need some more information. See above

**Comment by coder3101** [comment]
@all-contributors add @tiger2005 for bug

**Comment by tiger2005** [comment]
The selected characters are always black in Dark Fusion mode, no matter what kind of editor style I choose.

**Comment by coder3101** [comment]
@sonulohani can you confirm and would you like to fix it?

**Comment by coder3101** [comment]
@tiger2005 what is CP Editor version? Open cpeditor and `Help->About CP Editor`

**Comment by sonulohani** [comment]
> @sonulohani can you confirm and would you like to fix it?

I would like to fix this. Please assign this to me. Thanks

**Comment by tiger2005** [comment]
The selected characters are always black in Dark Fusion mode, no matter what kind of editor style I choose.

**Comment by tiger2005** [comment]
version was given in a previous comment, v6.8.1

**Comment by sonulohani** [comment]
I can confirm that with Dark fusion the selection shows in black color.
