### ISSUE TITLE
Use more structured file format to refactor the setting system

### ISSUE THREAD

**Issue by neko-para** [cpeditor/cpeditor#798]
**Is your feature request related to a problem? Please describe.**
As it's better to recontruct the current setting system before start solving #532, I open this issue.
The ini format has forced us to store settings in a single plane, which is not suitable for object-like settings, especially the snippets and parentheses. Currently we use symbol '/' to emulate levels and path, but this problem won't disappear.

**Describe the solution you'd like**
Use json/xml to store settings and rebuild genSettings.

**Remark**
Actually it's not necessary to change the file format. I can just parse the ini and build a more structured system(build a tree), but I think it's a chance to make a change.

**Comment by ouuan** [comment]
I think the file format doesn't matter. Now we are saving `a.b.c` at `a/b/c`, but if `a` and `a.b` are both `QVariantMap`s, we can simply save `a` at `a`.
