### ISSUE TITLE
Get samples incorrectly

### ISSUE THREAD

**Issue by Acfboy** [cpeditor/cpeditor#802]
**Describe the bug**

In some cases, CP Editor gets the wrong samples from Compitive Companion 
**To Reproduce**

Luogu P1185

**Screenshots**

![捕获](https://user-images.githubusercontent.com/36621731/111713771-3373f080-888b-11eb-9f51-8e723bef021f.PNG)

**Environment**

 - OS: Windows 7
 - CP Editor Version: 6.7.2

**Additional context**

?

**Comment by coder3101** [comment]
Can you provide the problem url?

**Comment by coder3101** [comment]
Run the competitive companion in debug mode and inspect what it sends to cpeditor.

**Comment by Acfboy** [comment]
> Can you provide the problem url?

<https://www.luogu.com.cn/problem/P1185>

**Comment by StudyingFather** [comment]
I tested it in the debug mode of the Competitive Companion, getting wrong data in the console.

So it's Competitive Companion that does not work properly, not CP Editor.

**Comment by ouuan** [comment]
https://github.com/jmerle/competitive-companion/issues/149
