### ISSUE TITLE
Integrate autocompletion for different languages

### ISSUE THREAD

**Issue by prayutsu** [cpeditor/cpeditor#831]
**Is your feature request related to a problem? Please describe.**

We should also have an option to integrate auto-completion for various languages like other IDEs (VS code, CLion etc).

**Describe the solution you'd like**

Either we can have an option in the IDE itself to enable auto-completion or we should introduce support for some extension that does the same job.

**Describe alternatives you've considered**

NA

**Additional context**

NA

**Comment by coder3101** [comment]
Duplicate of #156
