### ISSUE TITLE
Swap-line shortcuts don't work on macOS

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#863]
**Describe the bug**

> When I try to swap lines with the command that CP Editor has configured in macOS (Command+Shift+(Up or Down Arrow)) it doesn't work, because in macOS, the shortcut Command+Up Arrow for example when used in text, moves the cursor from the current cursor position to the beginning, and Command+Down to the end
>
> So when you also use Shift, what you get is that you select all the way to the beginning or all the way to the end, depending on the direction you have chosen.
>
> The thing is that this shortcut is native to macOS and takes precedence over CP Editor, i.e. it never swaps lines.

**Additional context**

> what is the possibility to change the shortcut by another key combination like in Sublime Text(Command+Cntrl+Up arrow) or VSCode(Alt+Up arrow)

#862

**Comment by ouuan** [comment]
@allcontributors add @rbruno95 for reporting a bug.

**Comment by neko-para** [comment]
Maybe we can change the default setting according to the OS or customize it in the first run.

**Comment by ps-19** [comment]
@rbruno95 @neko-para can you tell me which i need to change?? Updating README.md isn't a permanent solution. I would like to work on this issue. Kindly assign me.

**Comment by swift-zym** [comment]
> @rbruno95 @neko-para can you tell me which file is needed to changed?? Updating README.md isn't a correct solution for this issue. I would like to work on this issue. Kindly assign me.

What do you mean by "updating README"？

**Comment by ouuan** [comment]
> Updating README.md isn't a correct solution for this issue.

You can read https://allcontributors.org/. But even you are not familiar with all-contributors, I don't know why you thought a comment was a solution. After all, this issue is still open, which means we didn't state that we had provided a solution.

**Comment by ps-19** [comment]
> 
> 
> > Updating README.md isn't a correct solution for this issue.
> 
> You can read https://allcontributors.org/. But even you are not familiar with all-contributors, I don't know why you thought a comment was a solution. After all, this issue is still open, which means we didn't state that we had provided a solution.

I didn't know about https://allcontributors.org/. I was searching for an issue to work upon. I thought someone updated README.md file and didn't corrected actual file. I commented so that anyone will assign me this issue and i will resolve it.

**Comment by coder3101** [comment]
@ps-19 it's fine, you can pick another issue andI will assign it to you. This is already being fixed by ouuan's PR referenced above.

[These](https://github.com/cpeditor/cpeditor/labels/good%20first%20issue)are good beginner friendly issues you can work to fix, or you can choose any other issue and ask our help if you don't understand something. Contribution are always welcomed!

**Comment by ps-19** [comment]
@coder3101 thank you for your response.
