### ISSUE TITLE
Detached Execution is not working in Windows when using clang

### ISSUE THREAD

**Issue by coder3101** [cpeditor/cpeditor#872]
**Describe the bug**

Detached execution is not working on Windows 10 with clang

**To Reproduce**

1. Run detached and instead of launching program it says 'C:/Users/`<name>`/AppData/Local/Temp/CP" "Editor-iGoJIc/sol' is not recognized as an internal or external command,
operable program or batch file.

**Screenshots**

**Environment**

Windows 10 21H1
Build from master (4756571)

**Additional context**

The problem is no related with spaces in path to executable, it seems to be related with the fact that `cmd` can only execute programs with ending `.exe`.

A compile command like `g++ hello.cpp -o hello` produces `hello.exe` however, `clang++ hello.cpp -o hello` it produces `hello`.

To be on safe side we can pass the path with suffix (exe) and it produces correct binary for both the compilers.

**Comment by ouuan** [comment]
Can you bisect to find the first bad commit?

**Comment by coder3101** [comment]
The problem is related with https://github.com/cpeditor/cpeditor/blob/b637dc6f8d48dd6f653139619f437d3cba99a5e7/src/Core/Compiler.cpp#L86

If we use g++ a compile command like `g++ hello.cpp -o hello` produces `hello.exe` however if we use clang++ `clang++ hello.cpp -o hello` it produces `hello`.

I think we should change that line to:         

```cpp
args << QFileInfo(tmpFilePath).canonicalFilePath() << "-o" << outputFilePath(tmpFilePath, sourceFilePath, "C++");
```

To be on safe side we can pass the path with suffix and it produces correct binary for both the compilers.
