### ISSUE TITLE
Bug that code gives non-zero exit code but works on other ide's

### ISSUE THREAD

**Issue by Suyash-leo** [cpeditor/cpeditor#881]
**Describe the bug**
A cpp code gives non-zero exit code while works fine on other ide's

A code written in cpp language gives non-zero exit code and produces no output on running.

**To Reproduce**
https://ideone.com/vXwyUs
paste the given code in the editor section and take the sample input (for example input could be- 9 9 99). Now compile and run this code.

**Screenshots**

![image](https://user-images.githubusercontent.com/55657523/122640164-8c1d8880-d11b-11eb-9411-37e59843ced5.png)

**Environment**

![image](https://user-images.githubusercontent.com/55657523/122640189-aeafa180-d11b-11eb-92a6-0eb101fdf530.png)

**Additional context**

This same code got accepted on codeforces and also works fine on geeksforgeeks ide, etc

**Comment by ouuan** [comment]
You can learn about [undefined behaviors](https://en.wikipedia.org/wiki/Undefined_behavior). For your code, you can try declaring the `dp` array outside of the `main` function. However, this has nothing to do with CP Editor. It's the compiler that differs.

BTW, it's highly recommended to update your CP Editor, 6.3.4 is too old.

**Comment by Suyash-leo** [comment]
thanks for the quick and detailed response
