### ISSUE TITLE
能否更新一下app icon

### ISSUE THREAD

**Issue by qinyihao** [cpeditor/cpeditor#890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

cpeditor的图标在launchpad里面比较不和谐

### Describe the feature you'd like

能否加入如下图片作为icon：
![photo](https://user-images.githubusercontent.com/40647091/123257017-346c8c00-d524-11eb-8f2b-7e3565d458d7.png)

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
We don't accept Chinese issues here. Please use [the Chinese community](https://github.com/cpeditor/cpeditor-cn).
