### ISSUE TITLE
Python language server doesn't start with latest jedi version

### ISSUE THREAD

**Issue by tusqasi** [cpeditor/cpeditor#892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This error pops up in messages window
`[Language server sent an error. Please check log for details.]`

No yellow underlines, no linting

### Expected Behavior

That should not come, and language linting and goodies should work.

Wrong syntax should be highlighted

### Steps To Reproduce

1. Open python file (doesn't matter if on disk or hot saved)
2. That error pops up

### CP Editor Version

6.7.2

### OS

Manjaro

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

### Anything else?

Looking at the logs I found

```    "message": "pkg_resources.VersionConflict: (jedi 0.18.0 (/home/tusqasi/.local/lib/python3.9/site-packages), Requirement.parse('jedi<0.18.0,>=0.17.2'))```

then...
I removed 0.18.0, installed 0.17.2, then it works as expected. 

Is this this even a `cpeditor` problem or a `pyls` issue?

PS. this new form thing will taking time getting used to. (for me at least)

**Comment by tusqasi** [comment]
I tried to run with `jedi==0.17.2` in a venv, can confirm it is jedi version problem

is this relevant here  though?

**Comment by ouuan** [comment]
I don't think it's relevant to CP Editor. The `VersionConflict` in the log sounds like the version doesn't meet other packages' requirements.
