### ISSUE TITLE
cpeditor-6.8.2 Hotkeys（F11） not working

### ISSUE THREAD

**Issue by Transmigration-zhou** [cpeditor/cpeditor#900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

cpeditor-6.8.2 F11 of Hotkeys not working,other Hotkeys are uncertain
but cpeditor-6.7.1 can work normally 

### Expected Behavior

cpeditor-6.8.2 F11 can work normally 

### Steps To Reproduce

cpeditor-6.8.2 F11 of Hotkeys not working,other Hotkeys are uncertain
but cpeditor-6.7.1 can work normally 

### CP Editor Version

6.8.2

### OS

window10

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
See https://github.com/cpeditor/cpeditor/blob/master/CHANGELOG.md
