### ISSUE TITLE
Python syntax highlighting does not work some times

### ISSUE THREAD

**Issue by tusqasi** [cpeditor/cpeditor#901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`elif` is white
![image](https://user-images.githubusercontent.com/24749908/124301126-ffdc7e00-db7c-11eb-8abf-20047348aeb2.png)

### Expected Behavior

`elif` should be same color as `if`

### Steps To Reproduce

happens in python files

### CP Editor Version

6.9.0

### OS

Manjaro

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

### Anything else?

This is not about the theme, I changed the editor theme and that did not help.

I am pretty sure this is related to cpeditor.

**Comment by coder3101** [comment]
#516 will fix it. The highlighting is done by a regex matcher so it's very naive.

**Comment by tusqasi** [comment]
Should i close this issue then?
