### ISSUE TITLE
lcm function not recognized in cpp

### ISSUE THREAD

**Issue by Suyash-leo** [cpeditor/cpeditor#905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

an unexpected error occurred when i used the lcm function in cpp to calculate the least common multiple of two numbers. The function exists in c++17 and runs fine on other ide like codechef etc.

![image](https://user-images.githubusercontent.com/55657523/124622132-78eb1680-de98-11eb-8001-722784353ac1.png)

### Expected Behavior

I expect cp editor to recognise this function called lcm and give the required output.

### Steps To Reproduce

paste the below given code in cp editor and compile it.
Code starts below-

#include <bits/stdc++.h>
#include <numeric>

using namespace std;

#define int long long int
#define double long double
#define test int tttt; cin>>tttt; while(tttt--)
#define mod 1000000007    
#define pb push_back
#define vi vector<int>
#define yes cout<<"YES"<<"\n"
#define no cout<<"NO"<<"\n"
#define ff first
#define ss second
#define line cout<<"\n"
#define all(x) x.begin(), x.end()

//////////////////////////////////////////////////////////////////////

/*void messigoat(){ #ifndef ONLINE_JUDGE freopen("input.txt", "r", stdin);freopen("output.txt", "w", stdout); #endif }*/
void messiforever() {ios_base::sync_with_stdio(false);cin.tie(NULL);cout.tie(NULL);}
int gcd(int a, int b){if(b==0)return a;return gcd(b,a%b);}
bool prime(int n){for(int i=2;i*i<=n;i++){if(n%i==0)return false;}return true;}
long long binexpm(long long a, long long b, long long m) {a %= m;long long res = 1;while (b > 0) {if (b & 1)res = res * a % m;a = a * a % m;b >>= 1;}return res;}
long long binexp(long long a, long long b) {long long res = 1;while (b > 0) {if (b & 1)res = res * a;a = a * a;b >>= 1;}return res;}
void arrin(int arr[], int n){for(int i=1;i<=n;i++)cin>>arr[i];}

//////////////////////////////////////////////////////////////////////
		//******* MESSI is the G*O*A*T *******//
/*		
⠀⠀⠀⠀⣠⡤⠒⠂⢀⣈⣉⠉⠑⠒⠢⠤⡀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⡰⠉⢁⣰⣶⣾⣿⣿⣿⣿⣷⣶⣼⣶⣼⣆⠀⠀⠀⠀⠀⠀
⠀⢠⣁⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⡀⠀⠀⠀
⠀⣿#byFCA⠛⠉⠉⠁⠀⠈⠉⠉⠙⠻⣿⣿⣷⣿⡄⠀⠀
⠀⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣿⣷⣿⢱⠀⠀
⠀⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣟⠂⡇⠀
⠀⣿⣿⠀⢀⣤⣶⣶⣦⠀⠀⢠⣴⣿⣷⣶⡄⠀⠘⢿⣿⣧⡇⠀
⢸⣿⡏⠀⠠⡶⢽⡶⠿⠃⠀⠘⢿⠿⠶⠟⠿⠂⠀⢸⣿⣿⡿⡀
⡜⢿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠟⠋⠀⡇
⢱⠈⠙⠀⠀⠀⠀⣠⢠⣤⣤⣤⣤⣤⡤⡀⠀⠀⠀⠀⠀⣤⠀⢰
⢸⠀⢢⡄⠀⠀⠴⣧⣴⡶⢿⢿⣿⣿⣿⣾⣦⠀⡀⢠⣆⠀⠙⠸
⢠⠀⠈⣷⣀⡀⠨⣿⢿⢋⣉⣉⣉⣙⡿⣿⡿⣠⣟⣾⡿⣤⡠⠂
⠘⠦⠤⣿⣿⣷⣼⣿⠀⠉⠉⠉⠉⠉⠀⢸⣿⣿⣿⣿⣿⠁⠀⠀
⠀⠀⠀⢸⢻⣿⣿⣿⣶⡀⠾⣦⣷⠔⢧⣾⣿⣿⣿⣿⢸⠀⠀⠀
⠀⠀⢀⣾⠀⠉⣿⣿⣿⣧⣦⣻⣳⣶⣿⣿⣿⣾⣿⡿⢸⠀⠀⠀
⠀⢀⣿⣿⡀⠈⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⢸⣧⠀⠀
⠀⢸⣿⣿⣇⠀⠈⠿⢿⣿⣿⣿⣿⣿⣿⣿⠿⠛⠀⠀⣿⣿⡆⠀
⠀⠈⢿⣿⣿⡄⠀⠀⠀⠉⠛⠛⠛⠛⠉⠁⠀⠀⠀⠀⣿⣿⣇⠀
⠀⠀⢸⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿⣿⣿⠀
⠀⠀⠀⣿⣿⣿⣿⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⡇⠀
⠀⠀⠀⠘⢿⣿⣿⣿⣧⡀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⠟⠁⠀
⠀⠀⠀⠀⠀⠙⠿⢿⣿⣿⣶⣄⡀⠀⠀⠀⠀⣰⣿⣿⠋⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣦⠀⠀⠀⣿⣿⠃⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⣿⣿⣷⣤⣺⣿⡇⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⠿⣿⠿⠋⠀⠀⠀⠀⠀⠀
🐐🐐 LIONEL MESSI 🐐🐐	
*/			
//////////////////////////////////////////////////////////////////////

int32_t main()
{	
	messiforever(); //messigoat();
	
	test
	{
		int n; cin>>n;
		int ans=0;
		int prev=1;
		for(int i=2;i<=100000000;i++)
		{
			int nxt=lcm(prev,i);
			int cur=n/prev;
			cur-=n/nxt;
			ans+= cur*i;
			prev=nxt;
			if(nxt>n)
			break;
		}
		cout<<ans%mod<<"\n";
	}
	
	
	return 0;
}

### CP Editor Version

6.8.2

### OS

Windows 10

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
Add `-std=c++17` in your C++ Compile Command.

**Comment by StudyingFather** [comment]
Obviously it's not CP Editor's fault.

Whether the `lcm` function is provided depends on the compiler you used.
