### ISSUE TITLE
In C++ syntax highlighting, common types like 'string' or 'int64_t' are not highlighted in a consistent way.

### ISSUE THREAD

**Issue by hpfdf** [cpeditor/cpeditor#906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/5363617/124834209-5a932280-df4d-11eb-9507-3c0cbd85adad.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/5363617/124834218-5e26a980-df4d-11eb-92e2-28f3b3416cd5.png)

### Steps To Reproduce

1. Create a new C++ file.
2. Type the following code:
```cpp

// Expected:

int pw(int a, int b, int c = M) {
    int ans = 1;
    while (b) {
        if (b & 1) ans = ans * a % c;
        a = a * a % c;
        b >>= 1;
    }
    return ans;
}

int iv(int x) {
    return pw(x, M - 2);
}

// Actual:
int64_t pw(int64_t a, int64_t b, int64_t c = M) {
    int64_t ans = 1;
    while (b) {
        if (b & 1) ans = ans * a % c;
        a = a * a % c;
        b >>= 1;
    }
    return ans;
}

int64_t iv(int64_t x) {
    return pw(x, M - 2);
}

```

### CP Editor Version

6.9.2

### OS

Windows 10

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

### Anything else?

This is true on all editor themes.

https://github.com/cpeditor/cpeditor/pull/516 may solve this.  I understand that will be a substantial change.  But there are always ways to make the change smoothly:  you could ship a version that support both and make the new editor an optional feature controlled by a toggle/checkbox in settings.  I don't mind if you ship a workable version and say it is experimental, then improve on the go.

**Comment by coder3101** [comment]
> #516 may solve this. I understand that will be a substantial change. But there are always ways to make the change smoothly.

It indeed will fix all these issues. The smooth transition is not required since we plan to release the next major release 7.0 with the above PR merged.
