### ISSUE TITLE
The output box doesn't show the outputs after '\0'.

### ISSUE THREAD

**Issue by Mooos-MoSheng** [cpeditor/cpeditor#907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the output box, the outputs which is after a ‘\0’ is not shown.
The Code:
![image](https://user-images.githubusercontent.com/46639923/124848098-bb167400-dfce-11eb-8a22-c54cd22fd98a.png)
In The Output Box:
![image](https://user-images.githubusercontent.com/46639923/124848198-f4e77a80-dfce-11eb-85c6-2b51ee1866c7.png)

### Expected Behavior

I think it should be (In PowerShell):
![image](https://user-images.githubusercontent.com/46639923/124848245-0a5ca480-dfcf-11eb-92a4-d78886aaaf55.png)

### Steps To Reproduce

```cpp
#include <iostream>
int main()
{
	std::cout << "___" << '\0' << std::endl
			  << "CANNOT SEE ME";
}
```

### CP Editor Version

6.8.2

### OS

Windows 10

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment]
The outputs are handled at

- https://github.com/cpeditor/cpeditor/blob/90c995c1c6a97ab070e739d94b042926f2ef5d99/src/Core/Runner.cpp#L173
- https://github.com/cpeditor/cpeditor/blob/90c995c1c6a97ab070e739d94b042926f2ef5d99/src/Core/Runner.cpp#L185

`QProcess::readAllStandardOutput` returns a QByteArray, and [QByteArray stores `\0`s](https://doc.qt.io/qt-5/qbytearray.html#details), so we only need to [replace](https://doc.qt.io/qt-5/qbytearray.html#replace-3) `'\0'` with `""`.
