### ISSUE TITLE
Run custom scripts

### ISSUE THREAD

**Issue by cs-mshah** [cpeditor/cpeditor#914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### Describe the feature you'd like

It would be great if CP editor supports execution of custom scripts. This would make it possible for anyone to have small extensions of their own. Here are a few examples where they are extremely useful.

- Execution of a script before submitting: If I am using my own header files (Ex: atcoder library for example) and I want to submit to some other site, then I need to fill my solution file with the functions from the header using something like generate.py before submitting.
- executing a script after saving, to rename the file and put it in an appropriate directory.
- push to github on a command.
- custom script to submit to various judges.

Here's how the feature should work:
> - Have a separate section in preferences for scripts.
> - scripts get executed on actions like: `on hotkey press`, `onsave`, `on POST request`, `onexit`, `onsubmit`, `oncompile`, `onrun`, `on compile and run`, `on start of editor` and many more as the editor expands.
> - for every entry of action, there is a list of scripts that you want to run : either one after the other or asynchronously.
> - To start with, we need to provide the path to the script and parameters to run the script or the run command. Parameters include the all predefined variables of CP editor like: ${filename}, ${basename}, ${filepath} etc.

Ex: python generate.py ${filepath}

> There can be a separate window pane next/below messages showing the logs for the successful run of the scripts/output provided by them (if any).

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

### Anything else?

Keep this feature with **_high priority_**, as this is extremely useful and will expand the possibilities of the editor

**Comment by ouuan** [comment]
It will be nice to support running custom scripts. However, here are some alternative solutions/suggestions about the example use cases you provided/

> Execution of a script before submitting: If I am using my own header files (Ex: atcoder library for example) and I want to submit to some other site, then I need to fill my solution file with the functions from the header using something like generate.py before submitting.

You can add the header in the code template or in several snippets. It's hard to do so for some big libraries, but I suppose in that case it will also be hard for custom scripts.


> executing a script after saving, to rename the file and put it in an appropriate directory.

Have you checked [Default File Path For Problem URLs](https://cpeditor.org/docs/preferences/file-path/#default-file-path-for-problem-urls)?

> push to github on a command.

I'm wondering how this is notably better than doing it in the terminal :thinking: 

> custom script to submit to various judges.

There's #212 for this.

**Comment by cs-mshah** [comment]
@ouuan It isn't a good idea to populate the template, for readability reasons. That's one main reason why we would like to have functions in separate header files and when solving, just include them. What the script would do is simply create a copy of the current file and submit the copy with the "header.h" removed and the contents of the header populated in it. After submitting, it could destroy this temporary file. So all I need to do is something like #include <datastructures.h>, and have a on submit script which would do the job.   <br>
For the case of saving, I use a little complicated rule for saving. like for codeforces: "cf <problem_name>.cpp", cc: codechef, at: atcoder, and these go to the respective folders based on the site. So, I already first quickly save wherever CP editor does and then with a terminal run "CP" (alias to run my script), which basically moves the file to the directory and renames it accordingly (by reading the comment header at the top)  <br>

For the case of submitting, #212 is still not done. But if we have our own or want to use one, we can use it.  

These are just a few use cases, but there could be even more. For example, I could have my own stress testing script and all I need is to edit the script and test my code against it. So all this can just be done with a few shortcuts and I can immediately see the results.

**Comment by ouuan** [comment]
> @ouuan It isn't a good idea to populate the template, for readability reasons.

If you don't want to see a whole screen of codes, you can compress it and move it out of screen: https://github.com/ouuan/CF-template/blob/master/template_compressed.cpp. Headers can also be compressed to a single line and stored in a snippet.

If you don't want to scroll to the main function, there's [Template Cursor Position](https://cpeditor.org/docs/preferences/language/#template-cursor-position).

> For the case of saving, I use a little complicated rule for saving. like for codeforces: "cf <problem_name>.cpp", cc: codechef, at: atcoder, and these go to the respective folders based on the site. So, I already first quickly save wherever CP editor does and then with a terminal run "CP" (alias to run my script), which basically moves the file to the directory and renames it accordingly (by reading the comment header at the top)

This doesn't explain why [Default File Path For Problem URLs](https://cpeditor.org/docs/preferences/file-path/#default-file-path-for-problem-urls) doesn't work. Your description sounds like exactly what this feature does. Do you want #580 instead? I see your "+1" reaction there.

> For example, I could have my own stress testing script and all I need is to edit the script and test my code against it. So all this can just be done with a few shortcuts and I can immediately see the results.

There's also #162.

**Comment by ouuan** [comment]
Yeah, it will be definitely nice to have a good plugin system, but it's hard to develop such a system. The main reason plugins are important and work fine in other text editors is that other editors are multi-purpose, while CP Editor is targeted at competitive programmers, which limits the use case. I don't mean plugins are useless in a specially designed IDE, but it's less important.

**Comment by ouuan** [comment]
I thought this was requested before but failed to find it because it was moved to Discussions by mistake: #638. Now closing this in favor of it.

**Comment by rogeryoungh** [comment]
I think this feature is useful, just a simple plugin system can do a lot of things.
