### ISSUE TITLE
Collapsible code sections

### ISSUE THREAD

**Issue by cs-mshah** [cpeditor/cpeditor#915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

I have to scroll through large templates and classes.

### Describe the feature you'd like

If functions, classes and other similar structures are collapsible (like sublime text), the code would be much east to read and sift through.  
![image](https://user-images.githubusercontent.com/56499208/124916967-e28e3080-e010-11eb-9e99-fd1238bbab95.png)  
Something similar to the above is useful.

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by swift-zym** [comment]
Will be a part of #516.
