### ISSUE TITLE
Zooming in/out Laggy + auto-zooms in/out when saving

### ISSUE THREAD

**Issue by lethan3** [cpeditor/cpeditor#920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Kind of low-priority, but sometimes I accidentally zoom in and out using the trackpad and it takes a while (1-2 seconds) for it to resize to the new size. I don't think this is an issue with my computer, since zooming is very quick on notepad++.

### Expected Behavior

Zooms in/out quickly, without lagging

### Steps To Reproduce

1. Open a file
2. Write some code
3. Try zooming in/out by pinching trackpad, lags for 1-2 seconds

### CP Editor Version

6.7.2

### OS

Windows 10

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
Can you test 6.8.2 or 6.9.2? Is it faster / completely no lagging / still the same?

**Comment by ouuan** [comment]
> I updated to 6.8.2, and it still seems to be lagging. Maybe a good temporary fix would be to have a setting to turn off zoom by pinching and instead add font resize buttons/ font size in settings?

There are font size settings in the preferences window right now.

**Comment by ouuan** [comment]
How many tabs did you open? Now all tabs are updated when you change the font size.

**Comment by lethan3** [comment]
Before I did open a lot of tabs, now since I have only ~2 open at a time it's faster now. Thanks!
