### ISSUE TITLE
AUR stable is outdated

### ISSUE THREAD

**Issue by coder3101** [cpeditor/cpeditor#937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently AUR stable is marked out of date. https://aur.archlinux.org/pkgbase/cpeditor/

### Expected Behavior

CI should have updated the package: https://github.com/cpeditor/cpeditor/actions/runs/1056247474 

Seems the job version check failed.

### Steps To Reproduce

N/A

### CP Editor Version

N/A

### OS

N/A

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
It's fixed in cad4cbc395f030c77cd1b77b8ca38a59a16aad6d which is committed after 6.8.3. I think we'd better manually update the AUR package this time.

**Comment by coder3101** [comment]
We should close once it is updated. I will update the title to say " AUR stable is outdated "

**Comment by coder3101** [comment]
> manually update the AUR package for this time.

It needs updating SSH keys in AUR and GitHub Secrets. It could take some time.

**Comment by coder3101** [comment]
Cannot update as `aur.archlinux.org` is down.
