### ISSUE TITLE
Add a goto to problem URL function

### ISSUE THREAD

**Issue by tusqasi** [cpeditor/cpeditor#945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

When I stop solving problems for the day, I'll close the editor and the tabs.

Next day I have to copy the URL and paste it in the browser.

### Describe the feature you'd like

Press a key board short cut and it send the URL to the browser. 

### Describe alternatives you've considered

None yet, when running custom scripts on the file comes out, I can try some shell shenanigans.

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment]
There are already "Open Problem in Browser" in the context menu of a tab bar whose problem URL is set, and [Bind file and problem](https://cpeditor.org/docs/preferences/actions/#bind-file-and-problem) which can restore the problem URL after reopening the corresponding file.
