### ISSUE TITLE
Modern Greek translation

### ISSUE THREAD

**Issue by RysteQ** [cpeditor/cpeditor#972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### Describe the feature you'd like

I just want to help by adding a new language, that language being modern Greek

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment]
There are three parts to translate:

1. Docs in the repository (README, CONTRIBUTING, etc.)
2. Texts in the application.
3. Pages on the website.

Would you like to translate all of them or some of them?

**Comment by RysteQ** [comment]
For now I will translate the text in the application, after that is done I will translate the ReadMe and Contributing files too

**Comment by ouuan** [comment]
Just want to make sure, is the language code "el_GR"?

**Comment by RysteQ** [comment]
Yes it is, I have been working on the translation by using a russian translation file and changing the properties with Qt Linguist, I am almost 1/5 done !

**Comment by RysteQ** [comment]
I created a pull request for the ts file, in a few days I will add the translated ReadMe.md file !

**Comment by ouuan** [comment]
You should add "This fixes #972" in the body of #984 (see [Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)) instead of closing this before #984 is merged.
