### ISSUE TITLE
Copy Code Button in for each tab 

### ISSUE THREAD

**Issue by s-i-d-d-i-s** [cpeditor/cpeditor#989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

I'm looking for a button to copy the source code to clipboard. It's a bit of pain to press Ctrl + A, Ctrl + C each time.

### Describe the feature you'd like

Add a button near Compile and Run to copy the source code in current editor

### Are you willing to contribute to this?

- [X] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

### Anything else?

I may try to fix this myself since the code is open source, but still i wanted to put this as a reminder if i am not able to.

**Comment by swift-zym** [comment]
Doesn't it takes more time to tap a button than to press Ctrl + A and Ctrl + C?
