### ISSUE TITLE
Fail to execute wakatime when file path includes spaces

### ISSUE THREAD

**Issue by swift-zym** [cpeditor/cpeditor#991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

CP Editor generated command like `wakatime --entity /xxx folder/a.cpp`

### Expected Behavior

CP Editor should generate command like `wakatime --entity "/xxx folder/a.cpp"`

### Steps To Reproduce

1. Open a file in any directory which includes spaces

### CP Editor Version

6.10.0

### OS

macOS Monterey

### Are you willing to contribute to this?

- [X] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment]
I suspect that you saw the unquoted command in the log, which is not the real command.
